coverage:
  precision: 2
  round: down
  range: "70...100"

flag_coverage:
  - unit_tests
  - integration_tests

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_metrics: false

ignore:
  - "**/*.md"
  - "docs/"
  - "examples/"
  - "tools/"

codecov:
  require_ci_to_pass: true

json:
  pretty: true
