from __future__ import annotations

from typing import Any

import numpy as np
from numpy.typing import NDArray

SchemaDict = dict[str, Any]

class FluxionError(Exception): ...
class ValidationError(FluxionError): ...
class SurrogateError(FluxionError): ...
class SimulationError(FluxionError): ...

class OsmReader:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def from_path(path: str) -> OsmReader: ...
    def to_schema_dict(self) -> SchemaDict: ...

class OsmWriter:
    def __init__(self, schema: SchemaDict) -> None: ...
    @staticmethod
    def from_schema_dict(schema: SchemaDict) -> OsmWriter: ...
    @staticmethod
    def from_schema_file(path: str) -> OsmWriter: ...
    def export(self, path: str) -> None: ...
    def to_schema_dict(self) -> SchemaDict: ...

class MultiZoneThermalModel:
    def __init__(self, num_zones: int = 2) -> None: ...
    @staticmethod
    def from_case_spec(case_id: str) -> MultiZoneThermalModel: ...
    def num_zones(self) -> int: ...
    def get_zone_temperatures(self) -> list[float]: ...
    def set_zone_temperatures(self, temps: list[float]) -> None: ...
    def get_zone_energies(self) -> list[float]: ...
    def get_hourly_temperatures(self) -> list[list[float]] | None: ...
    def get_hourly_temperatures_numpy(self) -> tuple[NDArray[np.float64], list[int]]: ...
    # Issue #1799 — sub-hourly 9R4C node temperature traces
    def get_nodal_temperatures(self) -> list[list[list[float]]] | None: ...
    def get_nodal_temperatures_numpy(self) -> tuple[NDArray[np.float64], list[int]]: ...
    def num_multinode_solvers(self) -> int: ...
    def nodal_temperature_node_names(self) -> list[str]: ...

def import_osm(path: str) -> SchemaDict: ...
def export_osm(schema: SchemaDict, path: str) -> None: ...
