from __future__ import annotations

from typing import Any

SchemaDict = dict[str, Any]

class FluxionError(Exception): ...
class ValidationError(FluxionError): ...
class SurrogateError(FluxionError): ...
class SimulationError(FluxionError): ...

class OsmReader:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def from_path(path: str) -> OsmReader: ...
    def to_schema_dict(self) -> SchemaDict: ...

class OsmWriter:
    def __init__(self, schema: SchemaDict) -> None: ...
    @staticmethod
    def from_schema_dict(schema: SchemaDict) -> OsmWriter: ...
    @staticmethod
    def from_schema_file(path: str) -> OsmWriter: ...
    def export(self, path: str) -> None: ...
    def to_schema_dict(self) -> SchemaDict: ...

def import_osm(path: str) -> SchemaDict: ...
def export_osm(schema: SchemaDict, path: str) -> None: ...
