"""Type stubs for the ``fluxion`` Python package (PyO3 bindings).

Auto-curated from the ``#[pymodule] fn fluxion`` registration in
``src/lib.rs`` plus the ``multi_zone`` submodule in ``src/python/bindings.rs``.
Every ``#[pyclass]`` registered in the primary ``fluxion`` module is listed
here. The drift gate ``scripts/check_pyi_drift.py`` (and the self-contained
Rust integration test ``tests/pyi_stub_completeness.rs``) assert that this file
stays in sync with the Rust registrations — see Issue #2509.

Rust→Python type translation conventions used throughout:
  ``&str``/``String`` → ``str`` · ``f64``/``f32`` → ``float`` ·
  ``usize``/``u32``/``i32`` → ``int`` · ``bool`` → ``bool`` ·
  ``Vec<T>`` → ``list[T]`` · ``Option<T>`` → ``T | None`` ·
  ``PyResult<T>`` → ``T`` (errors raised as ``FluxionError`` subclasses) ·
  ``&Bound<PyDict>``/``Py<PyDict>`` → ``dict[str, Any]`` ·
  ``Bound<numpy::PyArrayND<f64>>`` → ``NDArray[np.float64]`` ·
  ``HashMap<String, V>`` → ``dict[str, V]``.
"""

from __future__ import annotations

import enum
from typing import Any

import numpy as np
from numpy.typing import NDArray

# A schema dictionary (OpenStudio/gbXML/IFC interchange representation).
SchemaDict = dict[str, Any]


# ---------------------------------------------------------------------------
# Exception hierarchy
# ---------------------------------------------------------------------------

class FluxionError(Exception):
    """Base class for all fluxion runtime errors."""


class ValidationError(FluxionError):
    """Raised when building parameters or model inputs fail validation."""


class SurrogateError(FluxionError):
    """Raised when the ONNX surrogate model fails to load or infer."""


class SimulationError(FluxionError):
    """Raised when the thermal simulation fails to converge or step."""


# ---------------------------------------------------------------------------
# Top-level free functions
# ---------------------------------------------------------------------------

def import_osm(path: str) -> SchemaDict:
    """Import an OpenStudio ``.osm`` file into a schema dict."""


def export_osm(schema: SchemaDict, path: str) -> None:
    """Export a schema dict to an OpenStudio ``.osm`` file."""


def export_gbxml(schema: SchemaDict, path: str) -> None:
    """Export a schema dict to a Green Building XML (gbXML) file."""


def create_multi_zone_model_from_config(config: SchemaDict) -> MultiZoneThermalModel:
    """Build a :class:`MultiZoneThermalModel` from a config dictionary."""


def create_multi_zone_model_from_schema_file(schema_path: str) -> MultiZoneThermalModel:
    """Build a :class:`MultiZoneThermalModel` from a schema file on disk."""


def create_multi_zone_model_from_schema_dict(schema: SchemaDict) -> MultiZoneThermalModel:
    """Build a :class:`MultiZoneThermalModel` from an in-memory schema dict."""


def create_zone_setpoints(config: SchemaDict) -> ZoneSetpoints:
    """Construct :class:`ZoneSetpoints` from a config dictionary."""


def compute_vav_terminal_performance(
    terminal: VavTerminalUnit,
    entering_dry_bulb_c: float,
    entering_humidity_ratio: float,
    air_density_kg_per_m3: float,
    control: VavTerminalControl,
) -> VavTerminalPerformance:
    """Run the reference VAV terminal unit performance calculation."""


# ---------------------------------------------------------------------------
# Core model + optimization API
# ---------------------------------------------------------------------------

class Model:
    """Standard single-building model for detailed building energy analysis.

    Use this class when you need detailed simulation of a single building with
    full control over construction, HVAC, weather, and surrogate evaluation.
    """

    def __init__(self, num_zones: int = 1) -> None: ...
    def num_zones(self) -> int: ...
    def get_temperatures(self) -> list[float]: ...
    def set_temperatures(self, temps: list[float]) -> None: ...
    def building_type(self) -> str: ...
    def set_building_type(self, building_type: str) -> None: ...
    def simulate(self, years: int, use_surrogates: bool) -> float: ...
    def simulate_with_loads(self, years: int, use_surrogates: bool) -> float: ...
    def simulate_numpy(
        self,
        dry_bulb_temp: Any,
        dni: Any,
        dhi: Any,
        ghi: Any,
        wind_speed: Any,
        humidity: Any,
        horizontal_infrared: Any,
        use_surrogates: bool,
    ) -> NDArray[np.float64]: ...
    def load_surrogate(self, model_path: str) -> None: ...
    def get_parameter_bounds(self) -> ParameterBounds: ...
    def validate_parameters_py(self, params: list[float]) -> None: ...
    def set_ground_temp(self, temperature: float) -> None: ...
    def ground_temperature_at(self, timestep: int) -> float: ...
    def zones(self) -> list[Zone]: ...
    def surfaces(self) -> list[Surface]: ...
    def set_surfaces(self, surfaces: list[Surface]) -> None: ...
    def hvac_system(self) -> HVACSystem: ...
    def set_hvac_system(self, hvac: HVACSystem) -> None: ...
    def __repr__(self) -> str: ...


class BatchOracle:
    """High-throughput parallel oracle for quantum / genetic-algorithm optimization.

    This is the core API for bulk evaluation of building design parameter
    populations. ``evaluate_population`` is parallelised with rayon at the
    population level (see the Batch-Oracle pattern, AGENTS.md).
    """

    def __init__(self) -> None: ...
    def evaluate_population(
        self, population: list[list[float]], use_surrogates: bool
    ) -> list[float]: ...
    def evaluate_population_typed(
        self, population: list[BuildingParameters], use_surrogates: bool
    ) -> list[float]: ...
    def evaluate_population_numpy(
        self, population: Any, use_surrogates: bool
    ) -> NDArray[np.float64]: ...
    def load_surrogate(self, model_path: str) -> None: ...
    def get_parameter_bounds(self) -> ParameterBounds: ...
    def validate_parameters_py(self, params: list[float]) -> None: ...


class ParameterBounds:
    """Parameter bounds for building design variables.

    Provides programmatic access to the valid ranges for all design
    parameters used by :class:`BatchOracle` and :class:`Model`.
    """

    @staticmethod
    def get_bounds() -> ParameterBounds: ...


class BuildingParameters:
    """Type-safe building design parameters with validation.

    Fields: ``window_u_value`` (0.0–6.0 W/m²K), ``heating_setpoint``
    (15.0–25.0 °C), ``cooling_setpoint`` (22.0–32.0 °C). The heating setpoint
    must be strictly less than the cooling setpoint.
    """

    def __init__(
        self, window_u_value: float, heating_setpoint: float, cooling_setpoint: float
    ) -> None: ...
    def to_vec(self) -> list[float]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


# ---------------------------------------------------------------------------
# Construction + geometry value types
# ---------------------------------------------------------------------------

class MassClass(enum.Enum):
    """Thermal-mass classification for construction assemblies."""
    VeryLight = 0
    Light = 1
    Medium = 2
    Heavy = 3
    VeryHeavy = 4


class SurfaceType(enum.Enum):
    """Surface type for construction calculations."""
    Wall = 0
    Ceiling = 1
    Floor = 2


class ConstructionLayer:
    """A single material layer in a construction assembly (Python wrapper)."""

    def __init__(
        self,
        name: str,
        conductivity: float,
        density: float,
        specific_heat: float,
        thickness: float,
        emissivity: float = 0.9,
        absorptance: float = 0.7,
    ) -> None: ...
    def r_value(self) -> float: ...
    def thermal_capacitance_per_area(self) -> float: ...


class Construction:
    """Multi-layer construction assembly (Python wrapper)."""

    def __init__(self, layers: list[ConstructionLayer]) -> None: ...
    def r_value_total(
        self, surface_type: SurfaceType | None = None, exterior_wind_speed: float | None = None
    ) -> float: ...
    def u_value(
        self, surface_type: SurfaceType | None = None, exterior_wind_speed: float | None = None
    ) -> float: ...
    def thermal_capacitance_per_area(self) -> float: ...
    def total_thickness(self) -> float: ...
    def layer_count(self) -> int: ...
    def mass_class(self) -> MassClass: ...


class WallSurface:
    """Wall surface representation (area, U-value, orientation)."""

    def __init__(self, area: float, u_value: float, orientation: str) -> None: ...


class VectorField:
    """Vector field wrapper for Python with optimised numpy support."""

    def __init__(self, data: Any) -> None: ...
    @staticmethod
    def from_scalar(value: float, size: int) -> VectorField: ...
    def len(self) -> int: ...
    def to_list(self) -> list[float]: ...
    def to_numpy(self) -> NDArray[np.float64]: ...
    def integrate(self) -> float: ...
    def gradient(self) -> VectorField: ...


class GeometryTensor:
    """Python-accessible wrapper for the interior ``GeometryTensor``.

    ``inner`` is wrapped in an ``Arc`` so ``to_numpy`` can hand zero-copy
    views to Python without moving the underlying data.
    """

    def __init__(self) -> None: ...
    @staticmethod
    def from_numpy(
        zone_coords: Any,
        wall_matrix: Any,
        window_matrix: Any,
        adjacency_matrix: Any,
        zone_properties: Any,
        summary: Any,
    ) -> GeometryTensor: ...
    @staticmethod
    def borrow_f64_slice(arr: Any) -> list[float]: ...
    def num_zones(self) -> int: ...
    def num_walls(self) -> int: ...
    def total_area(self) -> float: ...
    def total_volume(self) -> float: ...
    def validate(self) -> list[str]: ...
    def get_summary(self) -> list[float]: ...
    def zones_adjacent(self, i: int, j: int) -> bool: ...
    def to_numpy(
        self,
    ) -> tuple[
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
    ]: ...
    @staticmethod
    def build_zero_copy_2d(
        inner: Any, shape: tuple[int, int], pick: Any
    ) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...


# ---------------------------------------------------------------------------
# Multi-zone thermal model
# ---------------------------------------------------------------------------

class MultiZoneThermalModel:
    """Multi-zone thermal model for Python (ASHRAE 140 + 9R4C multi-node)."""

    def __init__(self, num_zones: int = 2) -> None: ...
    @staticmethod
    def from_case_spec(
        case_id: str,
        zone_solver: str | None = None,
        conduction_solver: str | None = None,
    ) -> MultiZoneThermalModel:
        """Build a model from an ASHRAE 140 case id.

        ``zone_solver``: ``"gauge"`` (default) | ``"5r1c"`` | ``"9r4c"``.
        The experimental ``"6r2c"`` / ``"8r3c"`` values raise ``ValueError``
        unless ``FLUXION_EXPERIMENTAL_ZONE_SOLVERS=1`` is set (and stay
        unavailable until the experimental cargo feature ships; issue #3291).
        ``conduction_solver``: ``"default"`` (default) | ``"ctf"`` | ``"fd"``.
        """
        ...
    def num_zones(self) -> int: ...
    def get_inner_num_zones(self) -> int: ...
    def get_zone_temperatures(self) -> list[float]: ...
    def set_zone_temperatures(self, temps: list[float]) -> None: ...
    def set_zone_setpoints(self, zone_idx: int, heating: float, cooling: float) -> None: ...
    def get_inter_zone_conductance(self, zone_i: int, zone_j: int) -> float: ...
    def set_inter_zone_conductance(self, zone_i: int, zone_j: int, conductance: float) -> None: ...
    def set_inter_zone_conductance_vector(self, conductances: list[float]) -> None: ...
    def get_inter_zone_conductance_vector(self) -> list[float]: ...
    def simulate_multi_zone(self, years: int, use_surrogates: bool) -> float: ...
    def get_zone_energies(self) -> list[float]: ...
    def get_zone_peak_loads(self) -> dict[str, list[float]]: ...
    def get_zone_peaks(self, zone_identifier: Any) -> dict[str, Any]: ...
    def export_zone_temperatures(self) -> dict[str, Any]: ...
    def get_hourly_temperatures(self) -> list[list[float]] | None: ...
    def get_hourly_temperatures_numpy(self) -> tuple[NDArray[np.float64], list[int]]: ...
    # Issue #1799 — sub-hourly 9R4C node temperature traces
    def get_nodal_temperatures(self) -> list[list[list[float]]] | None: ...
    def num_multinode_solvers(self) -> int: ...
    def nodal_temperature_node_names(self) -> list[str]: ...
    def get_nodal_temperatures_numpy(self) -> tuple[NDArray[np.float64], list[int]]: ...
    def validate_energy_balance(self) -> bool: ...
    def validate_energy_balance_detailed(self) -> tuple[bool, float, int]: ...
    def is_energy_unbalanced(self) -> bool: ...


# ---------------------------------------------------------------------------
# OpenStudio I/O
# ---------------------------------------------------------------------------

class OsmReader:
    """Reader for OpenStudio ``.osm`` files."""

    def __init__(self, path: str) -> None: ...
    @staticmethod
    def from_path(path: str) -> OsmReader: ...
    def to_schema_dict(self) -> SchemaDict: ...


class OsmWriter:
    """Writer for OpenStudio ``.osm`` files."""

    def __init__(self, schema: SchemaDict) -> None: ...
    @staticmethod
    def from_schema_dict(schema: SchemaDict) -> OsmWriter: ...
    @staticmethod
    def from_schema_file(path: str) -> OsmWriter: ...
    def export(self, path: str) -> None: ...
    def to_schema_dict(self) -> SchemaDict: ...


# ---------------------------------------------------------------------------
# HVAC bindings (src/python/hvac_bindings.rs)
# ---------------------------------------------------------------------------

class HVACSystemType(enum.Enum):
    """HVAC system type (mirrors ``sim::hvac::HVACSystemType``)."""
    Simple = 0
    VAV = 1
    CAV = 2
    HeatPump = 3
    Ideal = 4


class HVACMode(enum.Enum):
    """HVAC operating mode: heating / cooling / off."""
    Heating = 0
    Cooling = 1
    Off = 2


class HeatPumpMode(enum.Enum):
    """Heat-pump operating mode: heating / cooling / off."""
    Heating = 0
    Cooling = 1
    Off = 2


class VavOperatingMode(enum.Enum):
    """Operating mode of a VAV terminal unit."""
    Cooling = 0
    Heating = 1
    Deadband = 2


class ZoneSetpoints:
    """Per-zone heating/cooling setpoints and deadbands."""

    def __init__(self, num_zones: int) -> None: ...
    def set_heating_setpoint(self, zone_id: int, temp: float) -> None: ...
    def set_cooling_setpoint(self, zone_id: int, temp: float) -> None: ...
    def set_deadband(self, zone_id: int, deadband: float) -> None: ...
    def get_heating_setpoint(self, zone_id: int) -> float: ...
    def get_cooling_setpoint(self, zone_id: int) -> float: ...
    def get_deadband(self, zone_id: int) -> float: ...
    def validate(self) -> None: ...
    def num_zones(self) -> int: ...


class ZoneControl:
    """Zone-level HVAC controller bound to a thermal model + setpoints."""

    def __init__(self, thermal_model: MultiZoneThermalModel, setpoints: ZoneSetpoints) -> None: ...
    def update_controls(self, temperatures: list[float]) -> list[float]: ...
    def get_zone_status(self, zone_id: int) -> str: ...
    def get_energy_input(self, zone_id: int, current_temp: float) -> float: ...


class DailySchedule:
    """24-hour daily schedule of scalar values."""

    def __init__(self, name: str, schedule_type: str) -> None: ...
    def set_hour(self, hour: int, value: float) -> None: ...
    def fill_range(self, start_hour: int, end_hour: int, value: float) -> None: ...
    def value(self, hour: int) -> float: ...
    @staticmethod
    def constant(value: float) -> DailySchedule: ...


class HVACSchedule:
    """Heating + cooling setpoint schedules for an HVAC system."""

    def __init__(self) -> None: ...
    @staticmethod
    def constant_schedule(heating_sp: float, cooling_sp: float) -> HVACSchedule: ...
    @staticmethod
    def setback_schedule(
        day_heat: float, night_heat: float, cool_sp: float, night_start: int, night_end: int
    ) -> HVACSchedule: ...
    @staticmethod
    def with_operating_hours(
        heating_sp: float, cooling_sp: float, start_hour: int, end_hour: int
    ) -> HVACSchedule: ...
    @staticmethod
    def free_floating() -> HVACSchedule: ...
    def is_free_floating(self) -> bool: ...
    def heating_setpoint(self, hour: int) -> float: ...
    def cooling_setpoint(self, hour: int) -> float: ...
    def get_heating_schedule(self) -> DailySchedule: ...
    def get_cooling_schedule(self) -> DailySchedule: ...


class Chiller:
    """Chiller equipment model (cooling-only, polynomial efficiency curves)."""

    def __init__(
        self, id: str, cooling_capacity: float, cooling_cop: float, design_temp: float
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def cooling_capacity(self) -> float: ...
    @property
    def cooling_cop(self) -> float: ...
    @property
    def design_temp(self) -> float: ...
    def calculate_capacity(self, plr: float, outdoor_temp: float) -> float: ...
    def calculate_power(self, load: float, outdoor_temp: float) -> float: ...
    @property
    def current_plr(self) -> float: ...


class Boiler:
    """Boiler equipment model (heating-only, polynomial efficiency curves)."""

    def __init__(
        self, id: str, heating_capacity: float, efficiency: float, design_temp: float
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def heating_capacity(self) -> float: ...
    @property
    def efficiency(self) -> float: ...
    @property
    def design_temp(self) -> float: ...
    def calculate_capacity(self, plr: float, outdoor_temp: float) -> float: ...
    def calculate_power(self, load: float, outdoor_temp: float) -> float: ...
    @property
    def current_plr(self) -> float: ...


class HeatPump:
    """Heat-pump system with COP curves (heating + cooling)."""

    def __init__(
        self,
        id: str,
        heating_capacity: float,
        cooling_capacity: float,
        heating_cop: float,
        cooling_cop: float,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def heating_capacity(self) -> float: ...
    @property
    def cooling_capacity(self) -> float: ...
    @property
    def heating_cop(self) -> float: ...
    @property
    def cooling_cop(self) -> float: ...
    @property
    def mode(self) -> str: ...
    def heating_cop_at_temperature(self, outdoor_temp: float) -> float: ...
    def cooling_cop_at_temperature(self, outdoor_temp: float) -> float: ...
    def heating_power(self, outdoor_temp: float) -> float: ...
    def cooling_power(self, outdoor_temp: float) -> float: ...
    def set_mode(self, zone_temp: float, heating_sp: float, cooling_sp: float) -> None: ...


class VAVTerminal:
    """VAV terminal unit (high-level model with reheat coil)."""

    def __init__(self, id: str, zone_id: int, max_airflow: float) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def zone_id(self) -> int: ...
    @property
    def max_airflow(self) -> float: ...
    @property
    def min_airflow(self) -> float: ...
    @property
    def reheat_capacity(self) -> float: ...
    def set_min_airflow(self, min_airflow: float) -> None: ...
    def set_reheat_capacity(self, reheat_capacity: float) -> None: ...
    def reheat_demand(self, supply_temp: float, zone_temp: float) -> float: ...


class CAVSystem:
    """Constant Air Volume (CAV) system."""

    def __init__(self, id: str, design_airflow: float) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def design_airflow(self) -> float: ...
    @property
    def fan_power(self) -> float: ...
    @property
    def fan_efficiency(self) -> float: ...
    @property
    def heating_capacity(self) -> float: ...
    @property
    def cooling_capacity(self) -> float: ...
    def set_fan_power(self, fan_power: float) -> None: ...
    def set_fan_efficiency(self, fan_efficiency: float) -> None: ...
    def set_heating_capacity(self, heating_capacity: float) -> None: ...
    def set_cooling_capacity(self, cooling_capacity: float) -> None: ...
    def fan_power_consumption(self) -> float: ...


class VavTerminalUnit:
    """Reference VAV terminal unit (fan, cooling coil, optional reheat)."""

    def __init__(
        self,
        id: str,
        zone_id: int,
        max_airflow: float,
        cooling_capacity: float,
        reheat_capacity: float = 0.0,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def zone_id(self) -> int: ...
    @property
    def max_airflow(self) -> float: ...
    @property
    def min_airflow(self) -> float: ...
    @property
    def min_airflow_ratio(self) -> float: ...
    def set_min_airflow_ratio(self, ratio: float) -> None: ...
    @property
    def rated_cooling_capacity(self) -> float: ...
    @property
    def rated_reheat_capacity(self) -> float: ...
    @property
    def has_reheat(self) -> bool: ...
    @property
    def current_damper_position(self) -> float: ...


class VavTerminalControl:
    """Control signal for a :class:`VavTerminalUnit`.

    Encapsulates damper position and coil on/off states.
    """

    def __init__(
        self, damper_position: float, cooling_active: bool = False, reheat_setpoint: float | None = None
    ) -> None: ...
    @staticmethod
    def cooling(damper_position: float) -> VavTerminalControl: ...
    @staticmethod
    def heating(supply_setpoint_c: float) -> VavTerminalControl: ...
    @staticmethod
    def deadband() -> VavTerminalControl: ...
    @property
    def damper_position(self) -> float: ...
    @property
    def cooling_active(self) -> bool: ...
    @property
    def mode(self) -> VavOperatingMode: ...
    def __repr__(self) -> str: ...


class VavTerminalPerformance:
    """Performance result of a VAV terminal calculation (read-only).

    Constructed by :func:`compute_vav_terminal_performance`; not directly
    instantiable from Python.
    """

    @property
    def mode(self) -> VavOperatingMode: ...
    @property
    def damper_position(self) -> float: ...
    @property
    def fan_speed_fraction(self) -> float: ...
    @property
    def volumetric_flow_m3_per_s(self) -> float: ...
    @property
    def dry_air_mass_flow_kg_per_s(self) -> float: ...
    @property
    def cooling_total_capacity_w(self) -> float: ...
    @property
    def cooling_sensible_capacity_w(self) -> float: ...
    @property
    def cooling_latent_capacity_w(self) -> float: ...
    @property
    def cooling_shr(self) -> float: ...
    @property
    def reheat_capacity_w(self) -> float: ...
    @property
    def fan_shaft_power_w(self) -> float: ...
    @property
    def fan_motor_power_w(self) -> float: ...
    @property
    def fan_heat_w(self) -> float: ...
    @property
    def condensate_rate_kg_per_s(self) -> float: ...
    @property
    def supply_dry_bulb_c(self) -> float: ...


# ---------------------------------------------------------------------------
# 9R4C multi-node solver bindings (src/python/multi_node_bindings.rs)
# ---------------------------------------------------------------------------

class MassAirCouplingMode(enum.Enum):
    """How the multi-node mass network couples to the zone air node."""
    AdditiveSum = 0
    ParallelResistance = 1

    def __repr__(self) -> str: ...


class ThermalMassNode:
    """A single thermal-mass node (temperature, capacitance, conductances)."""

    def __init__(
        self,
        temperature: float,
        capacitance: float,
        h_tr_ms: float,
        h_tr_em: float,
        h_tr_me: float,
    ) -> None: ...
    @property
    def temperature(self) -> float: ...
    @temperature.setter
    def temperature(self, value: float) -> None: ...
    @property
    def capacitance(self) -> float: ...
    @capacitance.setter
    def capacitance(self, value: float) -> None: ...
    @property
    def h_tr_ms(self) -> float: ...
    @h_tr_ms.setter
    def h_tr_ms(self, value: float) -> None: ...
    @property
    def h_tr_em(self) -> float: ...
    @h_tr_em.setter
    def h_tr_em(self, value: float) -> None: ...
    @property
    def h_tr_me(self) -> float: ...
    @h_tr_me.setter
    def h_tr_me(self, value: float) -> None: ...
    @property
    def heat_flux_cumulative(self) -> float: ...


class MultiNodeThermalMass:
    """Per-surface-type collection of :class:`ThermalMassNode` (wall/roof/floor/internal)."""

    def __init__(
        self, wall: ThermalMassNode, roof: ThermalMassNode, floor: ThermalMassNode, internal: ThermalMassNode
    ) -> None: ...
    @property
    def wall(self) -> ThermalMassNode: ...
    @wall.setter
    def wall(self, value: ThermalMassNode) -> None: ...
    @property
    def roof(self) -> ThermalMassNode: ...
    @roof.setter
    def roof(self, value: ThermalMassNode) -> None: ...
    @property
    def floor(self) -> ThermalMassNode: ...
    @floor.setter
    def floor(self, value: ThermalMassNode) -> None: ...
    @property
    def internal(self) -> ThermalMassNode: ...
    @internal.setter
    def internal(self, value: ThermalMassNode) -> None: ...


class SurfaceExteriorTemperatures:
    """Exterior surface temperatures for the three opaque surface types."""

    def __init__(self, t_ext_wall: float, t_ext_roof: float, t_ext_floor: float) -> None: ...
    @property
    def t_ext_wall(self) -> float: ...
    @t_ext_wall.setter
    def t_ext_wall(self, value: float) -> None: ...
    @property
    def t_ext_roof(self) -> float: ...
    @t_ext_roof.setter
    def t_ext_roof(self, value: float) -> None: ...
    @property
    def t_ext_floor(self) -> float: ...
    @t_ext_floor.setter
    def t_ext_floor(self, value: float) -> None: ...


class MultiNodeSolver:
    """9R4C multi-node zone solver (ISO 13790-style thermal network)."""

    def __init__(
        self,
        h_tr_is: float,
        wall: ThermalMassNode,
        roof: ThermalMassNode,
        floor: ThermalMassNode,
        internal: ThermalMassNode,
    ) -> None: ...
    @property
    def mass(self) -> MultiNodeThermalMass: ...
    @mass.setter
    def mass(self, value: MultiNodeThermalMass) -> None: ...
    @property
    def h_tr_is(self) -> float: ...
    @h_tr_is.setter
    def h_tr_is(self, value: float) -> None: ...
    @property
    def zone_temperature(self) -> float: ...
    @zone_temperature.setter
    def zone_temperature(self, value: float) -> None: ...
    @property
    def surface_temperature(self) -> float: ...
    @surface_temperature.setter
    def surface_temperature(self, value: float) -> None: ...
    @property
    def exterior_temperature(self) -> float: ...
    @exterior_temperature.setter
    def exterior_temperature(self, value: float) -> None: ...
    @property
    def exterior_temperatures(self) -> SurfaceExteriorTemperatures: ...
    @exterior_temperatures.setter
    def exterior_temperatures(self, value: SurfaceExteriorTemperatures) -> None: ...
    @property
    def timestep_seconds(self) -> float: ...
    @timestep_seconds.setter
    def timestep_seconds(self, value: float) -> None: ...
    @property
    def coupling_mode(self) -> MassAirCouplingMode: ...
    @coupling_mode.setter
    def coupling_mode(self, value: MassAirCouplingMode) -> None: ...
    @property
    def r_total(self) -> float: ...
    @r_total.setter
    def r_total(self, value: float) -> None: ...
    @property
    def r_se(self) -> float: ...
    @r_se.setter
    def r_se(self, value: float) -> None: ...
    @property
    def initialized(self) -> bool: ...
    @initialized.setter
    def initialized(self, value: bool) -> None: ...
    @property
    def last_dt(self) -> float: ...
    @last_dt.setter
    def last_dt(self, value: float) -> None: ...
    def wall_temperature(self) -> float: ...
    def roof_temperature(self) -> float: ...
    def floor_temperature(self) -> float: ...
    def internal_temperature(self) -> float: ...
    def set_wall_conductances(self, h_tr_em: float, h_tr_ms: float) -> None: ...
    def set_roof_conductances(self, h_tr_em: float, h_tr_ms: float) -> None: ...
    def set_floor_conductances(self, h_tr_em: float, h_tr_ms: float) -> None: ...
    def set_internal_conductance(self, h_tr_me: float) -> None: ...
    def set_wall_capacitance(self, cm: float) -> None: ...
    def set_roof_capacitance(self, cm: float) -> None: ...
    def set_floor_capacitance(self, cm: float) -> None: ...
    def set_internal_capacitance(self, cm: float) -> None: ...
    def initialize_temperatures(self, t_initial: float) -> None: ...
    def step(self, dt: float) -> None: ...
    def effective_time_constant(self) -> float: ...


# ---------------------------------------------------------------------------
# FluxionModel interior bindings — Issue #1812 (src/python/model_bindings.rs)
# ---------------------------------------------------------------------------

class Orientation(enum.Enum):
    """Compass orientation of a surface (mirrors ``ashrae_cases::Orientation``)."""
    North = 0
    East = 90
    South = 180
    West = 270
    Up = -1
    Down = -2
    Horizontal = -3

    @property
    def prefix(self) -> str: ...
    @property
    def azimuth_deg(self) -> float: ...
    def __repr__(self) -> str: ...


class ShadingType(enum.Enum):
    """Shading device classification.

    Note: the Rust ``None`` variant is exposed as ``none_`` because ``None`` is
    a Python keyword (PyO3 appends ``_`` to keyword-colliding enum variants).
    """
    none_ = 0  # type: ignore[assignment]  # Rust variant `None`
    Overhang = 1
    Fins = 2
    OverhangAndFins = 3


class ShadingDevice:
    """Shading device attached to a surface (overhang, fins, or both)."""

    def __init__(self) -> None: ...
    @staticmethod
    def none() -> ShadingDevice: ...
    @staticmethod
    def overhang(depth: float, height: float) -> ShadingDevice: ...
    @staticmethod
    def fins(width: float) -> ShadingDevice: ...
    @staticmethod
    def overhang_and_fins(overhang_depth: float, fin_width: float, height: float) -> ShadingDevice: ...
    def __repr__(self) -> str: ...


class Material:
    """Single material layer in a construction assembly (Python-side ``ConstructionLayer``)."""

    def __init__(
        self, name: str, conductivity: float, density: float, specific_heat: float, thickness: float
    ) -> None: ...
    def r_value(self) -> float: ...
    def thermal_capacitance_per_area(self) -> float: ...
    def __repr__(self) -> str: ...


class Surface:
    """Building surface (opaque wall, window, roof, or floor).

    Surfaces are organised per zone in the underlying thermal model.
    """

    def __init__(self, area: float, u_value: float, orientation: Orientation, window_area: float = 0.0) -> None: ...
    def append_shading(self, device: ShadingDevice) -> None: ...
    def add_overhang(self, depth: float, height: float) -> None: ...
    def add_fins(self, width: float) -> None: ...
    def total_area(self) -> float: ...
    def __repr__(self) -> str: ...


class Zone:
    """Single thermal zone (runtime snapshot from the parent model)."""

    def __init__(
        self,
        index: int,
        temperature: float,
        area: float,
        heating_setpoint: float = 20.0,
        cooling_setpoint: float = 24.0,
        hvac_enabled: bool = True,
        surfaces: list[Surface] = [],
    ) -> None: ...
    def surface_count(self) -> int: ...
    def total_surface_area(self) -> float: ...
    def surfaces_with_orientation(self, orientation: Orientation) -> list[Surface]: ...
    def __repr__(self) -> str: ...


class HVACSystem:
    """HVAC system configuration snapshot (validation-layer HVAC type)."""

    def __init__(
        self,
        heating_capacity: float,
        cooling_capacity: float,
        cop_heating: float,
        cop_cooling: float,
        stages: int,
        min_outdoor_temp: float,
        max_outdoor_temp: float,
        vav_enabled: bool,
        economizer_enabled: bool,
        supply_air_temp: float,
    ) -> None: ...
    def heating_electrical_input(self) -> float: ...
    def cooling_electrical_input(self) -> float: ...
    def can_operate_at(self, outdoor_temp: float) -> bool: ...
    def __repr__(self) -> str: ...
