import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { toRenderModel, zoneColor } from "../src/lib/geometryAdapter";
import { sampleGeometry } from "../src/lib/sampleGeometry";
import { triangulatePolygon } from "../src/lib/triangulate";
import type { BuildingGeometry } from "../src/types/geometry";

const fixturePath = fileURLToPath(
  new URL("./fixtures/rust-sample-geometry.json", import.meta.url),
);
/** Generated by `cargo run --example dump_sample -p fluxion-tauri`. */
const rustSample = JSON.parse(
  readFileSync(fixturePath, "utf8"),
) as BuildingGeometry;

describe("Rust geometry JSON contract (load_geometry)", () => {
  it("fixture parses and matches the shape the R3F scene dereferences", () => {
    expect(rustSample.id).toBe("building-1");
    expect(rustSample.levels.length).toBe(2);
    expect(rustSample.zones.length).toBe(3);
    for (const level of rustSample.levels) {
      for (const space of level.spaces) {
        expect(space.surfaces.length).toBeGreaterThan(0);
        for (const surface of space.surfaces) {
          expect(surface.vertices.length).toBeGreaterThanOrEqual(3);
          for (const v of surface.vertices) {
            expect(typeof v.x).toBe("number");
            expect(typeof v.y).toBe("number");
            expect(typeof v.z).toBe("number");
          }
        }
      }
    }
  });

  it("embedded web fallback stays in sync with the Rust sample", () => {
    expect(sampleGeometry.name).toBe(rustSample.name);
    expect(sampleGeometry.levels.length).toBe(rustSample.levels.length);
    expect(sampleGeometry.zones.map((z) => z.id)).toEqual(
      rustSample.zones.map((z) => z.id),
    );
    const spaces = (g: BuildingGeometry) =>
      g.levels.flatMap((l) => l.spaces.map((s) => s.id));
    expect(spaces(sampleGeometry)).toEqual(spaces(rustSample));
  });
});

describe("toRenderModel", () => {
  const model = toRenderModel(rustSample);

  it("triangulates every surface of the sample building", () => {
    // 3 spaces x 6 surfaces, each a rectangle (2 triangles, 18 floats).
    expect(model.surfaces.length).toBe(18);
    for (const surface of model.surfaces) {
      expect(surface.triangleCount).toBe(2);
      expect(surface.positions.length).toBe(2 * 9);
    }
  });

  it("converts Z-up geometry to Y-up bounds", () => {
    // Building spans z in [0, 6] (BEM Z-up) -> y in [0, 6] (three.js Y-up).
    expect(model.bounds.min[0]).toBeCloseTo(0);
    expect(model.bounds.max[0]).toBeCloseTo(14);
    expect(model.bounds.max[1]).toBeCloseTo(6);
    expect(model.bounds.max[2]).toBeCloseTo(6);
  });

  it("computes summary stats mirroring the Rust compute_geometry_summary", () => {
    expect(model.stats.levelCount).toBe(2);
    expect(model.stats.spaceCount).toBe(3);
    expect(model.stats.zoneCount).toBe(3);
    expect(model.stats.totalFloorArea).toBeCloseTo(132.0);
  });

  it("assigns every surface to its owning thermal zone", () => {
    for (const surface of model.surfaces) {
      expect(surface.zoneId).toBeTruthy();
    }
    const zone1 = model.surfaces.filter((s) => s.zoneId === "zone-1");
    expect(zone1.length).toBe(6);
    expect(zone1.every((s) => s.spaceId === "space-1")).toBe(true);
  });

  it("produces identical render models for fixture and embedded sample", () => {
    const fromSample = toRenderModel(sampleGeometry);
    expect(fromSample.surfaces.length).toBe(model.surfaces.length);
    expect(fromSample.stats).toEqual(model.stats);
    expect(fromSample.bounds).toEqual(model.bounds);
  });
});

describe("zoneColor", () => {
  it("is deterministic and within the preserved palette", () => {
    const first = zoneColor("zone-1");
    expect(zoneColor("zone-1")).toBe(first);
    expect(zoneColor("zone-2")).not.toBe(first);
  });
});

describe("triangulatePolygon", () => {
  it("returns two triangles for a rectangle", () => {
    const positions = triangulatePolygon(
      [
        { x: 0, y: 0, z: 0 },
        { x: 4, y: 0, z: 0 },
        { x: 4, y: 3, z: 0 },
        { x: 0, y: 3, z: 0 },
      ],
      { x: 0, y: 0, z: 1 },
    );
    expect(positions).not.toBeNull();
    expect(positions!.length).toBe(2 * 9);
  });

  it("returns null for degenerate polygons", () => {
    expect(
      triangulatePolygon(
        [
          { x: 0, y: 0, z: 0 },
          { x: 1, y: 1, z: 1 },
        ],
        { x: 0, y: 1, z: 0 },
      ),
    ).toBeNull();
    expect(
      triangulatePolygon(
        [
          { x: 0, y: 0, z: 0 },
          { x: 1, y: 0, z: 0 },
          { x: 2, y: 0, z: 0 },
        ],
        { x: 0, y: 0, z: 0 },
      ),
    ).toBeNull();
  });

  it("triangulates a vertical wall (non-XY plane)", () => {
    const positions = triangulatePolygon(
      [
        { x: 0, y: 0, z: 0 },
        { x: 0, y: 0, z: 3 },
        { x: 8, y: 0, z: 3 },
        { x: 8, y: 0, z: 0 },
      ],
      { x: 0, y: -1, z: 0 },
    );
    expect(positions).not.toBeNull();
    expect(positions!.length).toBe(2 * 9);
  });
});
