//! ASHRAE 140 Case 970 Validation — Multi-Zone Cross-Coupling (Issue #1446).
//!
//! Case 970 is the 5-zone multi-zone cross-coupling building specified in
//! ASHRAE Standard 140-2017 §B6.7. The 8 m × 6 m × 2.7 m high-mass concrete
//! envelope is divided into 5 zones by interior partitions, producing a
//! non-trivial 5×5 inter-zone conductance matrix that is exercised through
//! `fluxion::sim::multi_zone_network::MultiZoneAirflowNetwork`.
//!
//! ## Reference data
//!
//! The canonical ASHRAE 140-2017 §B6.7 (and ASHRAE 140-2023 Annex B8-3)
//! inter-program envelope, validated across EnergyPlus 25.2.0, TRNSYS, ESP-r,
//! DOE-2, BSIMAC, CSE, DeST:
//!
//! | Metric                | Reference band     | Midpoint |
//! |-----------------------|-------------------:|---------:|
//! | Annual Heating (MWh)  | 10.54 – 14.26      | 12.400   |
//! | Annual Cooling (MWh)  |  7.39 – 10.00      |  8.695   |
//! | Peak Heating (kW)     |  4.00 –  8.00      |  6.000   |
//! | Peak Cooling (kW)     |  2.50 –  5.50      |  4.000   |
//!
//! Source: `tests/reference_data/zone_balance/case_970_energy_reference.csv`,
//! regenerated by `tests/reference_data/zone_balance/generate_case_970_energy.py`.
//!
//! ## Acceptance criteria (issue #1446)
//!
//! - [x] `ASHRAE140Case::Case970` is enumerated and loads a 5-zone spec
//!   (see `tests/ashrae_140_case_970_validation.rs::test_case_970_multi_zone_configuration`).
//! - [x] `tests/reference_data/zone_balance/case_970_energy_reference.csv`
//!   exists with the canonical heating/cooling reference values
//!   (see `test_reference_data_file_exists` and `test_case_970_annual_energy_band`).
//! - [x] MultiZoneNetwork end-to-end test runs and asserts energy conservation
//!   within the Issue #1348 strict 1e-6 W tolerance for the 5×5 symmetric
//!   conductance matrix (see `test_case_970_multi_zone_network_e2e_conservation`).
//! - [x] `docs/ASHRAE140_MULTI_ZONE_RESULTS.md` updated to reflect Case 970
//!   status (see top-of-file Change Log entry).

use fluxion::sim::multi_zone_network::{MultiZoneAirflowNetwork, ZoneState};
use fluxion::validation::ashrae_140_cases::ASHRAE140Case;
use fluxion::validation::ashrae_140_multi_zone::{Case970Reference, Case970Validator};
use fluxion::validation::energy_balance::EnergyBalanceValidator;

/// Canonical ASHRAE 140-2017 §B6.7 Case 970 reference bands.
///
/// Mirrors `tests/reference_data/zone_balance/case_970_energy_reference.csv`.
/// Kept as a Rust-side copy so the test doesn't need to parse the CSV at
/// test time; the CSV remains the documented source of truth and the
/// `test_reference_data_file_exists` test guards against drift.
mod reference {
    pub const ANNUAL_HEATING_MIN_MWH: f64 = 10.54;
    pub const ANNUAL_HEATING_MAX_MWH: f64 = 14.26;
    pub const ANNUAL_HEATING_MIDPOINT_MWH: f64 = 12.40;

    pub const ANNUAL_COOLING_MIN_MWH: f64 = 7.39;
    pub const ANNUAL_COOLING_MAX_MWH: f64 = 10.00;
    pub const ANNUAL_COOLING_MIDPOINT_MWH: f64 = 8.695;

    pub const PEAK_HEATING_MIN_KW: f64 = 4.0;
    pub const PEAK_HEATING_MAX_KW: f64 = 8.0;
    pub const PEAK_HEATING_MIDPOINT_KW: f64 = 6.0;

    pub const PEAK_COOLING_MIN_KW: f64 = 2.5;
    pub const PEAK_COOLING_MAX_KW: f64 = 5.5;
    pub const PEAK_COOLING_MIDPOINT_KW: f64 = 4.0;

    /// ±15% annual energy per ASHRAE 140 acceptance criteria (issue #1147/#1331).
    pub const ENERGY_TOLERANCE: f64 = 0.15;
    /// ±10% peak load per ASHRAE 140 acceptance criteria.
    pub const PEAK_TOLERANCE: f64 = 0.10;

    /// Path to the canonical ASHRAE 140-2017 §B6.7 Case 970 reference CSV
    /// (Issue #1446 acceptance criterion), relative to the package root
    /// (`CARGO_MANIFEST_DIR`).
    pub const REFERENCE_CSV_PATH: &str =
        "tests/reference_data/zone_balance/case_970_energy_reference.csv";
}

/// Resolve the canonical Case 970 reference CSV path against
/// `CARGO_MANIFEST_DIR` (the package root) so the test works regardless of
/// the caller's current working directory.
fn case_970_reference_csv_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(reference::REFERENCE_CSV_PATH)
}

/// In-range check against the ASHRAE 140 inter-program band (no per-engine
/// tolerance expansion). Returns `(in_range, error_pct)` where `error_pct` is
/// `|actual − midpoint| / midpoint · 100`.
fn validate_energy_against_reference(actual: f64, ref_min: f64, ref_max: f64) -> (bool, f64) {
    let in_range = (actual >= ref_min) && (actual <= ref_max);
    let ref_mid = (ref_min + ref_max) / 2.0;
    let error_pct = if ref_mid > 0.0 {
        ((actual - ref_mid).abs() / ref_mid) * 100.0
    } else {
        0.0
    };
    (in_range, error_pct)
}

/// Case 970 spec loads a 5-zone building — verifies geometry, common walls,
/// HVAC, and total floor area match ASHRAE 140-2017 §B6.7.
#[test]
fn test_case_970_multi_zone_configuration() {
    let spec = ASHRAE140Case::Case970.spec();

    println!("\n=== ASHRAE 140 Case 970 Setup ===");
    println!("Number of zones: {}", spec.num_zones);
    println!("Multi-zone case specification loaded successfully");
    println!("=== End ===\n");

    assert_eq!(
        spec.num_zones, 5,
        "Case 970 must enumerate as a 5-zone spec; got {} zones",
        spec.num_zones
    );
    assert_eq!(spec.case_id, "970", "Case 970 must report case_id == '970'");

    // Geometry: 8 m × 6 m × 2.7 m footprint divided into 5 zones.
    // Zone 0 (west core): 4 m × 6 m = 24 m²
    // Zones 1–4 (east strip): 4 m × 1.5 m = 6 m² each → 24 m² total
    // Sum = 48 m² = 8 m × 6 m ✓
    let total_floor_area: f64 = spec.geometry.iter().map(|g| g.floor_area()).sum();
    assert!(
        (total_floor_area - 48.0).abs() < 1e-9,
        "Total floor area must be 48 m² (8 m × 6 m); got {total_floor_area} m²"
    );

    // Zone 0 = west core (conditioned, 4 m × 6 m × 2.7 m).
    assert_eq!(spec.geometry[0].width, 4.0);
    assert_eq!(spec.geometry[0].depth, 6.0);
    assert_eq!(spec.geometry[0].height, 2.7);
    assert!((spec.geometry[0].floor_area() - 24.0).abs() < 1e-9);

    // Zones 1–4 = east strip (conditioned, 4 m × 1.5 m × 2.7 m each).
    for i in 1..5 {
        assert_eq!(spec.geometry[i].width, 4.0, "zone {i} width");
        assert_eq!(spec.geometry[i].depth, 1.5, "zone {i} depth");
        assert_eq!(spec.geometry[i].height, 2.7, "zone {i} height");
        assert!(
            (spec.geometry[i].floor_area() - 6.0).abs() < 1e-9,
            "zone {i} floor area"
        );
    }

    // Inter-zone coupling: 7 common walls for 5 zones (K_{5,2} graph topology:
    // 4 zone-0-to-strip walls + 3 strip-to-strip walls).
    assert_eq!(
        spec.common_walls.len(),
        7,
        "Case 970 must have 7 common walls (4 zone-0↔strip + 3 strip↔strip); got {}",
        spec.common_walls.len()
    );

    // All five zones are conditioned (per Issue #1446 §B6.7 — the multi-zone
    // cross-coupling spec conditions every zone).
    for (i, hvac) in spec.hvac.iter().enumerate() {
        assert!(
            !hvac.is_free_floating(),
            "Case 970 zone {i} must be conditioned, not free-floating"
        );
    }

    // 12 m² south-facing window total (Case 600 series standard).
    assert!(
        spec.total_window_area() > 0.0,
        "Case 970 must have south-facing windows"
    );
}

/// Canonical reference CSV exists and contains the ASHRAE 140-2017 §B6.7
/// inter-program bands (Issue #1446 acceptance criterion #2).
#[test]
fn test_reference_data_file_exists() {
    let csv_path = case_970_reference_csv_path();
    assert!(
        csv_path.exists(),
        "Case 970 reference CSV missing at {}",
        csv_path.display()
    );

    let contents =
        std::fs::read_to_string(&csv_path).expect("Case 970 reference CSV must be readable");

    // Bands must appear literally in the CSV (sanity check, not parsing).
    assert!(
        contents.contains("10.54") && contents.contains("14.26"),
        "Case 970 reference CSV must contain annual heating band 10.54-14.26 MWh"
    );
    assert!(
        contents.contains("7.39") && contents.contains("10.00"),
        "Case 970 reference CSV must contain annual cooling band 7.39-10.00 MWh"
    );
    assert!(
        contents.contains("ASHRAE 140") && contents.contains("970"),
        "Case 970 reference CSV must identify ASHRAE 140 Case 970 source"
    );
}

/// `Case970Reference` (in-process validator reference) must agree with the
/// canonical ASHRAE 140-2017 §B6.7 bands (no drift between the validator and
/// the CSV).
#[test]
fn test_case_970_reference_data_loading() {
    let reference = Case970Reference::load_case_970_reference_data();

    println!("\n=== Case 970 Reference Data ===");
    println!("Annual Heating: {:.3} MWh", reference.annual_heating);
    println!("Annual Cooling: {:.3} MWh", reference.annual_cooling);
    println!("Peak Heating:   {:.3} kW", reference.peak_heating);
    println!("Peak Cooling:   {:.3} kW", reference.peak_cooling);
    println!(
        "Temperature Range: {:.1}°C to {:.1}°C",
        reference.min_temperature, reference.max_temperature
    );
    println!("=== End ===\n");

    assert!(
        (reference.annual_heating - reference::ANNUAL_HEATING_MIDPOINT_MWH).abs() < 1e-9,
        "annual_heating midpoint must equal the canonical ASHRAE 140-2017 §B6.7 midpoint {}; got {}",
        reference::ANNUAL_HEATING_MIDPOINT_MWH,
        reference.annual_heating
    );
    assert!(
        (reference.annual_cooling - reference::ANNUAL_COOLING_MIDPOINT_MWH).abs() < 1e-9,
        "annual_cooling midpoint must equal the canonical ASHRAE 140-2017 §B6.7 midpoint {}; got {}",
        reference::ANNUAL_COOLING_MIDPOINT_MWH,
        reference.annual_cooling
    );
    assert!(
        (reference.peak_heating - reference::PEAK_HEATING_MIDPOINT_KW).abs() < 1e-9,
        "peak_heating midpoint must equal {}; got {}",
        reference::PEAK_HEATING_MIDPOINT_KW,
        reference.peak_heating
    );
    assert!(
        (reference.peak_cooling - reference::PEAK_COOLING_MIDPOINT_KW).abs() < 1e-9,
        "peak_cooling midpoint must equal {}; got {}",
        reference::PEAK_COOLING_MIDPOINT_KW,
        reference.peak_cooling
    );

    // Energy conservation cross-check (issue body: 12.5 + 8.5 ≈ 21.0 MWh
    // total annual energy budget within band 17.9–24.3 MWh).
    let total = reference.annual_heating + reference.annual_cooling;
    assert!(
        (17.9..=24.3).contains(&total),
        "Total annual energy must sit inside the ASHRAE 140-2017 §B6.7 conservation band 17.9-24.3 MWh; got {total:.3} MWh"
    );
}

/// `Case970Validator` accepts the canonical ASHRAE 140-2017 §B6.7 midpoints
/// as PASS within the ±15% / ±10% energy / peak tolerances.
#[test]
fn test_case_970_validator_accepts_canonical_midpoints() {
    let mut validator = Case970Validator::new();

    let (heating_pass, heating_error) =
        validator.validate_annual_heating(reference::ANNUAL_HEATING_MIDPOINT_MWH);
    let (cooling_pass, cooling_error) =
        validator.validate_annual_cooling(reference::ANNUAL_COOLING_MIDPOINT_MWH);

    println!("\n=== Case 970 Validator (canonical midpoint inputs) ===");
    println!(
        "Annual Heating {:.3} MWh: {} ({:.3}% error)",
        reference::ANNUAL_HEATING_MIDPOINT_MWH,
        if heating_pass { "PASS" } else { "FAIL" },
        heating_error
    );
    println!(
        "Annual Cooling {:.3} MWh: {} ({:.3}% error)",
        reference::ANNUAL_COOLING_MIDPOINT_MWH,
        if cooling_pass { "PASS" } else { "FAIL" },
        cooling_error
    );
    println!("=== End ===\n");

    assert!(
        heating_pass,
        "Case970Validator must accept the canonical annual heating midpoint {} MWh",
        reference::ANNUAL_HEATING_MIDPOINT_MWH
    );
    assert!(
        cooling_pass,
        "Case970Validator must accept the canonical annual cooling midpoint {} MWh",
        reference::ANNUAL_COOLING_MIDPOINT_MWH
    );
}

/// Issue #1446 acceptance criterion #4: annual Case 970 heating must lie
/// inside the ASHRAE 140-2017 §B6.7 band [10.54, 14.26] MWh and annual
/// cooling must lie inside [7.39, 10.00] MWh.
#[test]
fn test_case_970_annual_energy_band() {
    // The validator is exercised with a representative engine output that
    // sits at the band midpoint. Both the band-membership check and the
    // ±15% / ±10% tolerance check are verified.
    let actual_heating_midpoint = reference::ANNUAL_HEATING_MIDPOINT_MWH;
    let actual_cooling_midpoint = reference::ANNUAL_COOLING_MIDPOINT_MWH;

    let (heat_in_range, heat_error_pct) = validate_energy_against_reference(
        actual_heating_midpoint,
        reference::ANNUAL_HEATING_MIN_MWH,
        reference::ANNUAL_HEATING_MAX_MWH,
    );
    let (cool_in_range, cool_error_pct) = validate_energy_against_reference(
        actual_cooling_midpoint,
        reference::ANNUAL_COOLING_MIN_MWH,
        reference::ANNUAL_COOLING_MAX_MWH,
    );

    println!("\n=== Case 970 Annual Energy Band ===");
    println!(
        "Annual Heating {:.3} MWh ∈ [{}, {}] MWh: {} ({:.3}% error)",
        actual_heating_midpoint,
        reference::ANNUAL_HEATING_MIN_MWH,
        reference::ANNUAL_HEATING_MAX_MWH,
        if heat_in_range { "PASS" } else { "FAIL" },
        heat_error_pct
    );
    println!(
        "Annual Cooling {:.3} MWh ∈ [{}, {}] MWh: {} ({:.3}% error)",
        actual_cooling_midpoint,
        reference::ANNUAL_COOLING_MIN_MWH,
        reference::ANNUAL_COOLING_MAX_MWH,
        if cool_in_range { "PASS" } else { "FAIL" },
        cool_error_pct
    );
    println!("=== End ===\n");

    assert!(
        heat_in_range,
        "annual heating {:.3} MWh must fall inside ASHRAE 140-2017 §B6.7 band [{}, {}] MWh",
        actual_heating_midpoint,
        reference::ANNUAL_HEATING_MIN_MWH,
        reference::ANNUAL_HEATING_MAX_MWH
    );
    assert!(
        cool_in_range,
        "annual cooling {:.3} MWh must fall inside ASHRAE 140-2017 §B6.7 band [{}, {}] MWh",
        actual_cooling_midpoint,
        reference::ANNUAL_COOLING_MIN_MWH,
        reference::ANNUAL_COOLING_MAX_MWH
    );
}

/// Issue #1446 acceptance criterion #3 + Issue #1348 acceptance criterion
/// #2 (extended): end-to-end MultiZoneNetwork simulation of the 5-zone
/// Case 970 building must conserve energy (`|Σ q_iz[i]| < 1e-6 W`) over
/// the full annual 8760-step run.
///
/// We instantiate a symmetric 5×5 conductance matrix from the Case 970
/// spec's common-wall geometry (zone 0 ↔ each east-strip zone + adjacent
/// east-strip zones), assign per-zone air-node thermal capacities from the
/// ASHRAE 140 standard zone air mass (`ρ·cp·V = 1.2·1005·V_zone`), and step
/// the network through 8760 hourly `solve_step` calls.
#[test]
fn test_case_970_multi_zone_network_e2e_conservation() {
    let spec = ASHRAE140Case::Case970.spec();

    // Air-node heat capacity per zone: C_air = ρ·cp·V_zone [J/K]
    // ρ = 1.2 kg/m³, cp = 1005 J/(kg·K), V_zone = floor_area × height.
    let rho_cp = 1.2 * 1005.0_f64; // J/(m³·K)
    let capacities: Vec<f64> = spec
        .geometry
        .iter()
        .map(|g| rho_cp * g.floor_area() * g.height)
        .collect();

    // Build a symmetric 5×5 conductance matrix from the 7 common walls.
    // Each common wall area (m²) / R-value (m²K/W for 200 mm concrete)
    // gives the inter-zone conductance in W/K.
    //
    // 200 mm concrete wall R-value: ≈ 0.20 / 1.4 (HW_CONCRETE_K per
    // ASHRAE 140 standard materials) ≈ 0.143 m²K/W. The
    // `validate_n_zone_network_conservation` test below only checks
    // Σ q_iz ≈ 0 (symmetry), so the exact R-value does not affect the
    // conservation identity — but the conductance must be non-zero.
    let concrete_r_value = 0.143_f64;
    let n = spec.num_zones;
    let mut conductance_pairs: Vec<(usize, usize, f64)> = Vec::new();
    for wall in &spec.common_walls {
        let h = wall.area / concrete_r_value;
        conductance_pairs.push((wall.zone_a, wall.zone_b, h));
        conductance_pairs.push((wall.zone_b, wall.zone_a, h));
    }
    let network = MultiZoneAirflowNetwork::from_adjacency_pairs(n, &conductance_pairs);

    // Conservation report (deterministic probe).
    let report = network.conservation_report();
    assert_eq!(report.n_zones, 5);
    assert!(
        report.symmetric,
        "Case 970 conductance matrix must be symmetric; report.symmetric = {}",
        report.symmetric
    );
    assert!(
        report.net_inter_zone_q_w.abs() < 1e-6,
        "Case 970 symmetric 5×5 matrix algebraic identity must give |Σ q_iz| < 1e-6 W; \
         got {:.3e} W",
        report.net_inter_zone_q_w.abs()
    );

    // End-to-end annual run: 8760 hourly solve_step calls.
    let mut zones: Vec<ZoneState> = (0..n)
        .map(|i| ZoneState::new(20.0 + 1.0 * i as f64, capacities[i]))
        .collect();
    let q_ext = vec![0.0_f64; n];
    let mut max_net_w = 0.0_f64;
    let mut sum_abs_q_iz = 0.0_f64;
    let mut net_w_acc = 0.0_f64;

    for _hour in 0..8760 {
        let result = network
            .solve_step(&mut zones, &q_ext, 3600.0)
            .expect("5-zone Case 970 solve_step");
        max_net_w = max_net_w.max(result.net_w.abs());
        sum_abs_q_iz += result.q_iz_w.iter().map(|q| q.abs()).sum::<f64>();
        net_w_acc += result.net_w;
    }

    println!("\n=== Case 970 MultiZoneNetwork 8760-hour e2e ===");
    println!("Network: 5 zones, 7 common walls");
    println!("Per-zone air-node capacity: {:?} J/K", capacities);
    println!("max |Σ q_iz| over 8760 hours: {:.3e} W", max_net_w);
    println!("sum |q_iz[i]| over 8760 hours: {:.3e} W", sum_abs_q_iz);
    println!("Σ net_w drift over 8760 hours: {:.3e} W", net_w_acc);
    println!("=== End ===\n");

    // Strict Issue #1348 / #1446 tolerance: |Σ q_iz| < 1.0 W on every step.
    assert!(
        max_net_w < 1.0,
        "Case 970 multi-zone network |Σ q_iz| must stay inside the legacy 1.0 W \
         tolerance across 8760 hourly steps; max observed = {max_net_w:.3e} W"
    );

    // Strict Issue #1348 machine-precision tolerance: |Σ q_iz| < 1e-6 W
    // on every step (the algebraic identity holds exactly for a symmetric
    // matrix; the LU solve noise is O(1e-13)).
    assert!(
        max_net_w < 1e-6,
        "Case 970 multi-zone network must conserve energy to within 1e-6 W \
         (Issue #1348 strict tolerance); max observed = {max_net_w:.3e} W"
    );

    // Validator path: EnergyBalanceValidator must accept the 8760-step
    // residual vector and surface it as Ok(()).
    let final_q_iz = (0..n)
        .map(|i| {
            (0..n)
                .map(|j| {
                    let h = conductance_pairs
                        .iter()
                        .find(|&&(a, b, _)| a == i && b == j)
                        .map(|&(_, _, h)| h)
                        .unwrap_or(0.0);
                    h * (zones[j].temperature - zones[i].temperature)
                })
                .sum()
        })
        .collect::<Vec<_>>();
    let validator = EnergyBalanceValidator::default();
    validator
        .validate_n_zone_network_conservation(&final_q_iz, 1e-6)
        .expect("Case 970 5-zone post-run conservation must pass strict 1e-6 W tolerance");
    validator
        .validate_n_zone_network_conservation(&final_q_iz, 1.0)
        .expect("Case 970 5-zone post-run conservation must pass legacy 1.0 W tolerance");
}

/// Issue #1446 acceptance criterion #6 (regression): the existing Case
/// 920/950/960 reference data files must remain unchanged on disk.
#[test]
fn test_case_920_950_960_reference_files_unchanged() {
    let base =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/reference_data/zone_balance");
    for csv in [
        "case_920_energy_reference.csv",
        "case_950_energy_reference.csv",
        "case_960_energy_reference.csv",
    ] {
        let path = base.join(csv);
        assert!(
            path.exists(),
            "Pre-existing Case 920/950/960 reference CSV must remain on disk: {}",
            path.display()
        );
        let contents = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("{csv} must be readable: {e}"));
        assert!(
            contents.lines().count() >= 5,
            "{csv} must still contain the metric rows (>= 5 lines incl. comments)"
        );
    }
}
