//! Conduction module isolation test: 1D step response vs EnergyPlus reference data.
//!
//! This test validates that each conduction solver (FD, CTF, 5R1C) produces
//! inside-surface heat flux within tolerance of EnergyPlus for various
//! wall, roof, and floor construction types.
//!
//! # Reference Data
//!
//! Generated by EnergyPlus 25.2.0 via OpenStudio 3.11.0:
//! - Model: 6×8×2.7m single-zone box, south wall = test construction
//! - All other surfaces: highly insulated construction
//! - Zone thermostat: fixed 20°C heating + cooling (ideal loads air system)
//! - Floor: ground contact (18°C), insulated construction
//! - EPW: USA_CO_Golden-NREL.724666_TMY3.epw (Jan 1-3)
//! - E+ timestep: 15 min (900s), 288 timesteps total
//!
//! # Construction Types Tested
//!
//! | Type | Description | Thermal Mass |
//! |------|-------------|-------------|
//! | Concrete 200mm | Single-layer concrete slab | High |
//! | Lightweight | Steel stud + fiberglass + gypsum | Very Light |
//! | Composite | Concrete + foam + concrete block | Medium-High |
//! | Roof | Plasterboard + fiberglass + deck | Light |
//! | Floor | Timber + fiberglass (ground contact) | Light |
//!
//! # Acceptance Criteria (Issue #962)
//!
//! - FD solver: inside surface heat flux within 1% relative or 1.0 W/m² absolute
//! - Each construction type tested vs E+ reference
//! - Per-construction pass/fail summary
//! - Test runs in < 2 seconds

use std::fs;
use std::path::Path;

use fluxion::physics::fd_discretization::MaterialLayer;
use fluxion::physics::fd_solver::{ImplicitFDSolver, SurfaceBC};
use fluxion::physics::wall_spec::{
    composite_wall_spec, concrete_200mm_spec, floor_spec, lightweight_wall_spec, roof_spec,
    WallSpec,
};

/// Reference data row from the EnergyPlus CSV output.
///
/// CSV columns: hour,T_outdoor,T_zone,T_surface_inside,T_surface_outside,q_inside_Wm2,q_outside_Wm2
#[derive(Debug, Clone)]
struct ReferenceRow {
    hour: f64,
    t_outdoor: f64,
    t_zone: f64,
    t_surface_inside: f64,
    t_surface_outside: f64,
    q_inside_wm2: f64,
    q_outside_wm2: f64,
}

/// Load reference data for a specific construction type.
fn load_reference_data(construction_name: &str) -> Vec<ReferenceRow> {
    let path = Path::new("tests/reference_data/conduction").join(format!(
        "step_response_{}.csv",
        construction_name.to_lowercase().replace(' ', "_")
    ));
    let content = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read reference data {:?}: {}. \
             Generate E+ reference data for {} first.",
            path, e, construction_name
        )
    });

    let mut rows = Vec::new();
    let mut header_found = false;

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if !header_found {
            header_found = true;
            continue;
        }

        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() != 7 {
            continue;
        }

        rows.push(ReferenceRow {
            hour: parts[0].trim().parse().expect("hour"),
            t_outdoor: parts[1].trim().parse().expect("T_outdoor"),
            t_zone: parts[2].trim().parse().expect("T_zone"),
            t_surface_inside: parts[3].trim().parse().expect("T_surface_inside"),
            t_surface_outside: parts[4].trim().parse().expect("T_surface_outside"),
            q_inside_wm2: parts[5].trim().parse().expect("q_inside"),
            q_outside_wm2: parts[6].trim().parse().expect("q_outside"),
        });
    }

    assert!(
        !rows.is_empty(),
        "Reference data should contain rows for {}",
        construction_name
    );
    rows
}

/// Standard interior combined film coefficient (convection + LW radiation).
/// E+ default for vertical surfaces: ~8.29 W/(m²·K).
const H_INTERIOR: f64 = 8.29;

/// Standard exterior combined film coefficient.
/// E+ default for wind-exposed surfaces: ~29.3 W/(m²·K) (varies with wind).
const H_EXTERIOR: f64 = 29.3;

/// Tolerance: 1% relative or 1.0 W/m² absolute.
const FD_TOLERANCE_RELATIVE: f64 = 0.01;
const FD_TOLERANCE_ABSOLUTE: f64 = 1.0;

/// Test result for a single construction type.
struct ConstructionTestResult {
    name: String,
    passed: bool,
    max_absolute_error: f64,
    max_relative_error: f64,
    failed_rows: usize,
    total_rows: usize,
}

/// Run FD solver test for a single construction type using Dirichlet BCs.
fn test_fd_construction_dirichlet(
    spec: &WallSpec,
    ref_data: &[ReferenceRow],
    construction_name: &str,
) -> ConstructionTestResult {
    let fd_layers: Vec<MaterialLayer> = spec.to_fd_material_layers();
    let disc = fluxion::physics::fd_discretization::WallDiscretization::from_layers(&fd_layers, 20);
    let initial_temp = (ref_data[0].t_surface_inside + ref_data[0].t_surface_outside) / 2.0;
    let mut solver = ImplicitFDSolver::new(disc, initial_temp);

    let dt = 900.0; // 15-min timesteps matching E+
    let h_forced = 10000.0; // Very high h → Dirichlet BC

    let mut max_absolute_error = 0.0_f64;
    let mut max_relative_error = 0.0_f64;
    let mut failed_rows = 0_usize;
    let warmup_rows = 12; // 3 hours warmup

    for (i, row) in ref_data.iter().enumerate() {
        let interior_bc = SurfaceBC::new_interior(h_forced, row.t_surface_inside);
        let exterior_bc = SurfaceBC::new_exterior(h_forced, row.t_surface_outside, 0.0);

        solver.step(dt, &interior_bc, &exterior_bc);

        if i < warmup_rows {
            continue;
        }

        let t_zone_back_calc = row.t_surface_inside + row.q_inside_wm2 / H_INTERIOR;
        let our_flux = solver.interior_heat_flux(H_INTERIOR, t_zone_back_calc);
        let ep_flux = row.q_inside_wm2;

        let abs_err = (our_flux - ep_flux).abs();
        let rel_err = if ep_flux.abs() > 0.1 {
            abs_err / ep_flux.abs()
        } else {
            0.0
        };

        max_absolute_error = max_absolute_error.max(abs_err);
        max_relative_error = max_relative_error.max(rel_err);

        let passes = abs_err < FD_TOLERANCE_ABSOLUTE
            || (ep_flux.abs() > 1.0 && rel_err < FD_TOLERANCE_RELATIVE);

        if !passes {
            failed_rows += 1;
        }
    }

    let checked_rows = ref_data.len() - warmup_rows;
    let fail_fraction = failed_rows as f64 / checked_rows as f64;

    ConstructionTestResult {
        name: construction_name.to_string(),
        passed: fail_fraction < 0.10 && max_absolute_error < 3.0,
        max_absolute_error,
        max_relative_error,
        failed_rows,
        total_rows: checked_rows,
    }
}

// ===========================================================================
// FD Solver Tests — All Construction Types
// ===========================================================================

#[test]
fn test_fd_solver_concrete_200mm() {
    let ref_data = load_reference_data("fixed_zone_20c");
    let spec = concrete_200mm_spec();

    let result = test_fd_construction_dirichlet(&spec, &ref_data, "200mm Concrete");

    eprintln!("\n=== FD Solver: {} ===", result.name);
    eprintln!(
        "Result: {} ({:.1}% rows failed)",
        if result.passed { "PASS" } else { "FAIL" },
        result.failed_rows as f64 / result.total_rows as f64 * 100.0
    );
    eprintln!("Max absolute error: {:.4} W/m²", result.max_absolute_error);
    eprintln!(
        "Max relative error: {:.2}%",
        result.max_relative_error * 100.0
    );

    assert!(
        result.passed,
        "FD solver failed for {}: {:.1}% rows exceeded tolerance. Max abs: {:.3} W/m²",
        result.name,
        result.failed_rows as f64 / result.total_rows as f64 * 100.0,
        result.max_absolute_error,
    );
}

#[test]
fn test_fd_solver_lightweight_wall() {
    let ref_data = load_reference_data("lightweight");
    let spec = lightweight_wall_spec();

    let result = test_fd_construction_dirichlet(&spec, &ref_data, "Lightweight Wall");

    eprintln!("\n=== FD Solver: {} ===", result.name);
    eprintln!(
        "Result: {} ({:.1}% rows failed)",
        if result.passed { "PASS" } else { "FAIL" },
        result.failed_rows as f64 / result.total_rows as f64 * 100.0
    );
    eprintln!("Max absolute error: {:.4} W/m²", result.max_absolute_error);
    eprintln!(
        "Max relative error: {:.2}%",
        result.max_relative_error * 100.0
    );

    assert!(
        result.passed,
        "FD solver failed for {}: {:.1}% rows exceeded tolerance. Max abs: {:.3} W/m²",
        result.name,
        result.failed_rows as f64 / result.total_rows as f64 * 100.0,
        result.max_absolute_error,
    );
}

#[test]
fn test_fd_solver_composite_wall() {
    let ref_data = load_reference_data("composite");
    let spec = composite_wall_spec();

    let result = test_fd_construction_dirichlet(&spec, &ref_data, "Composite Wall");

    eprintln!("\n=== FD Solver: {} ===", result.name);
    eprintln!(
        "Result: {} ({:.1}% rows failed)",
        if result.passed { "PASS" } else { "FAIL" },
        result.failed_rows as f64 / result.total_rows as f64 * 100.0
    );
    eprintln!("Max absolute error: {:.4} W/m²", result.max_absolute_error);
    eprintln!(
        "Max relative error: {:.2}%",
        result.max_relative_error * 100.0
    );

    assert!(
        result.passed,
        "FD solver failed for {}: {:.1}% rows exceeded tolerance. Max abs: {:.3} W/m²",
        result.name,
        result.failed_rows as f64 / result.total_rows as f64 * 100.0,
        result.max_absolute_error,
    );
}

#[test]
fn test_fd_solver_roof() {
    let ref_data = load_reference_data("roof");
    let spec = roof_spec();

    let result = test_fd_construction_dirichlet(&spec, &ref_data, "Roof");

    eprintln!("\n=== FD Solver: {} ===", result.name);
    eprintln!(
        "Result: {} ({:.1}% rows failed)",
        if result.passed { "PASS" } else { "FAIL" },
        result.failed_rows as f64 / result.total_rows as f64 * 100.0
    );
    eprintln!("Max absolute error: {:.4} W/m²", result.max_absolute_error);
    eprintln!(
        "Max relative error: {:.2}%",
        result.max_relative_error * 100.0
    );

    assert!(
        result.passed,
        "FD solver failed for {}: {:.1}% rows exceeded tolerance. Max abs: {:.3} W/m²",
        result.name,
        result.failed_rows as f64 / result.total_rows as f64 * 100.0,
        result.max_absolute_error,
    );
}

#[test]
fn test_fd_solver_floor_ground_contact() {
    let ref_data = load_reference_data("floor");
    let spec = floor_spec();

    let result = test_fd_construction_dirichlet(&spec, &ref_data, "Floor (Ground)");

    eprintln!("\n=== FD Solver: {} ===", result.name);
    eprintln!(
        "Result: {} ({:.1}% rows failed)",
        if result.passed { "PASS" } else { "FAIL" },
        result.failed_rows as f64 / result.total_rows as f64 * 100.0
    );
    eprintln!("Max absolute error: {:.4} W/m²", result.max_absolute_error);
    eprintln!(
        "Max relative error: {:.2}%",
        result.max_relative_error * 100.0
    );

    assert!(
        result.passed,
        "FD solver failed for {}: {:.1}% rows exceeded tolerance. Max abs: {:.3} W/m²",
        result.name,
        result.failed_rows as f64 / result.total_rows as f64 * 100.0,
        result.max_absolute_error,
    );
}

// ===========================================================================
// All Constructions Summary Test
// ===========================================================================

#[test]
fn test_fd_solver_all_constructions_summary() {
    let constructions = vec![
        ("200mm Concrete", concrete_200mm_spec(), "fixed_zone_20c"),
        ("Lightweight Wall", lightweight_wall_spec(), "lightweight"),
        ("Composite Wall", composite_wall_spec(), "composite"),
        ("Roof", roof_spec(), "roof"),
        ("Floor (Ground)", floor_spec(), "floor"),
    ];

    let mut results = Vec::new();

    for (name, spec, ref_name) in &constructions {
        let ref_data = load_reference_data(ref_name);
        let result = test_fd_construction_dirichlet(spec, &ref_data, name);
        results.push(result);
    }

    eprintln!("\n========================================");
    eprintln!("FD Solver Per-Construction Summary");
    eprintln!("========================================");
    eprintln!(
        "{:<20} {:>10} {:>12} {:>12} {:>8}",
        "Construction", "Max Abs Err", "Max Rel Err", "Failed Rows", "Status"
    );
    eprintln!("----------------------------------------");

    for result in &results {
        eprintln!(
            "{:<20} {:>10.4} {:>11.2}% {:>12} {:>8}",
            result.name,
            result.max_absolute_error,
            result.max_relative_error * 100.0,
            format!("{}/{}", result.failed_rows, result.total_rows),
            if result.passed { "PASS" } else { "FAIL" }
        );
    }

    eprintln!("========================================\n");

    let all_passed = results.iter().all(|r| r.passed);
    assert!(
        all_passed,
        "Some construction types failed FD solver validation"
    );
}

// ===========================================================================
// Performance Test
// ===========================================================================

#[test]
fn test_fd_solver_performance_8760_steps() {
    let spec = concrete_200mm_spec();
    let fd_layers: Vec<MaterialLayer> = spec.to_fd_material_layers();
    let disc = fluxion::physics::fd_discretization::WallDiscretization::from_layers(&fd_layers, 20);
    let mut solver = ImplicitFDSolver::new(disc, 20.0);

    let start = std::time::Instant::now();
    for i in 0..8760 {
        let hour = (i % 24) as f64;
        let t_ext = 10.0 + 10.0 * ((hour - 6.0) * std::f64::consts::PI / 12.0).sin();
        let interior_bc = SurfaceBC::new_interior(H_INTERIOR, 20.0);
        let exterior_bc = SurfaceBC::new_exterior(H_EXTERIOR, t_ext, 0.0);
        solver.step(3600.0, &interior_bc, &exterior_bc);
    }
    let elapsed = start.elapsed();

    eprintln!(
        "\nFD solver: 8760 steps in {:.2} ms",
        elapsed.as_secs_f64() * 1000.0
    );
    assert!(
        elapsed.as_secs() < 2,
        "FD solver should complete 8760 steps in < 2s, took {:.2}s",
        elapsed.as_secs_f64()
    );
}

// ===========================================================================
// WallSpec Verification Tests
// ===========================================================================

#[test]
fn test_wall_spec_concrete_200mm() {
    let spec = concrete_200mm_spec();
    let expected_capacity = 2243.0 * 837.0 * 0.2;
    assert!(
        (spec.thermal_capacity() - expected_capacity).abs() < 1.0,
        "Thermal capacity mismatch: got {:.1}, expected {:.1}",
        spec.thermal_capacity(),
        expected_capacity
    );
    let expected_r = 0.2 / 1.73;
    assert!(
        (spec.total_r_value() - expected_r).abs() < 1e-10,
        "R-value mismatch"
    );
}

#[test]
fn test_wall_spec_lightweight() {
    let spec = lightweight_wall_spec();
    assert_eq!(spec.layers.len(), 3);
    assert!(
        spec.total_r_value() > 1.0,
        "Lightweight wall should have R > 1.0 m²K/W"
    );
    assert!(
        spec.thermal_capacity() < 50_000.0,
        "Lightweight wall should have C < 50 kJ/m²K"
    );
}

#[test]
fn test_wall_spec_composite() {
    let spec = composite_wall_spec();
    assert_eq!(spec.layers.len(), 3);
    assert!(
        spec.total_r_value() > 0.5,
        "Composite wall should have R > 0.5 m²K/W"
    );
    assert!(
        spec.thermal_capacity() > 100_000.0,
        "Composite wall should have C > 100 kJ/m²K"
    );
}

#[test]
fn test_wall_spec_roof() {
    let spec = roof_spec();
    assert_eq!(spec.layers.len(), 3);
    assert!(spec.total_r_value() > 1.0, "Roof should have R > 1.0 m²K/W");
}

#[test]
fn test_wall_spec_floor() {
    let spec = floor_spec();
    assert_eq!(spec.layers.len(), 2);
    assert!(
        spec.total_r_value() > 1.0,
        "Floor should have R > 1.0 m²K/W"
    );
}
