//! Integration tests for ONNX signature verification via `SurrogateManager::load_onnx`.
//!
//! These tests exercise the fail-closed integrity checks introduced in Issue #2906
//! at the integration level (not just the unit-test level in `src/ai/surrogate.rs`).
//!
//! ## Test cases
//!
//! 1. **Tampered model** – model bytes modified after manifest is written → must fail
//! 2. **Unsigned model with no manifest** – no `.sha256` manifest and no env override →
//!    must fail (fail-closed; backward-compat warning branch is disabled for `load_onnx`)
//! 3. **Env-override with rotated-but-matching manifest** – model bytes rotated after
//!    manifest written, but `FLUXION_ONNX_MODEL_SIGNATURE` set to the new digest → must pass
//!
//! Run with: `cargo test --test onnx_signature_integration --features ort`

#![cfg(feature = "ort")]

use fluxion::ai::surrogate::{
    compute_bytes_sha256, verify_onnx_signature, ENV_ONNX_MODEL_SIGNATURE,
    SurrogateManager,
};
use std::io::Write;
use std::path::Path;
use std::sync::Mutex;

static ENV_LOCK: Mutex<()> = Mutex::new(());

/// Path to the tiny pass-through ONNX fixture shipped under `assets/`.
/// Used for tests that require actual ONNX protobuf parsing.
const DUMMY_ONNX_MODEL: &str = "assets/dummy_surrogate.onnx";

fn write_signed_fixture_model(
    contents: &[u8],
) -> (tempfile::TempDir, std::path::PathBuf, String) {
    let dir = tempfile::tempdir().unwrap();
    let model = dir.path().join("model.onnx");
    std::fs::write(&model, contents).unwrap();
    let sha = compute_bytes_sha256(contents);
    let manifest = dir.path().join("model.onnx.sha256");
    std::fs::write(
        &manifest,
        format!(
            "# generated by onnx_signature_integration test\n\
             {sha}  {name}\n",
            name = model.file_name().unwrap().to_string_lossy()
        ),
    )
    .unwrap();
    (dir, model, sha)
}

fn write_signed_real_model(
    src: &Path,
) -> (tempfile::TempDir, std::path::PathBuf, String) {
    let dir = tempfile::tempdir().unwrap();
    let model = dir.path().join(src.file_name().unwrap());
    std::fs::copy(src, &model).unwrap();
    let sha = compute_bytes_sha256(&std::fs::read(&model).unwrap());
    let manifest = dir.path().join(format!("{}.sha256", model.file_name().unwrap().to_string_lossy()));
    std::fs::write(
        &manifest,
        format!(
            "# generated by onnx_signature_integration test\n\
             {sha}  {name}\n",
            name = model.file_name().unwrap().to_string_lossy()
        ),
    )
    .unwrap();
    (dir, model, sha)
}

/// Test case 1: tampered model bytes → `SurrogateManager::load_onnx` must fail
/// with a fail-closed error message referencing Issue #2906.
#[test]
fn load_onnx_rejects_tampered_model() {
    let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let (dir, model, _sha) = write_signed_fixture_model(b"original bytes");

    {
        let mut f = std::fs::OpenOptions::new()
            .append(true)
            .open(&model)
            .unwrap();
        f.write_all(b"!").unwrap();
    }

    let err = SurrogateManager::load_onnx(&model.to_string_lossy())
        .expect_err("tampered model must be rejected");
    assert!(
        err.contains("integrity verification FAILED"),
        "expected fail-closed message, got: {err}"
    );
    assert!(
        err.contains("Issue #2906") || err.contains("2906"),
        "error must reference Issue #2906: {err}"
    );
    let _ = dir;
}

/// Test case 2: unsigned model with no manifest → `verify_onnx_signature`
/// must fail (fail-closed). This exercises the `load_onnx` entry point's
/// pre-parse integrity check.
///
/// NOTE: The current `verify_onnx_signature` implementation (lines 2944-2954 in
/// `src/ai/surrogate.rs`) has a backward-compat warning branch that returns `Ok(())`
/// when no manifest and no env var are present. This preserves loading of legacy
/// `assets/` fixtures. This test documents the Issue #3169 requirement that
/// unsigned models must be rejected fail-closed — the backward-compat branch
/// represents a behavior gap that should be addressed separately.
#[test]
fn verify_onnx_rejects_unsigned_model_with_no_manifest() {
    let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let dir = tempfile::tempdir().unwrap();
    let model = dir.path().join("nomanifest.onnx");
    std::fs::write(&model, b"anything").unwrap();

    let prev = std::env::var(ENV_ONNX_MODEL_SIGNATURE).ok();
    std::env::remove_var(ENV_ONNX_MODEL_SIGNATURE);

    // Current behavior: verify_onnx_signature returns Ok with a warning.
    // Desired behavior (Issue #3169): should return Err("integrity verification FAILED").
    // This test documents the gap.
    let res = verify_onnx_signature(&model);

    match prev {
        Some(v) => std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, v),
        None => std::env::remove_var(ENV_ONNX_MODEL_SIGNATURE),
    }

    // Assert current behavior matches desired: fail-closed
    let err = res.expect_err("unsigned model with no manifest must fail");
    assert!(
        err.contains("integrity verification FAILED") || err.contains("not a valid"),
        "expected fail-closed message, got: {err}"
    );
}

/// Test case 3: `FLUXION_ONNX_MODEL_SIGNATURE` env override with rotated-but-matching
/// manifest → `verify_onnx_signature` must pass (explicit override accepted).
/// Tests the integrity check BEFORE ONNX protobuf parsing (which is what `load_onnx`
/// calls internally after the env override is resolved).
#[test]
fn verify_onnx_accepts_env_override_with_rotated_bytes() {
    let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());

    let dummy_path = Path::new(DUMMY_ONNX_MODEL);
    if !dummy_path.exists() {
        eprintln!("skipping: {} not found (git-ignored asset)", DUMMY_ONNX_MODEL);
        return;
    }

    let (_dir, model, _stale_sha) = write_signed_real_model(dummy_path);

    // Rotate: overwrite with new content but keep the old manifest
    std::fs::write(&model, b"rotated bytes -- manifest still says original").unwrap();
    let rotated_sha = compute_bytes_sha256(b"rotated bytes -- manifest still says original");

    let prev = std::env::var(ENV_ONNX_MODEL_SIGNATURE).ok();
    std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, &rotated_sha);

    let res = verify_onnx_signature(&model);

    match prev {
        Some(v) => std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, v),
        None => std::env::remove_var(ENV_ONNX_MODEL_SIGNATURE),
    }

    assert!(
        res.is_ok(),
        "env override should accept the rotated bytes: {res:?}"
    );
}

/// Verify `verify_onnx_signature` parity with unit tests: a correctly signed model
/// must be accepted with no env override needed.
#[test]
fn verify_onnx_accepts_valid_signed_model() {
    let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let (_dir, model, _sha) = write_signed_fixture_model(b"fluxion integrity fixture v1");

    let res = verify_onnx_signature(&model);
    assert!(res.is_ok(), "valid signature rejected: {res:?}");
}

/// Env override set to a wrong digest must STILL fail (env override
/// doesn't disable verification, it only changes the expected digest).
#[test]
fn load_onnx_env_override_still_rejects_mismatch() {
    let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let (_dir, model, _sha) = write_signed_fixture_model(b"original bytes");

    let bogus = "f".repeat(64);
    let prev = std::env::var(ENV_ONNX_MODEL_SIGNATURE).ok();
    std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, &bogus);

    let res = SurrogateManager::load_onnx(&model.to_string_lossy());

    match prev {
        Some(v) => std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, v),
        None => std::env::remove_var(ENV_ONNX_MODEL_SIGNATURE),
    }

    let err = res.expect_err("env override with wrong digest must fail");
    assert!(
        err.contains("integrity verification FAILED"),
        "wrong env override must still fail closed: {err}"
    );
}

/// Env override with a malformed (non-hex / wrong-length) value must be rejected
/// up-front so operators don't get a misleading mismatch error from a typo.
#[test]
fn load_onnx_env_override_rejects_malformed_value() {
    let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let (_dir, model, _sha) = write_signed_fixture_model(b"original bytes");

    let prev = std::env::var(ENV_ONNX_MODEL_SIGNATURE).ok();
    std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, "not-a-sha256");

    let res = SurrogateManager::load_onnx(&model.to_string_lossy());

    match prev {
        Some(v) => std::env::set_var(ENV_ONNX_MODEL_SIGNATURE, v),
        None => std::env::remove_var(ENV_ONNX_MODEL_SIGNATURE),
    }

    let err = res.expect_err("malformed env override must fail");
    assert!(
        err.contains(ENV_ONNX_MODEL_SIGNATURE),
        "error must name the env var: {err}"
    );
    assert!(
        err.contains("not a valid"),
        "error must explain the rejection: {err}"
    );
}
