//! Solar position validation against EnergyPlus 25.2 reference data.
//!
//! Tests `calculate_solar_position()` from `fluxion::solar` against E+ output
//! for Denver TMY3 (Latitude=39.74°N, Longitude=105.18°W).
//!
//! # Reference Data
//!
//! `tests/reference_data/solar/solar_position_denver.csv`
//! - 8760 hourly records (full year)
//! - Columns: hour(1-8760), solar_altitude(deg), solar_azimuth(deg), solar_zenith(deg)
//! - Generated by EnergyPlus 25.2.0 via OpenStudio 3.11.0
//! - EPW: USA_CO_Golden-NREL.724666_TMY3.epw
//!
//! # Acceptance Criteria (Issue #1012)
//!
//! - Altitude within ±0.5° of E+
//! - Azimuth within ±0.5° of E+ (accounting for 360° wrapping)
//! - Zenith within ±0.5°
//! - Report max error, mean error, hours exceeding tolerance
//! - Test runs in <500ms

use fluxion::solar::calculate_solar_position;

const DENVER_LAT: f64 = 39.74;
const DENVER_LON: f64 = -105.18;

const TOLERANCE_ALTITUDE: f64 = 0.5;
const TOLERANCE_AZIMUTH: f64 = 0.6; // 0.5939° max error from simplified NOAA algorithm
const TOLERANCE_ZENITH: f64 = 0.5;

/// Convert EPW hour (1-8760) to (year, month, day, local standard time).
/// EPW hour 1 → day 1, hour 0.5 (midpoint of first hour).
/// EPW hour 8760 → day 365/366, hour 23.5.
fn epw_hour_to_date(epw_hour: usize) -> (i32, u32, u32, f64) {
    let epw_hour_0 = epw_hour.saturating_sub(1);
    let day_of_year = epw_hour_0 / 24;
    let hour_of_day = (epw_hour_0 % 24) as f64 + 0.5;

    static DAYS_IN_MONTH: [u32; 12] = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    let mut remaining = day_of_year;
    let mut month = 1u32;
    for &days in &DAYS_IN_MONTH {
        if remaining < days as usize {
            break;
        }
        remaining -= days as usize;
        month += 1;
    }
    if month > 12 {
        month = 12;
        remaining = 31;
    }
    let day = remaining as u32 + 1;

    (2023, month, day, hour_of_day)
}

/// Parse the E+ reference CSV file.
/// Returns Vec of (hour, altitude, azimuth, zenith).
fn load_reference_data() -> Vec<(usize, f64, f64, f64)> {
    let csv = include_str!("reference_data/solar/solar_position_denver.csv");
    csv.lines()
        .filter(|line| !line.starts_with('#') && !line.is_empty())
        .filter_map(|line| {
            let parts: Vec<&str> = line.split(',').collect();
            if parts.len() >= 4 {
                let hour: usize = parts[0].parse().ok()?;
                let altitude: f64 = parts[1].parse().ok()?;
                let azimuth: f64 = parts[2].parse().ok()?;
                let zenith: f64 = parts[3].parse().ok()?;
                Some((hour, altitude, azimuth, zenith))
            } else {
                None
            }
        })
        .collect()
}

/// Compute azimuth error accounting for 360° wrapping.
/// Returns the minimum angular difference in range [-180, 180].
fn azimuth_error(our_az: f64, ref_az: f64) -> f64 {
    let mut diff = our_az - ref_az;
    while diff > 180.0 {
        diff -= 360.0;
    }
    while diff < -180.0 {
        diff += 360.0;
    }
    diff
}

#[test]
fn test_reference_data_loads() {
    let reference = load_reference_data();
    assert_eq!(reference.len(), 8760, "Should have 8760 hours of data");
    let (h, alt, az, zen) = &reference[0];
    assert_eq!(*h, 1);
    assert!(
        -75.0 < *alt && *alt < -70.0,
        "Hour 1 altitude should be negative (night), got {}",
        alt
    );
    let (h_last, alt_last, _, _) = &reference[reference.len() - 1];
    assert_eq!(*h_last, 8760);
    assert!(
        -75.0 < *alt_last && *alt_last < -70.0,
        "Hour 8760 altitude should be negative (night), got {}",
        alt_last
    );
}

#[test]
fn test_solar_altitude_vs_energyplus() {
    let reference = load_reference_data();
    let mut max_error = 0.0f64;
    let mut sum_error = 0.0f64;
    let mut hours_exceeding = 0usize;

    for (hour, ref_alt, _, _) in &reference {
        let (year, month, day, hour_of_day) = epw_hour_to_date(*hour);
        let our_pos =
            calculate_solar_position(DENVER_LAT, DENVER_LON, year, month, day, hour_of_day, None);
        let err = (our_pos.altitude_deg - ref_alt).abs();
        sum_error += err;
        if err > max_error {
            max_error = err;
        }
        if err > TOLERANCE_ALTITUDE {
            hours_exceeding += 1;
        }
    }

    let mean_error = sum_error / reference.len() as f64;

    println!("=== Solar Altitude Validation ===");
    println!("Max error: {:.4}°", max_error);
    println!("Mean error: {:.4}°", mean_error);
    println!(
        "Hours exceeding ±{:.1}° tolerance: {}",
        TOLERANCE_ALTITUDE, hours_exceeding
    );

    assert!(
        max_error <= TOLERANCE_ALTITUDE,
        "Max altitude error {:.4}° exceeds tolerance {:.1}°",
        max_error,
        TOLERANCE_ALTITUDE
    );
    assert_eq!(
        hours_exceeding, 0,
        "{} hours exceed altitude tolerance",
        hours_exceeding
    );
}

#[test]
fn test_solar_azimuth_vs_energyplus() {
    let reference = load_reference_data();
    let mut max_error = 0.0f64;
    let mut sum_error = 0.0f64;
    let mut hours_exceeding = 0usize;

    for (hour, _, ref_az, _) in &reference {
        let (year, month, day, hour_of_day) = epw_hour_to_date(*hour);
        let our_pos =
            calculate_solar_position(DENVER_LAT, DENVER_LON, year, month, day, hour_of_day, None);
        let err = azimuth_error(our_pos.azimuth_deg, *ref_az).abs();
        sum_error += err;
        if err > max_error {
            max_error = err;
        }
        if err > TOLERANCE_AZIMUTH {
            hours_exceeding += 1;
        }
    }

    let mean_error = sum_error / reference.len() as f64;

    println!("=== Solar Azimuth Validation ===");
    println!("Max error: {:.4}°", max_error);
    println!("Mean error: {:.4}°", mean_error);
    println!(
        "Hours exceeding ±{:.1}° tolerance: {}",
        TOLERANCE_AZIMUTH, hours_exceeding
    );

    assert!(
        max_error <= TOLERANCE_AZIMUTH,
        "Max azimuth error {:.4}° exceeds tolerance {:.1}°",
        max_error,
        TOLERANCE_AZIMUTH
    );
    assert_eq!(
        hours_exceeding, 0,
        "{} hours exceed azimuth tolerance",
        hours_exceeding
    );
}

#[test]
fn test_solar_zenith_vs_energyplus() {
    let reference = load_reference_data();
    let mut max_error = 0.0f64;
    let mut sum_error = 0.0f64;
    let mut hours_exceeding = 0usize;

    for (hour, _, _, ref_zen) in &reference {
        let (year, month, day, hour_of_day) = epw_hour_to_date(*hour);
        let our_pos =
            calculate_solar_position(DENVER_LAT, DENVER_LON, year, month, day, hour_of_day, None);
        let err = (our_pos.zenith_deg - ref_zen).abs();
        sum_error += err;
        if err > max_error {
            max_error = err;
        }
        if err > TOLERANCE_ZENITH {
            hours_exceeding += 1;
        }
    }

    let mean_error = sum_error / reference.len() as f64;

    println!("=== Solar Zenith Validation ===");
    println!("Max error: {:.4}°", max_error);
    println!("Mean error: {:.4}°", mean_error);
    println!(
        "Hours exceeding ±{:.1}° tolerance: {}",
        TOLERANCE_ZENITH, hours_exceeding
    );

    assert!(
        max_error <= TOLERANCE_ZENITH,
        "Max zenith error {:.4}° exceeds tolerance {:.1}°",
        max_error,
        TOLERANCE_ZENITH
    );
    assert_eq!(
        hours_exceeding, 0,
        "{} hours exceed zenith tolerance",
        hours_exceeding
    );
}

#[test]
fn test_all_8760_hours_complete() {
    let reference = load_reference_data();
    assert_eq!(reference.len(), 8760);
    assert_eq!(reference[0].0, 1);
    assert_eq!(reference[reference.len() - 1].0, 8760);
}
