//! Golden-output regression harness for SurrogateManager (issue #1335).
//!
//! Verifies that 100 fixed inputs through `SurrogateManager::deterministic_analytical_loads`
//! produce the same outputs recorded in `tests/surrogate_models/golden/golden_v3_1_0.json`.
//!
//! This harness does NOT require an ONNX model to run — it uses the
//! deterministic analytical fallback. The real model, once trained, is
//! gated by `load_version` + the SHA-256 hash check in `registry.json`.
//!
//! The expected golden JSON is regenerated by `python3 scripts/gen_golden_outputs.py`
//! (see ADR-0004). To re-baseline after an intentional model behavior change:
//!   1. update `deterministic_analytical_loads` (or its callers);
//!   2. rerun the generator;
//!   3. commit the new JSON alongside the code change in the same PR.

use fluxion::ai::surrogate::{
    compute_bytes_sha256, validate_hash, ModelRegistry, ModelVersion, SurrogateInputs,
    SurrogateManager, VersionError,
};
use std::path::PathBuf;

fn golden_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("surrogate_models")
        .join("golden")
        .join("golden_v3_1_0.json")
}

fn registry_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("surrogate_models")
        .join("registry.json")
}

#[derive(serde::Deserialize)]
struct GoldenFile {
    #[serde(default)]
    #[allow(dead_code)]
    _meta: serde_json::Value,
    inputs: Vec<GoldenInput>,
    outputs: Vec<f64>,
}

#[derive(serde::Deserialize, Clone)]
struct GoldenInput {
    exterior_temp: f64,
    zone_temp: f64,
    #[allow(dead_code)]
    solar_rad: f64,
    #[allow(dead_code)]
    humidity: f64,
    #[allow(dead_code)]
    occupancy: f64,
    #[allow(dead_code)]
    climate_zone: String,
}

impl GoldenInput {
    fn to_surrogate_inputs(&self) -> SurrogateInputs {
        SurrogateInputs::from_physics(
            self.exterior_temp,
            self.zone_temp,
            self.solar_rad,
            self.humidity,
            self.occupancy,
            &self.climate_zone,
        )
    }
}

/// Per-tensor element-equality assertion: max relative error ≤ 1e-6.
fn assert_close_envelope(actual: &[f64], expected: &[f64], rel_tol: f64) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "length mismatch: actual={} expected={}",
        actual.len(),
        expected.len()
    );
    let mut max_rel: f64 = 0.0;
    let mut max_abs: f64 = 0.0;
    let mut worst_idx: usize = 0;
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let abs = (a - e).abs();
        let denom = e.abs().max(1e-9);
        let rel = abs / denom;
        if rel > max_rel {
            max_rel = rel;
            max_abs = abs;
            worst_idx = i;
        }
    }
    assert!(
        max_rel <= rel_tol,
        "golden regression: max relative error {} at index {} (actual={}, expected={}, abs={}) exceeds tolerance {}",
        max_rel,
        worst_idx,
        actual[worst_idx],
        expected[worst_idx],
        max_abs,
        rel_tol
    );
}

#[test]
fn golden_file_loads_and_has_100_inputs() {
    let path = golden_path();
    assert!(path.exists(), "golden JSON missing at {}", path.display());
    let raw = std::fs::read_to_string(&path).expect("read golden");
    let parsed: GoldenFile = serde_json::from_str(&raw).expect("parse golden");
    assert_eq!(parsed.inputs.len(), 100, "must have 100 fixed inputs");
    assert_eq!(parsed.outputs.len(), 100, "must have 100 outputs");
}

#[test]
fn golden_outputs_match_deterministic_analytical() {
    let raw = std::fs::read_to_string(golden_path()).expect("read golden");
    let parsed: GoldenFile = serde_json::from_str(&raw).expect("parse golden");

    let inputs: Vec<SurrogateInputs> = parsed
        .inputs
        .iter()
        .map(GoldenInput::to_surrogate_inputs)
        .collect();
    let actual = SurrogateManager::deterministic_analytical_loads(&inputs);

    assert_close_envelope(&actual, &parsed.outputs, 1e-6);
}

#[test]
fn golden_outputs_are_deterministic_across_runs() {
    let raw = std::fs::read_to_string(golden_path()).expect("read golden");
    let parsed: GoldenFile = serde_json::from_str(&raw).expect("parse golden");
    let inputs: Vec<SurrogateInputs> = parsed
        .inputs
        .iter()
        .map(GoldenInput::to_surrogate_inputs)
        .collect();

    let first = SurrogateManager::deterministic_analytical_loads(&inputs);
    let second = SurrogateManager::deterministic_analytical_loads(&inputs);
    assert_eq!(first, second, "deterministic output must be stable");
}

#[test]
fn golden_registry_loads_and_lists_v3_1_0() {
    let path = registry_path();
    assert!(path.exists(), "registry missing at {}", path.display());
    let raw = std::fs::read_to_string(&path).expect("read registry");
    let registry = ModelRegistry::from_json_str(&raw).expect("parse registry");

    assert!(!registry.is_empty(), "registry must have ≥1 version");
    let v310 = registry.lookup("3.1.0").expect("v3.1.0 missing");
    assert_eq!(v310.onnx_opset_version, 17);
    assert_eq!(
        v310.model_sha256.len(),
        64,
        "model_sha256 must be 64 hex chars"
    );
    assert!(registry.latest().is_some());
}

#[test]
fn model_version_constructor_rejects_placeholder_and_bad_opset() {
    let sha = "a".repeat(64);
    // Placeholder rejected.
    assert!(matches!(
        ModelVersion::new(
            "0.0.0",
            &sha,
            17,
            &sha,
            "2026-06-27",
            "summary",
            1.0,
            "models/x.onnx"
        ),
        Err(VersionError::PlaceholderVersion(_))
    ));
    // Bad semver rejected.
    assert!(matches!(
        ModelVersion::new(
            "3.1",
            &sha,
            17,
            &sha,
            "2026-06-27",
            "summary",
            1.0,
            "models/x.onnx"
        ),
        Err(VersionError::InvalidSemver(_))
    ));
    // Unsupported opset rejected.
    assert!(matches!(
        ModelVersion::new(
            "1.0.0",
            &sha,
            99,
            &sha,
            "2026-06-27",
            "summary",
            1.0,
            "models/x.onnx"
        ),
        Err(VersionError::UnsupportedOpset(99))
    ));
    // Bad SHA-256 rejected.
    let bad = "z".repeat(64);
    assert!(matches!(
        ModelVersion::new(
            "1.0.0",
            &bad,
            17,
            &sha,
            "2026-06-27",
            "summary",
            1.0,
            "models/x.onnx"
        ),
        Err(VersionError::InvalidHash(_))
    ));
}

#[test]
fn load_version_rejects_unknown_version() {
    let raw = std::fs::read_to_string(registry_path()).expect("read registry");
    let registry = ModelRegistry::from_json_str(&raw).expect("parse registry");
    let result = SurrogateManager::load_version("9.9.9", &registry);
    assert!(result.is_err(), "unknown version must error");
    let err = result.unwrap_err();
    assert!(
        err.contains("not found in registry"),
        "error must explain the miss; got: {}",
        err
    );
}

#[test]
fn load_version_rejects_hash_mismatch() {
    // Build a registry pointing at a temp file with a deliberately wrong hash.
    let tmp = tempdir_path("dummy.onnx");
    std::fs::write(&tmp, b"placeholder bytes for hash mismatch test").unwrap();
    let actual_hash = compute_bytes_sha256(b"placeholder bytes for hash mismatch test");
    // Claim the hash is all zeros.
    let wrong = "0".repeat(64);
    let registry = ModelRegistry::from_versions(vec![ModelVersion::new(
        "9.9.9-test",
        &wrong,
        17,
        &wrong,
        "2026-06-27",
        "synthetic",
        1.0,
        tmp.to_str().unwrap(),
    )
    .unwrap()]);

    let result = SurrogateManager::load_version("9.9.9-test", &registry);
    // Without the `ort` feature we expect the trailing "requires ort" message.
    // With the feature, we expect the hash-mismatch error first.
    let err = result.expect_err("load_version must error");
    assert!(
        err.contains("mismatch") || err.contains("ort"),
        "expected hash mismatch or ort-stub error; got: {}",
        err
    );

    // Sanity: the actual hash *does* validate when we feed it in.
    validate_hash(&actual_hash, &actual_hash).unwrap();
}

#[test]
fn hash_round_trip_on_a_real_file() {
    let tmp = tempdir_path("round_trip.onnx");
    let payload = b"deterministic bytes for sha256 round-trip";
    std::fs::write(&tmp, payload).unwrap();
    let file_hash = fluxion::ai::surrogate::compute_file_sha256(&tmp).unwrap();
    let bytes_hash = compute_bytes_sha256(payload);
    assert_eq!(file_hash, bytes_hash);
    assert_eq!(file_hash.len(), 64);
}

fn tempdir_path(name: &str) -> PathBuf {
    let mut p = std::env::temp_dir();
    p.push(format!("fluxion-surrogate-{}-{}", std::process::id(), name));
    p
}
