//! Recompilation harness (default mode).
//!
//! The preferred path: the candidate source is copied into a fresh
//! tempdir with a harness-generated `Cargo.toml` that pins the
//! workspace dep set, then `cargo build` runs in a subprocess with
//! `--target-dir` pointed at an isolated location. The resulting
//! artifact is loaded by the harness-side runner and dispatched
//! against the edge-case battery.
//!
//! ## Why subprocess `cargo build`
//!
//! - **Hermetic**: a fresh `target/` keeps artifacts out of the
//!   workspace root (issue #1244 hygiene) and avoids caching
//!   invalid optimized kernels across mutations.
//! - **Sandboxed**: the subprocess can be killed at the wall-clock
//!   cap (see [`crate::sandbox`]) without taking down the
//!   campaign driver.
//! - **Dependency-stability**: pinning `Cargo.toml` to the
//!   workspace dep set ensures candidates can't accidentally
//!   pull in a newer `serde` etc.; this is the `cargo audit`
//!   invariant from issue #3336.
//!
//! ## File layout (per evaluation)
//!
//! ```text
//! $TMPDIR/fluxion-evaluator-<uuid>/
//! ├── Cargo.toml          # generated by Recompiler
//! └── src/
//!     ├── lib.rs          # generated wrapper (see below)
//!     └── kernel.rs       # copied from the seed
//! ```
//!
//! The generated `src/lib.rs` instantiates `Candidate::default()`
//! and exposes `evaluate(input_json: &str) -> Result<String, String>`
//! for the harness-side runner to dispatch.

use std::path::{Path, PathBuf};

use crate::sandbox::{SandboxConfig, SandboxEnforcer};
use crate::EvaluatorError;

/// Outcome of a recompilation attempt.
#[derive(Debug)]
pub enum RecompileOutcome {
    /// The candidate compiled and produced an artifact at
    /// `artifact_path`. The caller should load and dispatch it.
    Success {
        /// Absolute path to the compiled `rlib` or `bin` artifact.
        artifact_path: PathBuf,
        /// Captured stderr from `cargo build` (for diagnostics; the
        /// Summary only records errors when the build *failed*).
        stderr: String,
    },
    /// The candidate failed to compile. `stderr` is captured for the
    /// Summary's `error` field.
    CompileFailure {
        /// Captured stderr from `cargo build`.
        stderr: String,
        /// Exit code reported by `cargo` (typically `101`).
        exit_code: Option<i32>,
    },
}

/// Configuration for the [`Recompiler`].
#[derive(Clone, Debug)]
pub struct RecompileConfig {
    /// Workspace root the harness is built into; the candidate's
    /// `Cargo.toml` pins `fluxion_evaluator` from this path so the
    /// compiled artifact can use the harness traits.
    pub workspace_root: PathBuf,

    /// Sandbox config (wall-clock cap, network isolation, …).
    pub sandbox: SandboxConfig,

    /// Optional path to a custom `cargo` binary. Defaults to whatever
    /// `cargo` resolves on `PATH`.
    pub cargo_bin: Option<PathBuf>,

    /// Whether to compile with `--release`. Defaults to `false` —
    /// dev builds are faster to compile, which matters when
    /// driving 1,000+ mutations per campaign. The OpenEvolve
    /// adapter runs a separate `--release` re-evaluation once per
    /// candidate before declaring fitness.
    pub release: bool,
}

impl RecompileConfig {
    /// Construct a default config rooted at the given workspace.
    pub fn new(workspace_root: impl Into<PathBuf>) -> Self {
        let wall_clock_cap = std::time::Duration::from_secs(60);
        let candidate_dir = std::env::temp_dir().join(format!("fluxion-evaluator-{}", uuid_like()));
        Self {
            workspace_root: workspace_root.into(),
            sandbox: SandboxConfig {
                wall_clock_cap,
                network_isolated: true,
                candidate_dir,
                memory_cap_bytes: None,
            },
            cargo_bin: None,
            release: false,
        }
    }
}

/// The recompiler. One instance per evaluation; not `Clone` (the
/// sandbox config owns the candidate dir and shouldn't be shared).
pub struct Recompiler {
    cfg: RecompileConfig,
    enforcer: SandboxEnforcer,
}

impl Recompiler {
    /// Construct a recompiler from a config.
    pub fn new(cfg: RecompileConfig) -> Self {
        let sandbox = SandboxConfig::from_env_with_defaults(cfg.sandbox.clone());
        let enforcer = SandboxEnforcer::new(sandbox);
        Self { cfg, enforcer }
    }

    /// Borrow the recompile config.
    pub fn config(&self) -> &RecompileConfig {
        &self.cfg
    }

    /// Borrow the sandbox enforcer.
    pub fn enforcer(&self) -> &SandboxEnforcer {
        &self.enforcer
    }

    /// Recompile the candidate source into the sandbox directory and
    /// run `cargo build`. On success, returns the artifact path; on
    /// failure, returns [`RecompileOutcome::CompileFailure`] with the
    /// captured stderr for the Summary's `error` field.
    ///
    /// `candidate_source` is the candidate's full Rust source
    /// (already including `use` statements, `pub struct Candidate`,
    /// and `impl Kernel for Candidate`). The harness wraps it with a
    /// generated `Cargo.toml` and a `src/lib.rs` shim that re-exports
    /// the candidate type.
    pub fn recompile(
        &self,
        candidate_id: &str,
        candidate_source: &str,
    ) -> Result<RecompileOutcome, EvaluatorError> {
        let dir = self.cfg.sandbox.candidate_dir.clone();
        let src_dir = dir.join("src");

        // Best-effort clean of any prior contents in this dir; we
        // intentionally do NOT clean the workspace target/ — the
        // --target-dir below points elsewhere.
        std::fs::create_dir_all(&src_dir).map_err(|e| {
            EvaluatorError::Subprocess(format!(
                "create candidate dir `{}` failed: {}",
                src_dir.display(),
                e
            ))
        })?;

        // 1. Write the harness-generated Cargo.toml.
        let cargo_toml = self.generate_cargo_toml();
        std::fs::write(dir.join("Cargo.toml"), cargo_toml)
            .map_err(|e| EvaluatorError::Subprocess(format!("write Cargo.toml failed: {}", e)))?;

        // 2. Write the candidate source into src/kernel.rs and a
        //    generated lib.rs that re-exports the candidate type.
        std::fs::write(src_dir.join("kernel.rs"), candidate_source)
            .map_err(|e| EvaluatorError::Subprocess(format!("write kernel.rs failed: {}", e)))?;
        let lib_rs = self.generate_lib_rs(candidate_id);
        std::fs::write(src_dir.join("lib.rs"), lib_rs)
            .map_err(|e| EvaluatorError::Subprocess(format!("write lib.rs failed: {}", e)))?;

        // 3. Run `cargo build` in a subprocess.
        let mut cmd = std::process::Command::new(
            self.cfg
                .cargo_bin
                .clone()
                .unwrap_or_else(|| PathBuf::from("cargo")),
        );
        cmd.arg("build");
        if self.cfg.release {
            cmd.arg("--release");
        }
        // Pin target-dir to the candidate dir so artifacts stay
        // out of the workspace root (issue #1244 hygiene).
        let target_dir = dir.join("target");
        cmd.arg("--target-dir").arg(&target_dir);
        // Keep the build offline; we already vendored the deps via
        // the generated Cargo.toml. This also ensures the harness
        // doesn't accidentally exfiltrate the candidate source via
        // a network call.
        cmd.env("CARGO_NET_OFFLINE", "true");

        let output = self.enforcer.run(cmd)?;

        if !output.status.success() {
            return Ok(RecompileOutcome::CompileFailure {
                stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
                exit_code: output.status.code(),
            });
        }

        // 4. Locate the artifact. With a single `lib` target, cargo
        //    emits `target/debug/lib<name>.rlib` (Linux/macOS) or
        //    `target/debug/<name>.dll` (Windows). We compute the
        //    expected path here rather than running `cargo metadata`
        //    so the harness has zero JSON-parsing in the hot path.
        let profile = if self.cfg.release { "release" } else { "debug" };
        let artifact = locate_artifact(&target_dir, profile, candidate_id);
        Ok(RecompileOutcome::Success {
            artifact_path: artifact,
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        })
    }

    /// Generate the candidate's `Cargo.toml` from the harness's
    /// workspace dep set. The crate name is the candidate_id with
    /// non-alphanumeric characters replaced by `_`.
    fn generate_cargo_toml(&self) -> String {
        let crate_name = sanitize_crate_name("candidate");
        let workspace = self.cfg.workspace_root.display();
        format!(
            r#"[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "{name}"
path = "src/lib.rs"

[dependencies]
fluxion-evaluator = {{ path = "{workspace}/crates/fluxion-evaluator" }}
serde_json = "1.0"
"#,
            name = crate_name,
            workspace = workspace,
        )
    }

    /// Generate the harness-side `lib.rs` shim. The shim is
    /// deliberately minimal: it re-exports the candidate's
    /// `Kernel` impl so the harness-side runner can dispatch it.
    fn generate_lib_rs(&self, _candidate_id: &str) -> String {
        // The candidate source is at `src/kernel.rs` and exports a
        // `pub struct Candidate` that implements `Kernel`. We
        // re-export the type and provide a top-level `dispatch`
        // function the harness-side runner uses.
        let crate_name = sanitize_crate_name("candidate");
        format!(
            r#"//! Harness-generated wrapper around the candidate kernel.
//!
//! Generated by `fluxion_evaluator::recompile::Recompiler` at
//! evaluation time; do NOT hand-edit — the harness will overwrite it
//! on the next mutation.

mod kernel;

use fluxion_evaluator::kernel::{{EdgeCase, Kernel, KernelInput, KernelOutput, ReferenceOutput}};
use kernel::Candidate;

/// Run the candidate on one edge case, returning the JSON-encoded
/// output. Errors are returned as JSON strings so the harness-side
/// runner can deserialize them uniformly.
pub fn evaluate(input_json: &str) -> Result<String, String> {{
    let input: KernelInput = serde_json::from_str(input_json)
        .map_err(|e| format!("input decode failed: {{}}", e))?;
    let candidate = Candidate::default();
    let output = candidate.evaluate(&input).map_err(|e| format!("{{:?}}", e))?;
    serde_json::to_string(&output).map_err(|e| format!("output encode failed: {{}}", e))
}}

// Re-export for the harness-side runner.
pub use kernel::Candidate as __Candidate;
pub use {crate_name}::*; // keep the crate name link healthy
"#,
            crate_name = crate_name,
        )
    }
}

/// Locate the compiled artifact under `target/<profile>/`.
///
/// cargo emits `<profile>/lib<crate>.rlib` on Unix and
/// `<profile>/<crate>.dll` on Windows. We probe both.
fn locate_artifact(target_dir: &Path, profile: &str, candidate_id: &str) -> PathBuf {
    let _ = candidate_id; // reserved for future per-candidate artifact naming
    let crate_name = sanitize_crate_name("candidate");
    let profile_dir = target_dir.join(profile);
    let rlib = profile_dir.join(format!("lib{}.rlib", crate_name));
    if rlib.exists() {
        return rlib;
    }
    let dll = profile_dir.join(format!("{}.dll", crate_name));
    if dll.exists() {
        return dll;
    }
    // Fallback: return the most likely path even if missing, so the
    // caller sees a sensible error message.
    rlib
}

/// Sanitize a string into a valid Rust crate identifier.
fn sanitize_crate_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (i, ch) in name.chars().enumerate() {
        if i == 0 {
            if ch.is_ascii_alphabetic() || ch == '_' {
                out.push(ch);
            } else {
                out.push('x');
            }
        } else if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push_str("candidate");
    }
    out
}

/// Best-effort monotonic, hex-shaped 8-byte id used to name temp
/// dirs. Not a UUID; just enough uniqueness to avoid collisions
/// inside one campaign. The replacement uses std's SystemTime so we
/// don't pull in `uuid` (which would be a new third-party crate).
fn uuid_like() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{:x}", nanos)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_handles_pathological_inputs() {
        assert_eq!(sanitize_crate_name("candidate"), "candidate");
        assert_eq!(
            sanitize_crate_name("9starts_with_digit"),
            "xstarts_with_digit"
        );
        assert_eq!(
            sanitize_crate_name("has-dashes-and.dots"),
            "has_dashes_and_dots"
        );
        assert_eq!(sanitize_crate_name(""), "candidate");
        // Spaces and unicode are replaced with underscores.
        assert_eq!(sanitize_crate_name("hello world"), "hello_world");
    }

    #[test]
    fn cargo_toml_pins_workspace_path() {
        let cfg = RecompileConfig::new("/tmp/ws");
        let r = Recompiler::new(cfg);
        let toml = r.generate_cargo_toml();
        assert!(toml.contains("path = \"/tmp/ws/crates/fluxion-evaluator\""));
        assert!(toml.contains("[dependencies]"));
        assert!(toml.contains("serde_json"));
    }

    #[test]
    fn lib_rs_wraps_candidate_and_exposes_dispatch() {
        let cfg = RecompileConfig::new("/tmp/ws");
        let r = Recompiler::new(cfg);
        let lib = r.generate_lib_rs("ctf-seed-0042");
        assert!(lib.contains("mod kernel"));
        assert!(lib.contains("pub fn evaluate(input_json: &str) -> Result<String, String>"));
        assert!(lib.contains("KernelInput"));
    }
}
