name: Setup Python Environment
description: Install Python with system dependencies

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config python3-dev
      env:
        DEBIAN_FRONTEND: noninteractive
