const fs = require('fs');
const resultsFile = process.env.RESULTS_FILE;

if (!fs.existsSync(resultsFile)) {
  console.log('No results file found, skipping comment');
  return;
}

const results = JSON.parse(fs.readFileSync(resultsFile, 'utf8'));
const s = results.summary;

const passIcon = s.validation_cases_failed === 0 ? '✅' : (s.pass_rate >= 50 ? '🟡' : '🔴');
const body = `## ${passIcon} ASHRAE 140 Benchmark Harness

| Metric | This PR |
|--------|---------|
| Cases passed | **${s.validation_cases_passed}** / ${s.total_validation_cases} (${s.pass_rate.toFixed(1)}%) |
| Cases failed | ${s.validation_cases_failed} |
| MAE | ${s.mae_percent.toFixed(2)}% |
| Duration | ${s.total_duration_s.toFixed(1)}s |
| Commit | \`${results.commit_sha}\` |

<details>
<summary>Per-target timing</summary>

| Target | ✓ | ✗ | Time |
|--------|---|---|------|
${results.test_targets.map(t =>
  `| \`${t.target}\` | ${t.tests_passed} | ${t.tests_failed} | ${t.duration_s.toFixed(1)}s |`
).join('\n')}
</details>

_Generated by [ASHRAE 140 Benchmark Harness](.github/workflows/ashrae_benchmark_harness.yml)_`;

// Find and update existing comment, or create new one
const {data: comments} = await github.rest.issues.listComments({
  owner: context.repo.owner,
  repo: context.repo.repo,
  issue_number: context.issue.number,
});

const existingComment = comments.find(c =>
  c.user.login === 'github-actions[bot]' &&
  c.body.includes('ASHRAE 140 Benchmark Harness')
);

if (existingComment) {
  await github.rest.issues.updateComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    comment_id: existingComment.id,
    body,
  });
} else {
  await github.rest.issues.createComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
    body,
  });
}
