name: Rust + Python Environment
description: Complete Rust and Python environment setup with all dependencies

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.10'
  rust-components:
    description: 'Rust components to install (e.g., rustfmt,clippy)'
    required: false
    default: ''
  cache:
    description: 'Enable pip caching'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Create pip cache directory
      if: inputs.cache == 'true'
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          mkdir -p ~/AppData/Local/pip/Cache
        else
          mkdir -p ~/.cache/pip
        fi

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache == 'true' && 'pip' || '' }}
        cache-dependency-path: 'requirements-dev.txt'

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config python3-dev
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}
