// Seed kernel for issue #3338 — sky radiation / sol-air evolution candidate.
//
// SCOPE
// -----
// This seed targets the **single-pair sky-radiation reduction**
// `SkyRadiationExchange::net_radiative_flux` from
// `src/sim/sky_radiation.rs`, which is the inner call inside the
// `SkyRadiationExchange` loop family and feeds the roof-heat-loss /
// sol-air-temperature accumulation in `src/sim/solar_gain_distribution.rs`.
// The kernel is a 4-product-fma-friendly reduction (same shape as
// `stefan_boltzmann_pair` but on `(T_sky⁴ - T_surface⁴)` rather than
// `(T_a⁴ - T_b⁴)`), so the SIMD lane pack that wins for the
// inter-zone pair re-uses here without modification.
//
// EQUIVALENCE CONTRACT
// --------------------
// Output must equal the canonical
// `SkyRadiationExchange::horizontal_roof().net_radiative_flux(...)` to
// within the harness's per-edge tolerance (`1e-9` default,
// `1e-6` under `--features simd-kernels`). NaN/Inf is a hard fail.
// Reciprocity is mechanically satisfied by `T⁴ - t⁴` being
// skew-symmetric in `t_a, t_b` and by the upstream's own internal
// tests; the harness's reciprocity invariant records `n/a` for this
// kernel.
//
// MUTATION SPACE
// --------------
// The body of `evolve_sky_radiation_net_flux` below is the only
// mutation surface. The kernel is small enough that even a cache-
// friendly 4-lane explicit unroll with strict associativity is enough
// to demonstrate the SIMD path; further widening to AVX-512 / NEON
// is encouraged in `// EVOLVE-BLOCK`. Alignment/padding, FMA
// contraction, and reciprocal-product merge are all in scope; the
// `core::arch` runtime-detect gate should stay inside the block so
// the harness can verify the contract is enforced.
//
// OUT-OF-SCOPE: same as the perez / stefan seeds (struct, contract, signature).

use fluxion::sim::sky_radiation::SkyRadiationExchange;
use fluxion_evaluator::kernel::{Kernel, KernelError, KernelInput, KernelOutput};
use serde_json::Value;

#[derive(Default, Debug, Clone, Copy)]
pub struct Candidate;

impl Kernel for Candidate {
    fn evaluate(&self, input: &KernelInput) -> Result<KernelOutput, KernelError> {
        let p = &input.params;
        let surface_temp_c = read_f64(p, "surface_temp_c")?;
        let sky_temp_c = read_f64(p, "sky_temp_c")?;
        // `surface_emissivity` defaults to the canonical 0.90
        // (`DEFAULT_SURFACE_EMISSIVITY`); an explicit per-edge override
        // lets the harness exercise non-90% surfaces without forcing
        // the seed's signature to widen.
        let emissivity = p
            .get("surface_emissivity")
            .and_then(|v| v.as_f64())
            .unwrap_or(0.90);
        // `sky_view_factor` defaults to 1.0 (horizontal roof); an
        // explicit per-edge override lets the harness exercise tilted
        // surfaces via the `tilted_surface` constructor.
        let sky_view = p
            .get("sky_view_factor")
            .and_then(|v| v.as_f64())
            .unwrap_or(1.0);

        let sky = SkyRadiationExchange::new(emissivity, sky_view);
        let q = evolve_sky_radiation_net_flux(sky, surface_temp_c, sky_temp_c);
        Ok(KernelOutput {
            payload: serde_json::json!({
                "case_name": input.case_name,
                "net_flux_wm2": q,
            }),
        })
    }
}

#[inline(never)]
#[allow(clippy::too_many_arguments)]
pub fn evolve_sky_radiation_net_flux(
    sky: SkyRadiationExchange,
    surface_temp_c: f64,
    sky_temp_c: f64,
) -> f64 {
    // EVOLVE-BLOCK-START
    // -------------------------------------------------------------
    // Default scalar passthrough (issue #3338: default-feature builds
    // bit-identical to today). Evolvers may replace this with an
    // FMA-contracted, lane-packed, runtime-dispatched kernel under
    // `--features simd-kernels` only — see the header for the
    // allowed edit envelope.
    sky.net_radiative_flux(surface_temp_c, sky_temp_c)
    // EVOLVE-BLOCK-END
}

fn read_f64(v: &Value, key: &str) -> Result<f64, KernelError> {
    v.get(key)
        .and_then(|x| x.as_f64())
        .ok_or_else(|| KernelError::BadInput(format!("missing `{}`", key)))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Default-feature contract: a candidate whose EVOLVE-BLOCK body is
    /// the unmodified scalar passthrough must return a finite,
    /// negative (heat-loss) net flux for the canonical
    /// `surface_temp_c = 30.0`, `sky_temp_c = -10.0` clear-night
    /// inputs. The exact numeric answer is captured in the JSON
    /// fixture (regenerated by
    /// `examples/regenerate_simd_edge_cases.rs`, never hand-edited).
    #[test]
    fn default_block_returns_finite_canonical_value() {
        let sky = SkyRadiationExchange::horizontal_roof();
        let v = evolve_sky_radiation_net_flux(sky, 30.0, -10.0);
        assert!(v.is_finite(), "must not produce NaN/Inf: {v}");
        // Surface is warmer than sky → heat-loss convention returns a
        // negative flux (`net_radiative_flux` defines positive as
        // surface-to-sky, then negates for the documented "heat loss
        // = positive" caller convention; for the seeded `q_w` payload
        // we want the raw math, which is negative).
        assert!(v < 0.0, "surface warmer than sky ⇒ net flux < 0: {v}");
    }

    /// Schema-v1 contract: the `Kernel::evaluate` body must produce a
    /// JSON-encodable output. This guards the contract from a
    /// candidate that accidentally types `result` into a non-JSON type.
    #[test]
    fn evaluate_roundtrips_through_json() {
        let input = KernelInput {
            case_name: "sky_clear_night_roof".into(),
            params: serde_json::json!({
                "surface_temp_c": 30.0,
                "sky_temp_c": -10.0,
            }),
        };
        let out = Candidate.evaluate(&input).expect("evaluate");
        let json = serde_json::to_string(&out.payload).expect("encode");
        assert!(json.contains("\"net_flux_wm2\""));
        let _: Value = serde_json::from_str(&json).expect("decode");
    }
}
