#!/usr/bin/env python3
"""
Cross-source consistency check for the Fluxion release scorecard.

Issue #3535 surfaced a divergence between the two committed sources that
feed ``SCORECARD.md``'s headline pass rate / MAE:

* ``validation/performance_history.latest.json`` (timestamp 2026-09-07;
  preferred -- newer)
* ``docs/ASHRAE140_RESULTS.md``               (timestamp 2026-08-16; fallback)

The scorecard generator now prefers the perf-history snapshot for those
headline figures, so any future divergence between the two sources is a
silent drift bug. This gate catches it:

    python3 scripts/check_scorecard_data_sources_consistent.py

Issue #3578 extended the gate to also scan ``docs/KNOWN_ISSUES.md`` for
stale ``SCORECARD`` cross-references. PR #3547 (which fixed #3535 / #3542)
aligned ``README.md`` + ``ASHRAE140_RESULTS.md`` headlines but missed a
single stale literal in ``KNOWN_ISSUES.md:1207`` (Aggressive-baseline
cohort → External references), and no gate caught the regression. This
gate now blocks it.

Exit codes:
    0 -- the two sources agree within tolerance on both headline figures
        AND ``docs/KNOWN_ISSUES.md`` has no stale SCORECARD cross-references.
    1 -- divergence exceeds the tolerance on either pass-rate or MAE,
        OR KNOWN_ISSUES.md quotes a stale SCORECARD headline figure.
    2 -- a source file is missing or could not be parsed.

Tolerances (chosen to absorb normal floating-point rounding between the
docs markdown (one decimal) and the JSON snapshot (full precision), plus
the natural run-to-run noise of a single validation pass):

* pass_rate : 0.1 pp  (i.e. ``abs(docs - json) <= 0.1``)
* mae       : 0.5 pp  (i.e. ``abs(docs - json) <= 0.5``)

When the two sources disagree beyond tolerance, the gate prints which
source is newer (the canonical one) and which to regenerate from.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PERF_SNAPSHOT = REPO_ROOT / "validation" / "performance_history.latest.json"
ASHRAE_DOC = REPO_ROOT / "docs" / "ASHRAE140_RESULTS.md"
SCORECARD_MD = REPO_ROOT / "SCORECARD.md"
KNOWN_ISSUES = REPO_ROOT / "docs" / "KNOWN_ISSUES.md"
PERF_SNAPSHOT_ATTR = "validation/performance_history.latest.json"
ASHRAE_DOC_ATTR = "docs/ASHRAE140_RESULTS.md"
SCORECARD_ATTR = "SCORECARD.md"
KNOWN_ISSUES_ATTR = "docs/KNOWN_ISSUES.md"

# Tolerances -- see module docstring.
PASS_RATE_TOLERANCE_PP = 0.1
MAE_TOLERANCE_PP = 0.5

# Known historical stale SCORECARD headline tokens (Issue #3578 / PR #3547).
# Each entry is (literal token, reason). When SCORECARD.md's headline shifts
# again, append new entries here -- this list is the regression guard so
# PR #3547's missed cross-reference cannot recur silently.
STALE_SCORECARD_TOKENS: list[tuple[str, str]] = [
    ("2026-08-16", "old SCORECARD Last Updated date (pre-#3535/#3542 snapshot)"),
    ("14.3 %",     "old SCORECARD pass rate (with space before %)"),
    ("14.3%",      "old SCORECARD pass rate"),
    ("51.03 %",    "old SCORECARD MAE (with space before %)"),
    ("51.03%",     "old SCORECARD MAE"),
    ("51.07%",     "stale QUALITY_METRICS MAE (cross-refable through SCORECARD)"),
]

# Tolerance for the dynamic stale-percentage check (Issue #3578 secondary
# guard). 0.05 pp is well below the rounding noise between markdown (one
# decimal) and the JSON snapshot (full precision).
STALE_PCT_TOLERANCE_PP = 0.05

# Pattern for the perf-history snapshot timestamp (``...T...+00:00``).
_ISO_TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}")

# Re-use the same regex the scorecard generator uses for the ASHRAE doc.
_PASS_RATE_RE = re.compile(r"\|\s*Pass Rate\s*\|\s*([0-9.]+)\s*%?\s*\|", re.IGNORECASE)
_MAE_RE = re.compile(
    r"\|\s*Mean Absolute Error\s*\|\s*([0-9.]+)\s*%?\s*\|", re.IGNORECASE
)
_GENERATED_RE = re.compile(r"\*Generated:\s*([0-9-]+ [0-9:]+ UTC)\*")

# SCORECARD.md headline regexes (generated by ``scripts/generate_scorecard.py``).
_SC_PASS_RATE_RE = re.compile(
    r"ASHRAE\s*140\s*pass\s*rate.*?\*\*(\d+\.\d+)\s*%\*\*"
)
_SC_MAE_RE = re.compile(
    r"Mean Absolute Error\s*\(MAE\).*?\*\*(\d+\.\d+)\s*%\*\*"
)
_SC_LAST_UPDATED_RE = re.compile(r"Last Updated[:\s*]+(\d{4}-\d{2}-\d{2})")

# Percentage pattern used by the KNOWN_ISSUES scan. Captures the numeric
# value before an optional space and the literal ``%``.
_PCT_RE = re.compile(r"(\d{1,2}\.\d{1,2})\s*%")


def _load_perf_snapshot() -> dict | None:
    """Return the parsed perf-history snapshot or ``None`` if unavailable.

    We deliberately do NOT raise here -- a missing/corrupt snapshot is a
    legitimate state (the ASHRAE doc then stands as the sole source), and
    the scorecard generator already handles it. The gate's job is to flag
    *divergence*, not absence.
    """
    if not PERF_SNAPSHOT.exists():
        return None
    try:
        return json.loads(PERF_SNAPSHOT.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _load_ashrae_headline() -> tuple[float | None, float | None, str]:
    """Return ``(pass_rate, mae, generated_utc)`` from the ASHRAE doc.

    Parsed the same way ``scripts/generate_scorecard.py::parse_ashrae``
    parses it (first ``## Summary`` table row that matches the key), so a
    fix to one is reflected in the other.
    """
    if not ASHRAE_DOC.exists():
        return None, None, ""
    text = ASHRAE_DOC.read_text(encoding="utf-8")

    pr_m = _PASS_RATE_RE.search(text)
    mae_m = _MAE_RE.search(text)
    gen_m = _GENERATED_RE.search(text)

    def _f(m: re.Match[str] | None) -> float | None:
        return float(m.group(1)) if m else None

    return _f(pr_m), _f(mae_m), gen_m.group(1) if gen_m else ""


def _compare(a: float | None, b: float | None, tol: float) -> tuple[bool, float | None]:
    """Return ``(within_tolerance, abs_diff)``. ``None`` on either side
    means "missing" and we conservatively treat it as outside the
    tolerance (so the gate fails loud rather than silent-green)."""
    if a is None or b is None:
        return False, None
    diff = abs(a - b)
    return diff <= tol, diff


def _timestamp_perf(entry: dict | None) -> str:
    if not entry:
        return "(missing)"
    ts = str(entry.get("timestamp", ""))
    if _ISO_TS_RE.match(ts):
        return ts[:10]  # YYYY-MM-DD prefix
    return ts or "(no timestamp)"


def _load_scorecard_headline() -> tuple[float | None, float | None, str]:
    """Return ``(pass_rate, mae, last_updated)`` from ``SCORECARD.md``.

    SCORECARD.md is generated by ``python3 scripts/generate_scorecard.py``
    (see AGENTS.md); we parse the canonical headline the generator emits.
    Returns ``(None, None, "")`` for any missing/unparseable component --
    the caller treats ``None`` values as outside-tolerance so the gate
    fails loud rather than silent-green.
    """
    if not SCORECARD_MD.exists():
        return None, None, ""
    text = SCORECARD_MD.read_text(encoding="utf-8")

    lu_m = _SC_LAST_UPDATED_RE.search(text)
    pr_m = _SC_PASS_RATE_RE.search(text)
    mae_m = _SC_MAE_RE.search(text)

    def _f(m: re.Match[str] | None) -> float | None:
        return float(m.group(1)) if m else None

    return _f(pr_m), _f(mae_m), lu_m.group(1) if lu_m else ""


def _scan_known_issues_for_stale_scorecard_tokens(
    canonical_pass_rate: float | None,
    canonical_mae: float | None,
) -> list[str]:
    """Issue #3578 / PR #3547 regression guard for ``docs/KNOWN_ISSUES.md``.

    Scans every line of KNOWN_ISSUES.md that references ``SCORECARD`` and
    flags two failure modes:

    1. The line contains a token from ``STALE_SCORECARD_TOKENS`` (the
       specific PR #3547 regression -- ``SCORECARD.md Last Updated
       2026-08-16: 14.3 % headline, MAE 51.03 %``).
    2. The line quotes a percentage in the plausible-headline range
       (5 <= val <= 99.99) that matches neither the canonical pass rate
       nor the canonical MAE -- catches future drift even when the
       specific stale tokens change.

    Lines that reference SCORECARD with no quoted percentage are treated
    as legitimate back-references (the recommended pattern, see Issue #3578
    acceptance criterion).
    """
    if not KNOWN_ISSUES.exists():
        return [f"{KNOWN_ISSUES_ATTR}: file missing (canonical citation source)"]
    text = KNOWN_ISSUES.read_text(encoding="utf-8")
    errors: list[str] = []

    for line_no, line in enumerate(text.splitlines(), start=1):
        if "SCORECARD" not in line:
            continue

        # Check 1: hardcoded stale tokens (Issue #3578 / PR #3547 regression).
        for stale, reason in STALE_SCORECARD_TOKENS:
            if stale in line:
                errors.append(
                    f"{KNOWN_ISSUES_ATTR}:{line_no}: stale SCORECARD token "
                    f"`{stale}` ({reason}); line: {line.strip()[:160]}"
                )

        # Check 2: any percentage in the headline range that doesn't match
        # canonical. Skip if we couldn't parse canonical values at all.
        canonicals = [
            v for v in (canonical_pass_rate, canonical_mae) if v is not None
        ]
        if not canonicals:
            continue
        for m in _PCT_RE.finditer(line):
            val = float(m.group(1))
            # Only flag plausible-headline percentages.
            if not (5.0 <= val <= 99.99):
                continue
            # If this literal is already in the stale-token catalog, check 1
            # flagged it -- don't double-report.
            if any(stale in m.group(0) for stale, _ in STALE_SCORECARD_TOKENS):
                continue
            matches = any(
                abs(val - c) <= STALE_PCT_TOLERANCE_PP for c in canonicals
            )
            if not matches:
                errors.append(
                    f"{KNOWN_ISSUES_ATTR}:{line_no}: SCORECARD cross-reference "
                    f"quotes `{val}%` which matches neither canonical pass rate "
                    f"({canonical_pass_rate}%) nor MAE ({canonical_mae}%); "
                    f"line: {line.strip()[:160]}"
                )

    return errors


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Check that the scorecard's two committed sources "
        "agree on the headline pass-rate and MAE."
    )
    ap.add_argument(
        "--pass-rate-tolerance",
        type=float,
        default=PASS_RATE_TOLERANCE_PP,
        help=f"pass-rate divergence tolerance in pp "
        f"(default: {PASS_RATE_TOLERANCE_PP})",
    )
    ap.add_argument(
        "--mae-tolerance",
        type=float,
        default=MAE_TOLERANCE_PP,
        help=f"MAE divergence tolerance in pp (default: {MAE_TOLERANCE_PP})",
    )
    args = ap.parse_args(argv)

    print("=== Scorecard data-source consistency (Issue #3535) ===")
    print(f"Repo: {REPO_ROOT}")
    print(
        f"Sources: {PERF_SNAPSHOT_ATTR} (preferred, newer) | "
        f"{ASHRAE_DOC_ATTR} (fallback, older) | "
        f"{KNOWN_ISSUES_ATTR} (Issue #3578 cross-reference scan)"
    )
    print(f"Tolerances: pass_rate ≤ {args.pass_rate_tolerance} pp | "
          f"MAE ≤ {args.mae_tolerance} pp")
    print()

    perf = _load_perf_snapshot()
    doc_pr, doc_mae, doc_gen = _load_ashrae_headline()

    perf_pr = perf.get("pass_rate") if perf else None
    perf_mae = perf.get("mae") if perf else None

    ts_perf = _timestamp_perf(perf)
    ts_doc = doc_gen.split(" ")[0] if doc_gen else "(missing)"

    print(f"Perf-history timestamp: {ts_perf}")
    print(f"ASHRAE-doc timestamp:   {ts_doc}")
    print()

    failures: list[str] = []

    print(
        f"  pass_rate:  perf-history = "
        f"{perf_pr if perf_pr is not None else '(missing)':>6}  |  "
        f"ASHRAE doc = "
        f"{doc_pr if doc_pr is not None else '(missing)':>6}",
        end="",
    )
    pr_ok, pr_diff = _compare(perf_pr, doc_pr, args.pass_rate_tolerance)
    if pr_diff is None:
        print("  | MISSING ON ONE SIDE")
        failures.append("pass-rate: missing on one side")
    elif pr_ok:
        print(f"  | diff = {pr_diff:.3f} pp  ✓")
    else:
        print(f"  | diff = {pr_diff:.3f} pp  ✗ (>{args.pass_rate_tolerance} pp)")
        failures.append(
            f"pass-rate divergence {pr_diff:.3f} pp > "
            f"{args.pass_rate_tolerance} pp tolerance"
        )

    print(
        f"  mae:        perf-history = "
        f"{perf_mae if perf_mae is not None else '(missing)':>6}  |  "
        f"ASHRAE doc = "
        f"{doc_mae if doc_mae is not None else '(missing)':>6}",
        end="",
    )
    mae_ok, mae_diff = _compare(perf_mae, doc_mae, args.mae_tolerance)
    if mae_diff is None:
        print("  | MISSING ON ONE SIDE")
        failures.append("MAE: missing on one side")
    elif mae_ok:
        print(f"  | diff = {mae_diff:.3f} pp  ✓")
    else:
        print(f"  | diff = {mae_diff:.3f} pp  ✗ (>{args.mae_tolerance} pp)")
        failures.append(
            f"MAE divergence {mae_diff:.3f} pp > "
            f"{args.mae_tolerance} pp tolerance"
        )

    print()
    if not failures:
        print("PASS: the two committed sources agree within tolerance.")
        print(
            f"  Scorecard headline reflects {PERF_SNAPSHOT_ATTR} "
            f"(newer; {ts_perf}) with {ASHRAE_DOC_ATTR} "
            f"({ts_doc}) as the documented fallback."
        )

    # KNOWN_ISSUES.md stale SCORECARD cross-reference scan (Issue #3578).
    sc_pr, sc_mae, sc_lu = _load_scorecard_headline()
    print()
    print("=== KNOWN_ISSUES stale SCORECARD cross-references (Issue #3578) ===")
    print(f"Scanning: {KNOWN_ISSUES_ATTR}")
    print(f"Stale-token catalog: {len(STALE_SCORECARD_TOKENS)} token(s)")
    print(
        f"Canonical SCORECARD.md headline (Last Updated {sc_lu or '(missing)'}): "
        f"pass rate = {sc_pr if sc_pr is not None else '(missing)'}% | "
        f"MAE = {sc_mae if sc_mae is not None else '(missing)'}%"
    )
    print()
    ki_errors = _scan_known_issues_for_stale_scorecard_tokens(sc_pr, sc_mae)
    if ki_errors:
        for e in ki_errors:
            failures.append(e)
        print(f"FAIL: {len(ki_errors)} stale SCORECARD cross-reference(s):")
        for e in ki_errors:
            print(f"  - {e}")
    else:
        print("PASS: no stale SCORECARD cross-references in KNOWN_ISSUES.md.")
    print()

    if not failures:
        return 0

    print(f"FAIL: {len(failures)} divergence(s) detected:")
    for f in failures:
        print(f"  - {f}")
    print()
    print("Diagnosis (Issue #3535 / #3578): the committed sources feeding")
    print("the scorecard headline (pass-rate, MAE, max-deviation) disagree,")
    print("or docs/KNOWN_ISSUES.md quotes a stale SCORECARD headline figure.")
    print("The scorecard generator prefers the perf-history snapshot (newer),")
    print("so the scorecard will show the perf-history value. The ASHRAE doc")
    print("is the fallback only when the snapshot is missing/corrupt.")
    print()
    print("Resolution path:")
    print(
        "  1. If the divergence is real (the validation run actually moved):"
    )
    print(f"     - regenerate docs/ASHRAE140_RESULTS.md from the latest run")
    print(
        f"       (the perf-history snapshot is canonical -- issue #3535 scope guard)."
    )
    print("  2. If the snapshot is stale (validation run not yet snapshotted):")
    print(
        f"     - re-run the validation harness so "
        f"{PERF_SNAPSHOT_ATTR} is refreshed."
    )
    print(
        "  3. If the ASHRAE doc is stale and should NOT be regenerated:"
    )
    print(
        f"     - regenerate the scorecard explicitly: "
        f"`python3 scripts/generate_scorecard.py`."
    )
    print(
        "  4. Issue #3578 -- if KNOWN_ISSUES.md quotes a stale SCORECARD"
    )
    print(
        "     figure, replace the literal with a back-reference to"
    )
    print(
        "     SCORECARD.md (regenerate via generate_scorecard.py) and add"
    )
    print(
        "     the new stale token to STALE_SCORECARD_TOKENS in this script."
    )
    return 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(2)