#!/usr/bin/env python3
"""
Aggregate hourly EnergyPlus reference data into monthly heating/cooling totals.

Reads:
    tests/reference_data/zone_balance/case_<ID>_energy_hourly.csv
        Format produced by generate_case_600_900_energy.py /
        generate_case_920_950_960_energy.py:
            hour,T_zone(C),T_out(C),Q_heat(W),Q_cool(W)
            1,...,Q_heat(W),Q_cool(W)
            ...
            8760,...
        Multi-zone cases (950, 960) are 17520 rows (8760 per zone); this script
        sums both zones into one monthly rollup (matching how
        generate_case_920_950_960_energy.py::compute_summary aggregates the
        annual totals).

Writes:
    tests/reference_data/ashrae140/monthly/case_<ID>_monthly_reference.csv
        Format consumed by tests/ashrae_140_blind_validation.rs:
            month,heating_mid_mwh,heating_accept_min_mwh,heating_accept_max_mwh,
                  cooling_mid_mwh,cooling_accept_min_mwh,cooling_accept_max_mwh
            Jan,...

Methodology
-----------
For each calendar month Jan..Dec:
    monthly_heating_mwh  = sum(hourly_Q_heat_in_month_W) / 1e6      # W*h -> MWh
    monthly_cooling_mwh  = sum(hourly_Q_cool_in_month_W) / 1e6
    accept_min           = monthly_mid * (1 - tolerance)
    accept_max           = monthly_mid * (1 + tolerance)
    tolerance            = 0.10    # Phase D ±10% per issue #668 / #1165

Hour -> month mapping follows the same convention as the simulation harness
(`MONTH_START_HOUR` in tests/ashrae_140_blind_validation.rs:100):
    [0, 744, 1416, 2160, 2880, 3624, 4344, 5088, 5832, 6552, 7296, 8016]
Hour `h` belongs to the smallest `MONTH_START_HOUR[m]` <= `h` (12 entries,
linear scan).

Usage
-----
    python3 scripts/generate_monthly_aggregate.py --case 600
    python3 scripts/generate_monthly_aggregate.py --case 900
    python3 scripts/generate_monthly_aggregate.py --all          # 600 + 900
    python3 scripts/generate_monthly_aggregate.py --case 920     # future
    python3 scripts/generate_monthly_aggregate.py --validate     # sanity check

The script is run only against a regenerated hourly E+ CSV. The current
monthly CSVs are NOT generated from this script — they are a documented
degree-day-derived reference (see tests/reference_data/ashrae140/monthly/README.md)
because the Case 600/900 IDFs produce cooling ~50× below the ASHRAE band per
the issue #2748 investigation. This script exists so the regeneration path
is in place when the post-#1323 / #1213 / #1328 cooling physics gap closes
(see docs/KNOWN_ISSUES.md §SOLAR-02 UPDATE / Issue #2239).

References
----------
* Issue #2748 — generate authoritative blind-validation monthly reference data
  (v1.3 DoD)
* Issue #2677 — monthly reference data is interim/placeholder (v1.3 DoD blocker)
* Issue #1165 — Phase D ±10% monthly infrastructure
* ASHRAE 140-2023 Annex B — annual + peak reference bands (no monthly
  breakdown published)
* ASHRAE Fundamentals Ch. 19 — Degree-Day Method (balance point 18.3 °C / 65 °F)
"""

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
ZONE_BALANCE_DIR = REPO_ROOT / "tests/reference_data/zone_balance"
MONTHLY_DIR = REPO_ROOT / "tests/reference_data/ashrae140/monthly"

# Same convention as MONTH_START_HOUR in tests/ashrae_140_blind_validation.rs:100.
# Hour `h` belongs to month `m` where MONTH_START_HOUR[m] <= h < MONTH_START_HOUR[m+1].
# The TMY representative year is non-leap (8760 h).
MONTH_START_HOUR: tuple[int, ...] = (
    0,    # Jan
    744,  # Feb  (31 days)
    1416, # Mar  (28 days)
    2160, # Apr  (31 days)
    2880, # May  (30 days)
    3624, # Jun  (31 days)
    4344, # Jul  (30 days)
    5088, # Aug  (31 days)
    5832, # Sep  (31 days)
    6552, # Oct  (30 days)
    7296, # Nov  (31 days)
    8016, # Dec  (30 days)
    8760, # sentinel for index 12
)

MONTH_LABELS: tuple[str, ...] = (
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
)

# Phase D ±10% acceptance window (issue #668 / #1165).
PHASE_D_TOLERANCE: float = 0.10

# Cases with monthly reference CSVs that can be regenerated by this script.
SUPPORTED_CASES: tuple[str, ...] = ("600", "900", "920", "950", "960")


@dataclass(frozen=True)
class HourlyRow:
    """Parsed row from `case_<id>_energy_hourly.csv`."""

    hour: int
    q_heat_w: float
    q_cool_w: float


@dataclass(frozen=True)
class MonthlyTotals:
    """Per-month heating/cooling totals in MWh (sum over all zones)."""

    heating_mwh: tuple[float, ...]  # 12 entries (Jan..Dec)
    cooling_mwh: tuple[float, ...]  # 12 entries (Jan..Dec)
    annual_heating_mwh: float
    annual_cooling_mwh: float
    rows_used: int


def hour_to_month_idx(hour: int) -> int:
    """Map an hour-of-year (0..8759) to a calendar month index (0..11).

    Mirrors `month_index_for_hour` in tests/ashrae_140_blind_validation.rs:111.
    Linear scan over 12 entries; trivially cheap.
    """
    if not 0 <= hour < 8760:
        raise ValueError(f"hour {hour} outside 0..8759 (non-leap TMY)")
    idx = 0
    for i, start in enumerate(MONTH_START_HOUR):
        if hour >= start:
            idx = i
        else:
            break
    return idx


def parse_hourly_csv(path: Path) -> list[HourlyRow]:
    """Parse `case_<id>_energy_hourly.csv` into a list of `HourlyRow`.

    Comment lines start with `#`; the header line is `hour,T_zone(C),T_out(C),Q_heat(W),Q_cool(W)`.
    Multi-zone cases (950, 960) carry 17520 rows (8760 × num_zones) — every
    row is appended; the monthly aggregator sums across zones, matching the
    annual aggregation in generate_case_920_950_960_energy.py:compute_summary.

    Negative Q_heat / Q_cool (numerical noise) are clamped to 0 — energy
    exports from EnergyPlus can produce tiny negative values at the
    round-off boundary, and a negative monthly sum is physically meaningless.
    """
    rows: list[HourlyRow] = []
    with path.open("r", newline="") as f:
        reader = csv.reader(f)
        header: list[str] | None = None
        for raw in reader:
            line_cells = [c.strip() for c in raw]
            if not line_cells or all(c.startswith("#") or c == "" for c in line_cells):
                continue
            # Some E+ exporters put every metadata comment into one comma-joined
            # cell; normalise that.
            if line_cells[0].startswith("#"):
                continue
            if header is None:
                if line_cells[0] != "hour":
                    raise ValueError(
                        f"{path}: expected header starting with 'hour', got {line_cells}"
                    )
                header = line_cells
                continue
            if len(line_cells) < len(header):
                raise ValueError(
                    f"{path}: row {len(rows)+1} has {len(line_cells)} cells, expected >= {len(header)}"
                )
            try:
                hour = int(line_cells[0])
                q_heat_w = float(line_cells[3])
                q_cool_w = float(line_cells[4])
            except (ValueError, IndexError) as exc:
                raise ValueError(
                    f"{path}: row {len(rows)+1} failed to parse: {line_cells}"
                ) from exc
            rows.append(
                HourlyRow(
                    hour=hour,
                    q_heat_w=max(q_heat_w, 0.0),
                    q_cool_w=max(q_cool_w, 0.0),
                )
            )
    if not rows:
        raise ValueError(f"{path}: no data rows found")
    return rows


def aggregate_monthly(rows: Iterable[HourlyRow]) -> MonthlyTotals:
    """Sum hourly Q_heat/Q_cool into per-month MWh totals.

    Hours are 1-based in the E+ CSV (rows are 1..8760); `hour_to_month_idx`
    expects 0-based, so we subtract 1 before bucketing.
    """
    heating_kwh = [0.0] * 12  # sum in Wh first, divide at the end
    cooling_kwh = [0.0] * 12
    rows_used = 0
    for row in rows:
        m_idx = hour_to_month_idx(row.hour - 1)
        heating_kwh[m_idx] += row.q_heat_w  # Wh/h × 1 h = Wh
        cooling_kwh[m_idx] += row.q_cool_w
        rows_used += 1
    heating_mwh = tuple(wh / 1e6 for wh in heating_kwh)  # Wh -> MWh
    cooling_mwh = tuple(wh / 1e6 for wh in cooling_kwh)
    annual_heating = sum(heating_mwh)
    annual_cooling = sum(cooling_mwh)
    return MonthlyTotals(
        heating_mwh=heating_mwh,
        cooling_mwh=cooling_mwh,
        annual_heating_mwh=annual_heating,
        annual_cooling_mwh=annual_cooling,
        rows_used=rows_used,
    )


def acceptance_window(mid: float, tolerance: float = PHASE_D_TOLERANCE) -> tuple[float, float]:
    """Phase D ±tolerance window around `mid`.

    For `mid == 0.0` (a structurally zero month, e.g. Denver cooling Jan),
    the acceptance window is [0, 0] — no simulated value can "pass" a
    zero-bounded month by construction. The Rust harness skips these
    months (`if ref_mid <= 1e-6 { continue; }` in
    `tests/ashrae_140_blind_validation.rs:594`).
    """
    if mid <= 1e-9:
        return (0.0, 0.0)
    return (mid * (1.0 - tolerance), mid * (1.0 + tolerance))


def build_csv_rows(totals: MonthlyTotals) -> list[list[str]]:
    """Build the data rows for the output CSV (header + Jan..Dec)."""
    rows: list[list[str]] = [
        [
            "month",
            "heating_mid_mwh",
            "heating_accept_min_mwh",
            "heating_accept_max_mwh",
            "cooling_mid_mwh",
            "cooling_accept_min_mwh",
            "cooling_accept_max_mwh",
        ]
    ]
    for m, label in enumerate(MONTH_LABELS):
        h_lo, h_hi = acceptance_window(totals.heating_mwh[m])
        c_lo, c_hi = acceptance_window(totals.cooling_mwh[m])
        rows.append(
            [
                label,
                f"{totals.heating_mwh[m]:.4f}",
                f"{h_lo:.4f}",
                f"{h_hi:.4f}",
                f"{totals.cooling_mwh[m]:.4f}",
                f"{c_lo:.4f}",
                f"{c_hi:.4f}",
            ]
        )
    return rows


def write_monthly_csv(case_id: str, totals: MonthlyTotals, output: Path) -> None:
    """Write the monthly CSV in the format consumed by `tests/ashrae_140_blind_validation.rs`.

    The header banner follows the same convention as the existing CSVs
    (`tests/reference_data/ashrae140/monthly/case_*_monthly_reference.csv`):
    the file is comma-separated so the Rust loader can stream it
    (`load_monthly_reference` in tests/ashrae_140_blind_validation.rs:484
    reads line-by-line, skipping `#` and `month,` rows).
    """
    output.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).isoformat()
    lines: list[str] = [
        f"# Monthly Energy Reference: ASHRAE 140 Case {case_id}",
        f"# Source: aggregated from case_{case_id}_energy_hourly.csv (EnergyPlus ≥25.2.0)",
        "# EPW baseline: USA_CO_Golden-NREL.724666_TMY3.epw",
        f"# Generated: {timestamp}",
        "# Generator: scripts/generate_monthly_aggregate.py",
        f"# Methodology: Σ(hourly Q_heat / Q_cool) per calendar month, ±{PHASE_D_TOLERANCE*100:.0f}% Phase D window",
        "# Annual sanity (sum of monthly):",
        f"#   heating = {totals.annual_heating_mwh:.4f} MWh",
        f"#   cooling = {totals.annual_cooling_mwh:.4f} MWh",
        f"# Rows aggregated: {totals.rows_used}",
    ]
    for row in build_csv_rows(totals):
        lines.append(",".join(row))
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def regenerate_case(case_id: str) -> Path:
    """Regenerate `case_<id>_monthly_reference.csv` from the hourly E+ CSV.

    Returns the output path. Raises FileNotFoundError if the hourly source
    is missing.
    """
    src = ZONE_BALANCE_DIR / f"case_{case_id}_energy_hourly.csv"
    if not src.exists():
        raise FileNotFoundError(
            f"{src}: hourly source missing — run generate_case_{case_id}_energy.py first"
        )
    rows = parse_hourly_csv(src)
    totals = aggregate_monthly(rows)
    out = MONTHLY_DIR / f"case_{case_id}_monthly_reference.csv"
    write_monthly_csv(case_id, totals, out)
    return out


def validate_case(case_id: str) -> tuple[bool, str]:
    """Validate a written monthly CSV: 12 month rows, sums match annual band.

    Returns (ok, message). Reads the CSV we just wrote and:
      - asserts 12 month rows + 1 header row
      - asserts Σ(heating_mid) ≈ annual_heating band [min, max] from
        `tests/reference_data/zone_balance/case_<id>_energy_reference.csv`
      - asserts Σ(cooling_mid) ≈ annual_cooling band [min, max]
    This is the internal-consistency check that closes the loop between
    the monthly CSVs and the authoritative annual bands (the same bands
    referenced by `tests/zone_balance_eplus_isolation.rs`).
    """
    src_csv = MONTHLY_DIR / f"case_{case_id}_monthly_reference.csv"
    annual_csv = ZONE_BALANCE_DIR / f"case_{case_id}_energy_reference.csv"
    hourly_csv = ZONE_BALANCE_DIR / f"case_{case_id}_energy_hourly.csv"
    if not src_csv.exists():
        return (False, f"{src_csv}: missing")
    if not annual_csv.exists():
        return (False, f"{annual_csv}: missing")
    if not hourly_csv.exists():
        return (
            False,
            f"{hourly_csv}: hourly source missing — cannot re-aggregate to validate",
        )

    rows = list(parse_hourly_csv(hourly_csv))
    totals = aggregate_monthly(rows)

    # Parse annual bands from case_<id>_energy_reference.csv
    annual_min_h = annual_max_h = None
    annual_min_c = annual_max_c = None
    with annual_csv.open("r", newline="") as f:
        for raw in csv.reader(f):
            cells = [c.strip() for c in raw]
            if not cells or cells[0].startswith("#") or cells[0] == "metric":
                continue
            metric, _, lo, hi, *_ = cells[:9]
            lo_f, hi_f = float(lo), float(hi)
            if metric == "annual_heating":
                annual_min_h, annual_max_h = lo_f, hi_f
            elif metric == "annual_cooling":
                annual_min_c, annual_max_c = lo_f, hi_f

    msgs: list[str] = []
    sum_h = sum(totals.heating_mwh)
    sum_c = sum(totals.cooling_mwh)
    ok = True
    if annual_min_h is not None and not (annual_min_h <= sum_h <= annual_max_h):
        ok = False
        msgs.append(
            f"Σ heating = {sum_h:.4f} MWh outside annual band [{annual_min_h}, {annual_max_h}]"
        )
    if annual_min_c is not None and not (annual_min_c <= sum_c <= annual_max_c):
        ok = False
        msgs.append(
            f"Σ cooling = {sum_c:.4f} MWh outside annual band [{annual_min_c}, {annual_max_c}]"
        )
    if ok:
        return (True, f"Case {case_id}: Σ H={sum_h:.4f}, Σ C={sum_c:.4f} MWh — within annual bands")
    return (False, f"Case {case_id}: " + "; ".join(msgs))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Aggregate hourly EnergyPlus reference data into monthly CSVs "
        "(issue #2748 / #1165)."
    )
    g = parser.add_mutually_exclusive_group(required=True)
    g.add_argument("--case", choices=SUPPORTED_CASES, help="single case to regenerate")
    g.add_argument("--all", action="store_true", help="regenerate Cases 600 and 900")
    g.add_argument(
        "--validate",
        action="store_true",
        help="sanity-check the monthly CSV against the annual band (read-only)",
    )
    args = parser.parse_args(argv)

    cases = list(SUPPORTED_CASES[:2]) if args.all else ([args.case] if args.case else [])
    if args.validate:
        # Validate every case that already has a monthly CSV
        rc = 0
        for c in SUPPORTED_CASES:
            csv_path = MONTHLY_DIR / f"case_{c}_monthly_reference.csv"
            if not csv_path.exists():
                print(f"Case {c}: no monthly CSV (skipping)")
                continue
            ok, msg = validate_case(c)
            print(msg)
            if not ok:
                rc = 1
        return rc

    rc = 0
    for c in cases:
        try:
            out = regenerate_case(c)
            print(f"Wrote {out}")
        except FileNotFoundError as exc:
            print(f"Case {c}: {exc}", file=sys.stderr)
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
