#!/usr/bin/env python3
"""Automated topology diagram extraction — Issue #3966.

Runs ``fluxion topology export`` for every ASHRAE 140 case in the topology
registry and writes deterministic, committed artifacts:

* ``tests/reference_data/topology/case-<N>.json``      — verbatim export bytes
* ``tests/reference_data/topology/lint/case-<N>.lint.json`` — verbatim
  ``topology lint --strict --format json`` bytes
* ``tests/reference_data/topology/index.json``          — machine index
* ``docs/architecture/topology/case-<N>.mmd``           — Mermaid source
* ``docs/architecture/topology/case-<N>.svg``           — dependency-free
  deterministic structural SVG (stdlib layout, no mermaid-cli/node needed)
* ``docs/architecture/topology/payloads/case-<N>.json`` — viewer payloads for
  ``fluxion-tauri/frontend/public/topology-standalone.html?model=<url>``
* ``docs/architecture/topology/index.md``               — human index

Drift is policed by ``scripts/check_topology_drift.py`` (wired into
``.github/workflows/topology_visualizer.yml``). Output is byte-deterministic:
no timestamps, no tool versions, no environment-derived data.

Usage:
    python3 scripts/generate_topology_diagrams.py [--dest REPO_ROOT] [--fluxion BIN]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# ASHRAE 140 cases registered in the topology export CLI (issue #3963).
TOPOLOGY_CASES = ["600", "610", "620", "630", "640", "650", "900", "960"]

GENERATOR_STAMP = (
    "Generated by scripts/generate_topology_diagrams.py — do not hand-edit. "
    "Drift-gated by scripts/check_topology_drift.py (issue #3966); "
    "regenerate with `python3 scripts/generate_topology_diagrams.py`."
)

REFERENCE_DIR = Path("tests/reference_data/topology")
LINT_DIR = REFERENCE_DIR / "lint"
DOCS_DIR = Path("docs/architecture/topology")
PAYLOAD_DIR = DOCS_DIR / "payloads"

# Deterministic layout: node kind -> column index (left-to-right thermal flow).
KIND_COLUMNS = {
    "outdoor_ambient": 0,
    "exterior_surface": 1,
    "wall_layer": 2,
    "interior_surface": 3,
    "zone_air": 4,
    "internal_mass": 5,
    "hvac_terminal": 6,
    "internal_gain": 7,
}
KIND_COLORS = {
    "outdoor_ambient": "#38bdf8",
    "exterior_surface": "#f97316",
    "wall_layer": "#a16207",
    "interior_surface": "#fbbf24",
    "zone_air": "#ef4444",
    "internal_mass": "#eab308",
    "hvac_terminal": "#14b8a6",
    "internal_gain": "#a855f7",
}
DEFAULT_NODE_COLOR = "#64748b"
EDGE_PALETTE = [
    "#0ea5e9", "#f97316", "#22c55e", "#a855f7", "#ef4444",
    "#eab308", "#14b8a6", "#ec4899", "#6366f1", "#64748b",
]

BOX_W, BOX_H = 170, 40
PITCH_X, PITCH_Y = 230, 54
MARGIN_X, MARGIN_TOP = 40, 64


def locate_fluxion(explicit: str | None) -> str:
    """Resolve the fluxion CLI path.

    Order: --fluxion / $FLUXION_BIN override, then target/debug, then
    target/release. A stale release binary predating the topology subcommand
    (hazard observed 2026-09-21) is rejected by the support probe.
    """
    candidates = []
    if explicit:
        candidates.append(explicit)
    import os

    env_bin = os.environ.get("FLUXION_BIN")
    if env_bin:
        candidates.append(env_bin)
    candidates += [str(REPO_ROOT / "target/debug/fluxion"), str(REPO_ROOT / "target/release/fluxion")]
    for cand in candidates:
        if cand and Path(cand).is_file() and os.access(cand, os.X_OK):
            probe = subprocess.run(
                [cand, "topology", "--help"], capture_output=True, check=False
            )
            if probe.returncode == 0:
                return cand
        if explicit and cand == explicit:
            break
    sys.stderr.write(
        "error: no fluxion CLI with `topology` support found; "
        "run `cargo build -p fluxion` or pass --fluxion/FLUXION_BIN\n"
    )
    raise SystemExit(2)


def run_cli(fluxion: str, args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run([fluxion, *args], capture_output=True, text=True, check=False)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def xml_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def _stable_index(coupling_type: str) -> int:
    total = 0
    for ch in coupling_type.encode("utf-8"):
        total = (total * 131 + ch) % 1_000_003
    return total % len(EDGE_PALETTE)


def render_mermaid(doc: dict, case: str) -> str:
    lines = [
        f"%% {GENERATOR_STAMP}",
        f"%% Case {case}: {doc['metadata'].get('model_name', '')}",
        "flowchart LR",
    ]
    for i, node in enumerate(doc["nodes"]):
        label = node.get("name", node["id"]).replace('"', "'")
        lines.append(f'    n{i}["{label}"]:::{node["kind"]}')
    for edge in doc["edges"]:
        src = _node_index(doc, edge["source_id"])
        tgt = _node_index(doc, edge["target_id"])
        arrow = "<-->" if edge.get("bidirectional") else "-->"
        label = edge.get("coupling_type", "coupling")
        lines.append(f"    n{src} {arrow}|{label}| n{tgt}")
    for kind in sorted({n["kind"] for n in doc["nodes"]}):
        color = KIND_COLORS.get(kind, DEFAULT_NODE_COLOR)
        lines.append(f"    classDef {kind} fill:{color},stroke:#0f172a,color:#0f172a")
    return "\n".join(lines) + "\n"


def _node_index(doc: dict, node_id: str) -> int:
    for i, node in enumerate(doc["nodes"]):
        if node["id"] == node_id:
            return i
    raise KeyError(f"edge references unknown node {node_id!r}")


def render_svg(doc: dict, case: str) -> str:
    nodes = doc["nodes"]
    edges = doc["edges"]
    kind_cols = dict(KIND_COLUMNS)
    next_col = len(kind_cols)
    for node in nodes:
        if node["kind"] not in kind_cols:
            kind_cols[node["kind"]] = next_col
            next_col += 1
    col_rows: dict[int, int] = {}
    pos: dict[str, tuple[int, int]] = {}
    for node in nodes:
        col = kind_cols[node["kind"]]
        row = col_rows.get(col, 0)
        col_rows[col] = row + 1
        pos[node["id"]] = (col, row)
    n_cols = max(col_rows) + 1 if col_rows else 1
    n_rows = max(col_rows.values()) if col_rows else 1

    coupling_types = sorted({e.get("coupling_type", "coupling") for e in edges})
    kinds_present = sorted({n["kind"] for n in nodes})
    legend_h = 28 + 20 * (1 + (len(kinds_present) + len(coupling_types)) // 3 + 1)
    width = MARGIN_X * 2 + PITCH_X * n_cols
    height = MARGIN_TOP + PITCH_Y * n_rows + legend_h + 20

    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{width}\" height=\"{height}\" "
            f"viewBox=\"0 0 {width} {height}\" font-family=\"Helvetica,Arial,sans-serif\">"
        ),
        f"<!-- {GENERATOR_STAMP} -->",
        f'<rect width="{width}" height="{height}" fill="#f8fafc"/>',
        (
            f'<text x="{MARGIN_X}" y="28" font-size="17" font-weight="bold" fill="#0f172a">'
            f"{xml_escape('ASHRAE 140 Case ' + case + ' — ' + doc['metadata'].get('model_name', ''))}</text>"
        ),
        "<defs>",
    ]
    for i, color in enumerate(EDGE_PALETTE):
        parts.append(
            f'<marker id="arrow{i}" viewBox="0 0 10 10" refX="10" refY="5" '
            f'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
            f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{color}"/></marker>'
        )
    parts.append("</defs>")

    # Edges (drawn under the boxes).
    for edge in edges:
        s_col, s_row = pos[edge["source_id"]]
        t_col, t_row = pos[edge["target_id"]]
        x1 = MARGIN_X + s_col * PITCH_X + BOX_W
        y1 = MARGIN_TOP + s_row * PITCH_Y + BOX_H // 2
        x2 = MARGIN_X + t_col * PITCH_X
        y2 = MARGIN_TOP + t_row * PITCH_Y + BOX_H // 2
        if t_col > s_col:
            mid = (x1 + x2) / 2
            path = f"M {x1} {y1} C {mid} {y1}, {mid} {y2}, {x2} {y2}"
        else:
            bulge = y1 + (60 if t_row >= s_row else -60)
            mid = (x1 + x2) / 2
            path = f"M {x1} {y1} C {mid} {bulge}, {mid} {y2}, {x2} {y2}"
        color_idx = _stable_index(edge.get("coupling_type", "coupling"))
        color = EDGE_PALETTE[color_idx]
        title = xml_escape(
            f"{edge['source_id']} -> {edge['target_id']} ({edge.get('coupling_type', 'coupling')})"
        )
        parts.append(
            f'<path d="{path}" fill="none" stroke="{color}" stroke-width="1.4" '
            f'opacity="0.75" marker-end="url(#arrow{color_idx})"><title>{title}</title></path>'
        )

    # Nodes.
    for node in nodes:
        col, row = pos[node["id"]]
        x = MARGIN_X + col * PITCH_X
        y = MARGIN_TOP + row * PITCH_Y
        color = KIND_COLORS.get(node["kind"], DEFAULT_NODE_COLOR)
        label = node.get("name", node["id"])
        if len(label) > 24:
            label = label[:23] + "…"
        parts.append(
            f'<g><title>{xml_escape(node["id"] + " (" + node["kind"] + ")")}</title>'
            f'<rect x="{x}" y="{y}" width="{BOX_W}" height="{BOX_H}" rx="7" '
            f'fill="{color}" stroke="#0f172a" stroke-width="1"/>'
            f'<text x="{x + BOX_W // 2}" y="{y + BOX_H // 2 + 4}" font-size="11" '
            f'text-anchor="middle" fill="#0f172a">{xml_escape(label)}</text></g>'
        )

    # Legend.
    ly = MARGIN_TOP + PITCH_Y * n_rows + 24
    parts.append(f'<text x="{MARGIN_X}" y="{ly}" font-size="12" font-weight="bold" fill="#0f172a">Legend</text>')
    lx, ly2 = MARGIN_X, ly + 18
    for kind in kinds_present:
        color = KIND_COLORS.get(kind, DEFAULT_NODE_COLOR)
        parts.append(
            f'<rect x="{lx}" y="{ly2 - 9}" width="12" height="12" rx="3" fill="{color}" stroke="#0f172a"/>'
            f'<text x="{lx + 17}" y="{ly2 + 1}" font-size="11" fill="#0f172a">{xml_escape(kind)}</text>'
        )
        lx += 190
        if lx > width - 200:
            lx, ly2 = MARGIN_X, ly2 + 18
    lx, ly2 = MARGIN_X, ly2 + 20
    for ctype in coupling_types:
        color = EDGE_PALETTE[_stable_index(ctype)]
        idx = _stable_index(ctype)
        parts.append(
            f'<path d="M {lx} {ly2} L {lx + 26} {ly2}" stroke="{color}" stroke-width="2" '
            f'marker-end="url(#arrow{idx})"/>'
            f'<text x="{lx + 33}" y="{ly2 + 4}" font-size="11" fill="#0f172a">{xml_escape(ctype)}</text>'
        )
        lx += 190
        if lx > width - 200:
            lx, ly2 = MARGIN_X, ly2 + 18
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def render_docs_index(entries: list[dict]) -> str:
    lines = [
        "# Topology Diagrams — Issue #3966",
        "",
        (
            f"Machine-generated ASHRAE 140 topology diagrams (Mermaid + structural SVG) with "
            f"verbatim `fluxion topology export` references, `topology lint --strict` reports, "
            f"and standalone-viewer payloads. {GENERATOR_STAMP}"
        ),
        "",
        (
            "Each case row links the committed artifacts; the reference JSONs under "
            "`tests/reference_data/topology/` are the drift-gated source of truth."
        ),
        "",
        (
            "Open the viewer at `fluxion-tauri/frontend/public/topology-standalone.html` and load a "
            "payload via `?model=` or drag-and-drop (issue #3965)."
        ),
        "",
        "| Case | Model | Nodes | Couplings | Lint (strict) | Mermaid | SVG | Viewer payload |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        lint = e["lint"]
        lint_cell = "✅ clean" if lint["clean"] else f"❌ {lint['errors']} err / {lint['warnings']} warn"
        lines.append(
            f"| {e['case']} | {e['model_name']} | {e['node_count']} | {e['edge_count']} | "
            f"{lint_cell} | [case-{e['case']}.mmd](case-{e['case']}.mmd) | "
            f"[case-{e['case']}.svg](case-{e['case']}.svg) | "
            f"[payloads/case-{e['case']}.json](payloads/case-{e['case']}.json) |"
        )
    lines += [
        "",
        "## How to regenerate",
        "",
        "```bash",
        "cargo build -p fluxion   # debug build is what the drift gate uses",
        "python3 scripts/generate_topology_diagrams.py",
        "python3 scripts/check_topology_drift.py   # must exit 0 before you commit",
        "```",
        "",
        (
            "The drift gate (`scripts/check_topology_drift.py`, wired into "
            "`.github/workflows/topology_visualizer.yml`) regenerates everything into a temp "
            "directory and byte-compares it against the committed tree; any physics change that "
            "alters the topology graph requires regenerating and committing these artifacts in "
            "the same PR."
        ),
        "",
    ]
    return "\n".join(lines)


def generate(dest_root: Path, fluxion_bin: str) -> int:
    dest_root = dest_root.resolve()
    ref_dir = dest_root / REFERENCE_DIR
    lint_dir = dest_root / LINT_DIR
    docs_dir = dest_root / DOCS_DIR
    payload_dir = dest_root / PAYLOAD_DIR
    for d in (ref_dir, lint_dir, docs_dir, payload_dir):
        d.mkdir(parents=True, exist_ok=True)

    entries: list[dict] = []
    failures = 0
    for case in TOPOLOGY_CASES:
        with tempfile.TemporaryDirectory() as td:
            tmp_export = Path(td) / f"case-{case}.json"
            export = run_cli(fluxion_bin, ["topology", "export", "--case", case, "--output", str(tmp_export)])
            if export.returncode != 0 or not tmp_export.is_file():
                sys.stderr.write(f"error: topology export failed for case {case}: {export.stderr}\n")
                failures += 1
                continue
            export_bytes = tmp_export.read_bytes()
            lint = run_cli(fluxion_bin, ["topology", "lint", "--case", case, "--strict", "--format", "json"])
            if lint.returncode != 0:
                sys.stderr.write(
                    f"error: topology lint --strict failed for case {case} "
                    f"(exit {lint.returncode}): {lint.stdout}{lint.stderr}\n"
                )
                failures += 1
            lint_bytes = lint.stdout.encode("utf-8")
            doc = json.loads(export_bytes.decode("utf-8"))

            rel_ref = REFERENCE_DIR / f"case-{case}.json"
            rel_lint = LINT_DIR / f"case-{case}.lint.json"
            rel_mmd = DOCS_DIR / f"case-{case}.mmd"
            rel_svg = DOCS_DIR / f"case-{case}.svg"
            rel_payload = PAYLOAD_DIR / f"case-{case}.json"
            (dest_root / rel_ref).write_bytes(export_bytes)
            (dest_root / rel_lint).write_bytes(lint_bytes)
            (dest_root / rel_mmd).write_text(render_mermaid(doc, case), encoding="utf-8")
            (dest_root / rel_svg).write_text(render_svg(doc, case), encoding="utf-8")
            (dest_root / rel_payload).write_bytes(export_bytes)

            try:
                lint_doc = json.loads(lint.stdout)
            except json.JSONDecodeError:
                lint_doc = {"clean": False, "summary": {"errors": -1, "warnings": -1, "total": -1}}
            meta = doc["metadata"]
            entries.append(
                {
                    "case": case,
                    "model_name": meta.get("model_name", ""),
                    "model_source": meta.get("model_source", ""),
                    "node_count": meta.get("node_count", len(doc["nodes"])),
                    "edge_count": meta.get("edge_count", len(doc["edges"])),
                    "lint": {
                        "clean": bool(lint_doc.get("clean", False)),
                        "errors": lint_doc.get("summary", {}).get("errors", -1),
                        "warnings": lint_doc.get("summary", {}).get("warnings", -1),
                        "total": lint_doc.get("summary", {}).get("total", -1),
                    },
                    "files": {
                        "reference": str(rel_ref),
                        "lint": str(rel_lint),
                        "mermaid": str(rel_mmd),
                        "svg": str(rel_svg),
                        "payload": str(rel_payload),
                    },
                    "sha256": {
                        "reference": sha256_bytes(export_bytes),
                        "lint": sha256_bytes(lint_bytes),
                        "mermaid": sha256_bytes((dest_root / rel_mmd).read_bytes()),
                        "svg": sha256_bytes((dest_root / rel_svg).read_bytes()),
                        "payload": sha256_bytes(export_bytes),
                    },
                }
            )
        print(f"case {case}: {meta.get('node_count')} nodes / {meta.get('edge_count')} edges — ok")

    index = {
        "schema": "fluxion-topology-index/1.0",
        "generated_by": "scripts/generate_topology_diagrams.py",
        "generator_note": GENERATOR_STAMP,
        "cases": entries,
    }
    (ref_dir / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (docs_dir / "index.md").write_text(render_docs_index(entries), encoding="utf-8")
    print(f"wrote {len(entries)} case artifact sets + index under {dest_root}")
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Automated topology diagram extraction (issue #3966): regenerate "
        "reference topologies, lint reports, Mermaid/SVG diagrams, and viewer payloads."
    )
    parser.add_argument(
        "--dest",
        default=str(REPO_ROOT),
        help="root directory to write artifacts under (default: repo root)",
    )
    parser.add_argument("--fluxion", default=None, help="explicit fluxion CLI binary path")
    args = parser.parse_args(argv)
    fluxion_bin = locate_fluxion(args.fluxion)
    return generate(Path(args.dest), fluxion_bin)


if __name__ == "__main__":
    raise SystemExit(main())
