#!/usr/bin/env python3
"""Automated topology diagram extraction — Issue #3966.

Runs ``fluxion topology export`` for every ASHRAE 140 case in the topology
registry and writes deterministic, committed artifacts:

* ``tests/reference_data/topology/case-<N>.json``      — verbatim export bytes
* ``tests/reference_data/topology/lint/case-<N>.lint.json`` — verbatim
  ``topology lint --strict --format json`` bytes
* ``tests/reference_data/topology/index.json``          — machine index
* ``docs/architecture/topology/case-<N>.mmd``           — Mermaid source
* ``docs/architecture/topology/case-<N>.svg``           — dependency-free
  deterministic structural SVG (stdlib layout, no mermaid-cli/node needed)
* ``docs/architecture/topology/payloads/case-<N>.json`` — viewer payloads for
  ``fluxion-tauri/frontend/public/topology-standalone.html?model=<url>``
* ``docs/architecture/topology/index.md``               — human index

Drift is policed by ``scripts/check_topology_drift.py`` (wired into
``.github/workflows/topology_visualizer.yml``). Output is byte-deterministic:
no timestamps, no tool versions, no environment-derived data.

Usage:
    python3 scripts/generate_topology_diagrams.py [--dest REPO_ROOT] [--fluxion BIN]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# ASHRAE 140 cases registered in the topology export CLI (issue #3963).
TOPOLOGY_CASES = ["600", "610", "620", "630", "640", "650", "900", "960"]

GENERATOR_STAMP = (
    "Generated by scripts/generate_topology_diagrams.py — do not hand-edit. "
    "Drift-gated by scripts/check_topology_drift.py (issue #3966); "
    "regenerate with `python3 scripts/generate_topology_diagrams.py`."
)

REFERENCE_DIR = Path("tests/reference_data/topology")
LINT_DIR = REFERENCE_DIR / "lint"
DOCS_DIR = Path("docs/architecture/topology")
PAYLOAD_DIR = DOCS_DIR / "payloads"

# Deterministic layout: node kind -> column slot (left-to-right thermal flow).
# Surface columns split per-zone for large graphs (issue #4037).
KIND_COLORS = {
    "outdoor_ambient": "#38bdf8",
    "boundary": "#78716c",
    "exterior_surface": "#f97316",
    "wall_layer": "#a16207",
    "interior_surface": "#fbbf24",
    "zone_air": "#ef4444",
    "internal_mass": "#eab308",
    "hvac_terminal": "#14b8a6",
    "internal_gain": "#a855f7",
}
DEFAULT_NODE_COLOR = "#64748b"

# Declared semantic edge-color mapping (issue #4038). Every color is chosen
# outside the node-kind palette so node fills and edge strokes never imply a
# false relationship.
EDGE_COLORS = {
    "conduction": "#1f77b4",
    "convection_exterior": "#17becf",
    "convection_interior": "#2ca02c",
    "longwave_radiation": "#9467bd",
    "shortwave_solar_direct": "#e377c2",
    "shortwave_solar_diffuse": "#bcbd22",
    "air_exchange": "#7f7f7f",
    "internal_gain_split": "#aec7e8",
    "hvac_sensible": "#98df8a",
    "ground_conduction": "#8c564b",
}
# Fallback for coupling types not in EDGE_COLORS (also node-palette-free).
EDGE_FALLBACK_PALETTE = ["#393b79", "#637939", "#8c6d31", "#843c39", "#7b4173"]

BOX_W, BOX_H = 170, 40
PITCH_X, PITCH_Y = 230, 54
MARGIN_X, MARGIN_TOP = 40, 64


def locate_fluxion(explicit: str | None) -> str:
    """Resolve the fluxion CLI path.

    Order: --fluxion / $FLUXION_BIN override, then target/debug, then
    target/release. A stale release binary predating the topology subcommand
    (hazard observed 2026-09-21) is rejected by the support probe.
    """
    candidates = []
    if explicit:
        candidates.append(explicit)
    import os

    env_bin = os.environ.get("FLUXION_BIN")
    if env_bin:
        candidates.append(env_bin)
    candidates += [str(REPO_ROOT / "target/debug/fluxion"), str(REPO_ROOT / "target/release/fluxion")]
    for cand in candidates:
        if cand and Path(cand).is_file() and os.access(cand, os.X_OK):
            probe = subprocess.run(
                [cand, "topology", "--help"], capture_output=True, check=False
            )
            if probe.returncode == 0:
                return cand
        if explicit and cand == explicit:
            break
    sys.stderr.write(
        "error: no fluxion CLI with `topology` support found; "
        "run `cargo build -p fluxion` or pass --fluxion/FLUXION_BIN\n"
    )
    raise SystemExit(2)


def run_cli(fluxion: str, args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run([fluxion, *args], capture_output=True, text=True, check=False)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def xml_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def edge_color(coupling_type: str) -> str:
    """Declared semantic color for a coupling type (issue #4038)."""
    if coupling_type in EDGE_COLORS:
        return EDGE_COLORS[coupling_type]
    total = 0
    for ch in coupling_type.encode("utf-8"):
        total = (total * 131 + ch) % 1_000_003
    return EDGE_FALLBACK_PALETTE[total % len(EDGE_FALLBACK_PALETTE)]


def case_title(case: str, doc: dict) -> str:
    """Header title without the duplicated case name (issue #4049)."""
    model_name = (doc["metadata"].get("model_name") or "").strip()
    base = f"ASHRAE 140 Case {case}"
    if not model_name or model_name == base or model_name.startswith(base):
        return model_name or base
    return f"{base} — {model_name}"


_LABEL_MAX = 24


def _middle_truncate(label: str) -> str:
    keep = _LABEL_MAX - 1  # room for the ellipsis
    head = (keep + 1) // 2
    tail = keep - head
    return label[:head] + "…" + label[-tail:]


def short_label(name: str) -> list[str]:
    """Issue #4035: abbreviate the Zone prefix; split long labels across two
    lines at a word boundary (never chopping the distinguishing token); only
    middle-truncate as a last resort."""
    label = re.sub(r"^Zone (\d+) ", r"Z\1 ", name)
    if len(label) <= _LABEL_MAX:
        return [label]
    words = label.split(" ")
    best: list[str] | None = None
    for i in range(1, len(words)):
        cand = [" ".join(words[:i]), " ".join(words[i:])]
        if best is None or max(len(c) for c in cand) < max(len(b) for b in best):
            best = cand
    lines = best if best is not None else [label]
    return [_middle_truncate(line) if len(line) > _LABEL_MAX else line for line in lines]


def display_labels(nodes: list[dict]) -> list[list[str]]:
    """Rendered labels (1-2 lines each), asserted unique within the diagram."""
    labels = [short_label(n.get("name", n["id"])) for n in nodes]
    joined = ["\n".join(lines) for lines in labels]
    dupes = sorted({j for j in joined if joined.count(j) > 1})
    if dupes:
        raise ValueError(f"rendered label collision (issue #4035): {dupes}")
    return labels


_MERMAID_SAFE = str.maketrans(
    {
        '"': "'",
        "`": "'",
        "[": "(",
        "]": ")",
        "{": "(",
        "}": ")",
        "|": "/",
    }
)


def sanitize_mermaid_label(text: str) -> str:
    """Issue #4041: neutralize Mermaid-significant characters in flowchart labels."""
    return text.translate(_MERMAID_SAFE)


def augment_boundaries(doc: dict) -> dict:
    """Issue #4036: synthesize boundary-condition nodes for the diagrams.

    Diagram-layer only — the verbatim export bytes (reference + payload JSONs)
    are untouched. Each ground-coupled exterior surface gets a shared
    ``boundary:ground`` node and a ``ground_conduction`` edge so the heat path
    is visible instead of living only in node attributes.
    """
    nodes = list(doc["nodes"])
    edges = list(doc["edges"])
    node_ids = {n["id"] for n in nodes}
    for node in doc["nodes"]:
        attrs = node.get("attributes") or {}
        if node["kind"] == "exterior_surface" and attrs.get("ground_coupled"):
            if "boundary:ground" not in node_ids:
                temp = attrs.get("ground_temperature_c")
                name = (
                    f"Ground ({temp:g} °C)"
                    if isinstance(temp, (int, float))
                    else "Ground"
                )
                nodes.insert(0, {"id": "boundary:ground", "kind": "boundary", "name": name})
                node_ids.add("boundary:ground")
            edges.append(
                {
                    "source_id": "boundary:ground",
                    "target_id": node["id"],
                    "coupling_type": "ground_conduction",
                    "bidirectional": False,
                    "conductance_w_per_k": None,
                    "attributes": {"ground_temperature_c": attrs.get("ground_temperature_c")},
                }
            )
    return {**doc, "nodes": nodes, "edges": edges}


def group_edges(edges: list[dict]) -> list[tuple[tuple, list[dict]]]:
    """Merge parallel identical edges for rendering (issue #4039).

    Groups by (source, target, coupling_type), normalizing direction for
    bidirectional edges since they render as the same curve.
    """
    groups: dict[tuple, list[dict]] = {}
    order: list[tuple] = []
    for edge in edges:
        src, tgt = edge["source_id"], edge["target_id"]
        if edge.get("bidirectional") and tgt < src:
            src, tgt = tgt, src
        key = (src, tgt, edge.get("coupling_type", "coupling"))
        if key not in groups:
            groups[key] = []
            order.append(key)
        groups[key].append(edge)
    return [(key, groups[key]) for key in order]


def edge_stroke_width(conductance: float | None, lo: float, hi: float) -> float:
    """Issue #4043: log-scaled stroke width in [1.2, 5.0]; unknown -> minimum."""
    if not conductance or conductance <= 0 or hi <= lo:
        return 1.2
    t = (math.log10(conductance) - math.log10(lo)) / (math.log10(hi) - math.log10(lo))
    return 1.2 + 3.8 * min(1.0, max(0.0, t))


_ZONE_RE = re.compile(r"^zone-(\d+):")
# Split surface columns per-zone when the wall_layer tower exceeds this many
# rows (issue #4037); case-960 has 34, single-zone cases have <= 17.
_ZONE_SPLIT_THRESHOLD = 20


def _node_zone(node: dict) -> str | None:
    m = _ZONE_RE.match(node["id"])
    return m.group(1) if m else None


def _surface_of(node_id: str, kind: str) -> str:
    if kind == "wall_layer":
        return re.sub(r":layer-\d+$", "", node_id)
    if kind == "exterior_surface":
        return re.sub(r":ext$", "", node_id)
    if kind == "interior_surface":
        return re.sub(r":int$", "", node_id)
    return node_id


def layout_positions(
    nodes: list[dict],
) -> tuple[dict[str, tuple[int, int]], dict[int, float], int, int]:
    """Issue #4037: assign (column, row) per node.

    * Surface columns split per-zone for large graphs (case-960) instead of
      one 34-row tower.
    * Within a column, wall layers are ordered by surface (following the
      exterior-surface order) then layer index, so each conduction chain is
      contiguous and roughly row-aligned with its films.
    * Short columns are vertically centered instead of top-aligned.

    Returns (positions, column_y_offsets, n_columns, max_rows).
    """
    zones = sorted({_node_zone(n) for n in nodes if _node_zone(n)})
    split = (
        sum(1 for n in nodes if n["kind"] == "wall_layer") > _ZONE_SPLIT_THRESHOLD
        and len(zones) > 1
    )

    col_keys: list[tuple] = [("ambient",)]
    if split:
        for z in zones:
            col_keys += [
                (f"zone:{z}", "ext"),
                (f"zone:{z}", "layer"),
                (f"zone:{z}", "int"),
            ]
    else:
        col_keys += [("surface", "ext"), ("surface", "layer"), ("surface", "int")]
    col_keys += [("zone_air",), ("internal_mass",), ("hvac_terminal",), ("internal_gain",)]
    col_index = {k: i for i, k in enumerate(col_keys)}

    slot_of = {
        "exterior_surface": "ext",
        "wall_layer": "layer",
        "interior_surface": "int",
    }

    def key_for(node: dict) -> tuple:
        kind = node["kind"]
        if kind in ("outdoor_ambient", "boundary"):
            return ("ambient",)
        if kind in slot_of:
            if split:
                return (f"zone:{_node_zone(node)}", slot_of[kind])
            return ("surface", slot_of[kind])
        key = (kind,)
        if key not in col_index:  # unknown kinds get trailing columns, first-seen
            col_index[key] = len(col_index)
        return key

    buckets: dict[tuple, list[dict]] = {}
    for node in nodes:
        buckets.setdefault(key_for(node), []).append(node)

    # Surface order follows the exterior-surface columns (zone order, then row).
    surface_order: dict[str, int] = {}
    ordered_cols = sorted(buckets, key=lambda k: col_index[k])
    for key in ordered_cols:
        for node in buckets[key]:
            if node["kind"] == "exterior_surface":
                surface = _surface_of(node["id"], "exterior_surface")
                if surface not in surface_order:
                    surface_order[surface] = len(surface_order)

    def layer_sort_key(node: dict) -> tuple[int, int]:
        m = re.search(r":layer-(\d+)$", node["id"])
        idx = int(m.group(1)) if m else 0
        return (
            surface_order.get(_surface_of(node["id"], "wall_layer"), 10**9),
            idx,
        )

    for key, bucket in buckets.items():
        if any(n["kind"] == "wall_layer" for n in bucket):
            bucket.sort(key=layer_sort_key)

    max_rows = max(len(b) for b in buckets.values()) if buckets else 1
    n_cols = len(col_index)
    pos: dict[str, tuple[int, int]] = {}
    col_yoff: dict[int, float] = {}
    for key in ordered_cols:
        col = col_index[key]
        bucket = buckets[key]
        col_yoff[col] = (max_rows - len(bucket)) * PITCH_Y / 2
        for row, node in enumerate(bucket):
            pos[node["id"]] = (col, row)
    return pos, col_yoff, n_cols, max_rows


def render_mermaid(doc: dict, case: str) -> str:
    title = case_title(case, doc)
    lines = [
        f"%% {GENERATOR_STAMP}",
        f"%% Case {case}: {title}",
        "flowchart LR",
    ]
    for i, node in enumerate(doc["nodes"]):
        label = sanitize_mermaid_label(node.get("name", node["id"]))
        lines.append(f'    n{i}["{label}"]:::{node["kind"]}')
    for edge in doc["edges"]:
        src = _node_index(doc, edge["source_id"])
        tgt = _node_index(doc, edge["target_id"])
        arrow = "<-->" if edge.get("bidirectional") else "-->"
        label = sanitize_mermaid_label(edge.get("coupling_type", "coupling"))
        lines.append(f"    n{src} {arrow}|{label}| n{tgt}")
    for kind in sorted({n["kind"] for n in doc["nodes"]}):
        color = KIND_COLORS.get(kind, DEFAULT_NODE_COLOR)
        lines.append(f"    classDef {kind} fill:{color},stroke:#0f172a,color:#0f172a")
    return "\n".join(lines) + "\n"


def _node_index(doc: dict, node_id: str) -> int:
    for i, node in enumerate(doc["nodes"]):
        if node["id"] == node_id:
            return i
    raise KeyError(f"edge references unknown node {node_id!r}")


def render_svg(doc: dict, case: str) -> str:
    nodes = doc["nodes"]
    edges = doc["edges"]
    title = case_title(case, doc)
    labels = display_labels(nodes)
    label_of = {node["id"]: label for node, label in zip(nodes, labels)}

    pos, col_yoff, n_cols, max_rows = layout_positions(nodes)

    coupling_types = sorted({e.get("coupling_type", "coupling") for e in edges})
    kinds_present = sorted({n["kind"] for n in nodes})
    colors = [edge_color(c) for c in coupling_types]
    color_index = {c: i for i, c in enumerate(colors)}

    legend_h = 28 + 20 * (1 + (len(kinds_present) + len(coupling_types)) // 3 + 1)
    width = MARGIN_X * 2 + PITCH_X * n_cols
    height = MARGIN_TOP + PITCH_Y * max_rows + legend_h + 20

    # Conductance range for log-scaled stroke widths (issue #4043).
    conds = [e.get("conductance_w_per_k") for e in edges]
    conds = [c for c in conds if c and c > 0]
    lo, hi = (min(conds), max(conds)) if conds else (1.0, 1.0)

    aria = f"{title}: {len(nodes)} nodes, {len(edges)} couplings"
    desc = (
        f"Node-link topology diagram of the {title} thermal model. "
        "Edge color encodes coupling type; edge width scales with log "
        "conductance; a ×N badge marks merged parallel edges."
    )
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{width}\" height=\"{height}\" "
            f"viewBox=\"0 0 {width} {height}\" font-family=\"Helvetica,Arial,sans-serif\" "
            f'role="img">'
        ),
        # Issue #4042: accessible name + description on the SVG root.
        f"<title>{xml_escape(aria)}</title>",
        f"<desc>{xml_escape(desc)}</desc>",
        f"<!-- {GENERATOR_STAMP} -->",
        f'<rect width="{width}" height="{height}" fill="#f8fafc"/>',
        (
            f'<text x="{MARGIN_X}" y="28" font-size="17" font-weight="bold" fill="#0f172a">'
            f"{xml_escape(title)}</text>"
        ),
        "<defs>",
    ]
    for i, color in enumerate(colors):
        parts.append(
            f'<marker id="arrow{i}" viewBox="0 0 10 10" refX="10" refY="5" '
            f'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
            f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{color}"/></marker>'
        )
    parts.append("</defs>")

    def node_xy(node_id: str) -> tuple[float, float]:
        col, row = pos[node_id]
        return (
            MARGIN_X + col * PITCH_X,
            MARGIN_TOP + row * PITCH_Y + col_yoff[col],
        )

    # Edges (drawn under the boxes), merged by multiplicity (issue #4039).
    badges: list[str] = []  # drawn after the nodes so they stay on top
    for (src, tgt, ctype), group in group_edges(edges):
        rep = group[0]
        mult = len(group)
        x1, y1 = node_xy(src)
        x1 += BOX_W
        y1 += BOX_H / 2
        x2, y2 = node_xy(tgt)
        y2 += BOX_H / 2
        s_col, t_col = pos[src][0], pos[tgt][0]
        if t_col > s_col:
            mid = (x1 + x2) / 2
            path = f"M {x1:.1f} {y1:.1f} C {mid:.1f} {y1:.1f}, {mid:.1f} {y2:.1f}, {x2:.1f} {y2:.1f}"
        else:
            s_row, t_row = pos[src][1], pos[tgt][1]
            bulge = y1 + (60 if t_row >= s_row else -60)
            mid = (x1 + x2) / 2
            path = (
                f"M {x1:.1f} {y1:.1f} C {mid:.1f} {bulge:.1f}, "
                f"{mid:.1f} {y2:.1f}, {x2:.1f} {y2:.1f}"
            )
        color = edge_color(ctype)
        idx = color_index[color]
        stroke_w = edge_stroke_width(rep.get("conductance_w_per_k"), lo, hi)
        # Issue #4040: double-headed arrows for bidirectional edges.
        marker_start = f' marker-start="url(#arrow{idx})"' if rep.get("bidirectional") else ""
        mult_suffix = f" ×{mult}" if mult > 1 else ""
        edge_title = xml_escape(f"{src} -> {tgt} ({ctype}){mult_suffix}")
        parts.append(
            f'<path d="{path}" fill="none" stroke="{color}" stroke-width="{stroke_w:.2f}" '
            f'opacity="0.75" marker-end="url(#arrow{idx})"{marker_start}>'
            f"<title>{edge_title}</title></path>"
        )
        if mult > 1:
            mx, my = (x1 + x2) / 2, (y1 + y2) / 2
            badges.append(
                f'<g><title>{xml_escape(f"{mult} parallel {ctype} edges")}</title>'
                f'<circle cx="{mx:.1f}" cy="{my:.1f}" r="10" fill="#ffffff" '
                f'stroke="#0f172a" stroke-width="1"/>'
                f'<text x="{mx:.1f}" y="{my + 3.5:.1f}" font-size="10" font-weight="bold" '
                f'text-anchor="middle" fill="#0f172a">×{mult}</text></g>'
            )

    # Nodes.
    for node in nodes:
        x, y = node_xy(node["id"])
        color = KIND_COLORS.get(node["kind"], DEFAULT_NODE_COLOR)
        cx = x + BOX_W / 2
        lines = label_of[node["id"]]
        if len(lines) == 1:
            label_svg = (
                f'<text x="{cx:.1f}" y="{y + BOX_H / 2 + 4:.1f}" font-size="11" '
                f'text-anchor="middle" fill="#0f172a">{xml_escape(lines[0])}</text>'
            )
        else:
            label_svg = "".join(
                f'<text x="{cx:.1f}" y="{y + BOX_H / 2 + dy:.1f}" font-size="11" '
                f'text-anchor="middle" fill="#0f172a">{xml_escape(line)}</text>'
                for line, dy in zip(lines, (-7, 7))
            )
        parts.append(
            f'<g><title>{xml_escape(node["id"] + " (" + node["kind"] + ")")}</title>'
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{BOX_W}" height="{BOX_H}" rx="7" '
            f'fill="{color}" stroke="#0f172a" stroke-width="1"/>'
            f"{label_svg}</g>"
        )

    # Multiplicity badges on top of everything (issue #4039).
    parts.extend(badges)

    # Legend.
    ly = MARGIN_TOP + PITCH_Y * max_rows + 24
    parts.append(
        f'<text x="{MARGIN_X}" y="{ly}" font-size="12" font-weight="bold" fill="#0f172a">'
        "Legend — edge width scales with log conductance</text>"
    )
    lx, ly2 = MARGIN_X, ly + 18
    for kind in kinds_present:
        color = KIND_COLORS.get(kind, DEFAULT_NODE_COLOR)
        parts.append(
            f'<rect x="{lx}" y="{ly2 - 9}" width="12" height="12" rx="3" fill="{color}" stroke="#0f172a"/>'
            f'<text x="{lx + 17}" y="{ly2 + 1}" font-size="11" fill="#0f172a">{xml_escape(kind)}</text>'
        )
        lx += 190
        if lx > width - 200:
            lx, ly2 = MARGIN_X, ly2 + 18
    lx, ly2 = MARGIN_X, ly2 + 20
    for ctype in coupling_types:
        color = edge_color(ctype)
        idx = color_index[color]
        parts.append(
            f'<path d="M {lx} {ly2} L {lx + 26} {ly2}" stroke="{color}" stroke-width="2" '
            f'marker-end="url(#arrow{idx})"/>'
            f'<text x="{lx + 33}" y="{ly2 + 4}" font-size="11" fill="#0f172a">{xml_escape(ctype)}</text>'
        )
        lx += 190
        if lx > width - 200:
            lx, ly2 = MARGIN_X, ly2 + 18
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def render_docs_index(entries: list[dict]) -> str:
    lines = [
        "# Topology Diagrams — Issue #3966",
        "",
        (
            f"Machine-generated ASHRAE 140 topology diagrams (Mermaid + structural SVG) with "
            f"verbatim `fluxion topology export` references, `topology lint --strict` reports, "
            f"and standalone-viewer payloads. {GENERATOR_STAMP}"
        ),
        "",
        (
            "Each case row links the committed artifacts; the reference JSONs under "
            "`tests/reference_data/topology/` are the drift-gated source of truth."
        ),
        "",
        (
            "Open the viewer at `fluxion-tauri/frontend/public/topology-standalone.html` and load a "
            "payload via `?model=` or drag-and-drop (issue #3965)."
        ),
        "",
        "| Case | Model | Nodes | Couplings | Lint (strict) | Mermaid | SVG | Viewer payload |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        lint = e["lint"]
        lint_cell = "✅ clean" if lint["clean"] else f"❌ {lint['errors']} err / {lint['warnings']} warn"
        lines.append(
            f"| {e['case']} | {e['model_name']} | {e['node_count']} | {e['edge_count']} | "
            f"{lint_cell} | [case-{e['case']}.mmd](case-{e['case']}.mmd) | "
            f"[case-{e['case']}.svg](case-{e['case']}.svg) | "
            f"[payloads/case-{e['case']}.json](payloads/case-{e['case']}.json) |"
        )
    lines += [
        "",
        "## How to regenerate",
        "",
        "```bash",
        "cargo build -p fluxion   # debug build is what the drift gate uses",
        "python3 scripts/generate_topology_diagrams.py",
        "python3 scripts/check_topology_drift.py   # must exit 0 before you commit",
        "```",
        "",
        (
            "The drift gate (`scripts/check_topology_drift.py`, wired into "
            "`.github/workflows/topology_visualizer.yml`) regenerates everything into a temp "
            "directory and byte-compares it against the committed tree; any physics change that "
            "alters the topology graph requires regenerating and committing these artifacts in "
            "the same PR."
        ),
        "",
    ]
    return "\n".join(lines)


def generate(dest_root: Path, fluxion_bin: str) -> int:
    dest_root = dest_root.resolve()
    ref_dir = dest_root / REFERENCE_DIR
    lint_dir = dest_root / LINT_DIR
    docs_dir = dest_root / DOCS_DIR
    payload_dir = dest_root / PAYLOAD_DIR
    for d in (ref_dir, lint_dir, docs_dir, payload_dir):
        d.mkdir(parents=True, exist_ok=True)

    entries: list[dict] = []
    failures = 0
    for case in TOPOLOGY_CASES:
        with tempfile.TemporaryDirectory() as td:
            tmp_export = Path(td) / f"case-{case}.json"
            export = run_cli(fluxion_bin, ["topology", "export", "--case", case, "--output", str(tmp_export)])
            if export.returncode != 0 or not tmp_export.is_file():
                sys.stderr.write(f"error: topology export failed for case {case}: {export.stderr}\n")
                failures += 1
                continue
            export_bytes = tmp_export.read_bytes()
            lint = run_cli(fluxion_bin, ["topology", "lint", "--case", case, "--strict", "--format", "json"])
            if lint.returncode != 0:
                sys.stderr.write(
                    f"error: topology lint --strict failed for case {case} "
                    f"(exit {lint.returncode}): {lint.stdout}{lint.stderr}\n"
                )
                failures += 1
            lint_bytes = lint.stdout.encode("utf-8")
            doc = json.loads(export_bytes.decode("utf-8"))
            # Diagram-layer augmentation (issue #4036): boundary-condition nodes
            # appear in the Mermaid/SVG diagrams only; the reference and payload
            # JSONs below stay byte-verbatim exports.
            diagram_doc = augment_boundaries(doc)

            rel_ref = REFERENCE_DIR / f"case-{case}.json"
            rel_lint = LINT_DIR / f"case-{case}.lint.json"
            rel_mmd = DOCS_DIR / f"case-{case}.mmd"
            rel_svg = DOCS_DIR / f"case-{case}.svg"
            rel_payload = PAYLOAD_DIR / f"case-{case}.json"
            (dest_root / rel_ref).write_bytes(export_bytes)
            (dest_root / rel_lint).write_bytes(lint_bytes)
            (dest_root / rel_mmd).write_text(render_mermaid(diagram_doc, case), encoding="utf-8")
            (dest_root / rel_svg).write_text(render_svg(diagram_doc, case), encoding="utf-8")
            (dest_root / rel_payload).write_bytes(export_bytes)

            try:
                lint_doc = json.loads(lint.stdout)
            except json.JSONDecodeError:
                lint_doc = {"clean": False, "summary": {"errors": -1, "warnings": -1, "total": -1}}
            meta = doc["metadata"]
            entries.append(
                {
                    "case": case,
                    "model_name": meta.get("model_name", ""),
                    "model_source": meta.get("model_source", ""),
                    "node_count": meta.get("node_count", len(doc["nodes"])),
                    "edge_count": meta.get("edge_count", len(doc["edges"])),
                    "lint": {
                        "clean": bool(lint_doc.get("clean", False)),
                        "errors": lint_doc.get("summary", {}).get("errors", -1),
                        "warnings": lint_doc.get("summary", {}).get("warnings", -1),
                        "total": lint_doc.get("summary", {}).get("total", -1),
                    },
                    "files": {
                        "reference": str(rel_ref),
                        "lint": str(rel_lint),
                        "mermaid": str(rel_mmd),
                        "svg": str(rel_svg),
                        "payload": str(rel_payload),
                    },
                    "sha256": {
                        "reference": sha256_bytes(export_bytes),
                        "lint": sha256_bytes(lint_bytes),
                        "mermaid": sha256_bytes((dest_root / rel_mmd).read_bytes()),
                        "svg": sha256_bytes((dest_root / rel_svg).read_bytes()),
                        "payload": sha256_bytes(export_bytes),
                    },
                }
            )
        print(f"case {case}: {meta.get('node_count')} nodes / {meta.get('edge_count')} edges — ok")

    index = {
        "schema": "fluxion-topology-index/1.0",
        "generated_by": "scripts/generate_topology_diagrams.py",
        "generator_note": GENERATOR_STAMP,
        "cases": entries,
    }
    (ref_dir / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (docs_dir / "index.md").write_text(render_docs_index(entries), encoding="utf-8")
    print(f"wrote {len(entries)} case artifact sets + index under {dest_root}")
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Automated topology diagram extraction (issue #3966): regenerate "
        "reference topologies, lint reports, Mermaid/SVG diagrams, and viewer payloads."
    )
    parser.add_argument(
        "--dest",
        default=str(REPO_ROOT),
        help="root directory to write artifacts under (default: repo root)",
    )
    parser.add_argument("--fluxion", default=None, help="explicit fluxion CLI binary path")
    args = parser.parse_args(argv)
    fluxion_bin = locate_fluxion(args.fluxion)
    return generate(Path(args.dest), fluxion_bin)


if __name__ == "__main__":
    raise SystemExit(main())
