//! Thermal Model Data - newtype data container
//!
//! This module contains ThermalModelData which holds all the thermal model state.
//! The ThermalModel wrapper provides Deref to access ThermalModelData fields.

use crate::physics::cta::{ContinuousTensor, VectorField};
use crate::physics::ctf_coefficients::CTFCoefficients;
use crate::physics::ctf_solver::CTFSolver;
use crate::physics::ctf_zone_coupling::CtfZoneCouplingSolver;
use crate::physics::fd_solver::ImplicitFDSolver;
use crate::physics::multi_node_solver::MultiNodeSolver;
use crate::physics::solver_manager::SolverManager;
use crate::sim::adaptive_timestep::TimestepMode;
use crate::sim::boundary::GroundTemperature;
use crate::sim::construction::WallSurface;
use crate::sim::hvac::{
    AnyEquipment, CyclingTracker, EconomizerMode, IdealLoadsSystem, PredictiveController,
};
use crate::sim::hvac_controller::{HvacSystemMode, IdealHVACController};
use crate::sim::occupancy::BuildingType;
use crate::sim::schedule::DailySchedule;
use crate::sim::solar::WindowProperties;
use crate::sim::thermal_model_core::DoorGeometry;
use crate::testing::integration::wiring::WiringTracer;
use crate::validation::ashrae_140_cases::{NightVentilation, Orientation};
use crate::validation::diagnostics::SimulationDiagnostics;
use crate::weather::HourlyWeatherData;
use std::sync::Arc;

pub struct ThermalModelData<T: ContinuousTensor<f64> + Clone> {
    pub num_zones: usize,
    pub temperatures: T,
    pub loads: T,
    pub solar_gains: T,
    pub opaque_solar_gains: T,
    pub surfaces: Vec<Vec<WallSurface>>,
    pub window_u_value: f64,
    pub heating_setpoint: f64,
    pub cooling_setpoint: f64,
    pub heating_setpoints: T,
    pub cooling_setpoints: T,
    pub hvac_enabled: T,
    pub heating_schedule: DailySchedule,
    pub cooling_schedule: DailySchedule,
    pub hvac_heating_capacity: f64,
    pub hvac_cooling_capacity: f64,
    pub hvac_controller: IdealHVACController,
    pub predictive_controller: PredictiveController,
    pub cycling_tracker: CyclingTracker,
    pub economizer_mode: EconomizerMode,
    pub previous_temperatures: VectorField,
    pub hvac_equipment: Option<AnyEquipment>,
    pub zone_area: T,
    pub ceiling_height: T,
    pub air_density: T,
    pub heat_capacity: T,
    pub window_ratio: T,
    pub aspect_ratio: T,
    pub infiltration_rate: T,
    pub wall_u_value: f64,
    pub roof_u_value: f64,
    pub floor_u_value: f64,
    pub case_id: String,
    pub building_type: BuildingType,
    pub thermal_model_type: crate::sim::thermal_model_core::ThermalModelType,
    pub timestep_mode: TimestepMode,
    pub mass_temperatures: T,
    pub thermal_capacitance: T,
    pub envelope_mass_temperatures: T,
    pub internal_mass_temperatures: T,
    pub envelope_thermal_capacitance: T,
    pub internal_thermal_capacitance: T,
    pub h_tr_me: T,
    pub ceiling_mass_temperatures: Option<T>,
    pub floor_mass_temperatures: Option<T>,
    pub partition_mass_temperatures: Option<T>,
    pub ceiling_thermal_capacitance: Option<T>,
    pub floor_thermal_capacitance: Option<T>,
    pub partition_thermal_capacitance: Option<T>,
    pub h_tr_ceiling: Option<T>,
    pub h_tr_floor_mass: Option<T>,
    pub h_tr_partition: Option<T>,
    pub tracer: Option<Arc<WiringTracer>>,
    pub h_tr_em: T,
    pub h_tr_ms: T,
    pub h_tr_is: T,
    /// h_tr_is excluding south wall contribution (for south wall bypass fix, Issue #715)
    pub h_tr_is_no_south: T,
    /// South wall's h_tr_em for series path computation (Issue #715)
    pub h_tr_em_south: T,
    pub h_tr_w: T,
    pub h_ve: T,
    pub h_tr_floor: T,
    pub ground_temperature: Box<dyn GroundTemperature>,
    pub h_tr_iz: T,
    pub h_tr_iz_rad: T,
    pub surface_emissivity: T,
    pub zone_volume: T,
    pub common_wall_area: f64,
    pub hvac_system_mode: HvacSystemMode,
    pub night_ventilation: Option<NightVentilation>,
    pub h_vent_mass: f64,
    pub thermal_bridge_coefficient: f64,
    pub ideal_air_loads_mode: bool,
    pub ideal_loads_system: Vec<Option<IdealLoadsSystem>>,
    pub free_float: bool, // When true, HVAC output is forced to zero (for free-floating cases)
    pub ctf_coefficients: Option<CTFCoefficients>,
    pub ctf_solvers: Vec<CTFSolver>,
    pub ctf_enabled: bool,
    pub ctf_timestep: f64,
    pub ctf_zone_coupling_solver: Option<CtfZoneCouplingSolver>,
    pub ctf_primary: bool,
    pub fd_solvers: Vec<ImplicitFDSolver>,
    pub fd_enabled: bool,
    pub fd_timestep: f64,
    pub multi_node_solvers: Vec<MultiNodeSolver>,
    pub solver_manager: Option<SolverManager>,
    pub convective_fraction: f64,
    pub solar_distribution_to_air: f64,
    pub solar_beam_to_mass_fraction: f64,
    pub thermal_mass_coupling_enhancement: f64,
    pub time_constant_sensitivity_correction: f64,
    pub cooling_sensitivity_correction: f64,
    pub time_constant_sensitivity_correction_6r2c: f64,
    pub cooling_sensitivity_correction_6r2c: f64,
    pub previous_mass_temperatures: T,
    pub mass_energy_change_cumulative: f64,
    pub envelope_mass_energy_change_cumulative: f64,
    pub internal_mass_energy_change_cumulative: f64,
    pub peak_power_heating: f64,
    pub peak_power_cooling: f64,
    pub annual_heating_energy: f64,
    pub annual_cooling_energy: f64,
    pub ctf_annual_heating_joules: f64,
    pub ctf_annual_cooling_joules: f64,
    pub fd_annual_heating_joules: f64,
    pub fd_annual_cooling_joules: f64,
    pub annual_electrical_energy: f64,
    pub weather: Option<HourlyWeatherData>,
    pub latitude_deg: f64,
    pub longitude_deg: f64,
    pub window_properties: Vec<WindowProperties>,
    pub window_orientations: Vec<Vec<Orientation>>,
    pub door_geometry: DoorGeometry,
    pub derived_h_ext: T,
    pub derived_term_rest_1: T,
    pub derived_h_ms_is_prod: T,
    pub derived_den: T,
    pub derived_sensitivity: T,
    pub derived_ground_coeff: T,
    pub diagnostics: Option<SimulationDiagnostics>,
    pub current_hvac_output: Option<T>,
    pub internal_radiative_to_mass: f64,
    // Per-surface thermal mass conductances for 9R4C model (Issue #715, Phase 6B)
    pub h_tr_ms_wall: Option<T>,
    pub h_tr_ms_roof: Option<T>,
    pub h_tr_ms_floor: Option<T>,
    pub h_tr_em_wall: Option<T>,
    pub h_tr_em_roof: Option<T>,
    pub h_tr_em_floor: Option<T>,
    // Per-surface thermal capacitances for 9R4C model
    pub cm_wall: Option<T>,
    pub cm_roof: Option<T>,
    pub cm_floor: Option<T>,
    pub cm_internal: Option<T>,
    // Multi-node thermal mass state for 9R4C model
    pub multi_node_thermal_mass: Option<crate::sim::multi_node_thermal::MultiNodeThermalMass>,
    /// PR #821 / Issue #825 — most recent zone-0 phi_ia (W to air node) computed
    /// inside `step_physics_5r1c`. Captured for the `pr821-diag` CSV writer so
    /// the heat-balance terms can be inspected hour by hour. Always 0.0 when
    /// the `pr821-diag` feature is disabled (and the field does not exist).
    #[cfg(feature = "pr821-diag")]
    pub last_phi_ia: f64,
    /// PR #821 / Issue #825 — most recent zone-0 phi_st (W to surface node).
    #[cfg(feature = "pr821-diag")]
    pub last_phi_st: f64,
    /// PR #821 / Issue #825 — most recent zone-0 phi_m (W to mass node).
    #[cfg(feature = "pr821-diag")]
    pub last_phi_m: f64,
}

impl<T: ContinuousTensor<f64> + Clone> Clone for ThermalModelData<T> {
    fn clone(&self) -> Self {
        Self {
            num_zones: self.num_zones,
            temperatures: self.temperatures.clone(),
            loads: self.loads.clone(),
            solar_gains: self.solar_gains.clone(),
            opaque_solar_gains: self.opaque_solar_gains.clone(),
            surfaces: self.surfaces.clone(),
            window_u_value: self.window_u_value,
            heating_setpoint: self.heating_setpoint,
            cooling_setpoint: self.cooling_setpoint,
            heating_setpoints: self.heating_setpoints.clone(),
            cooling_setpoints: self.cooling_setpoints.clone(),
            hvac_enabled: self.hvac_enabled.clone(),
            heating_schedule: self.heating_schedule.clone(),
            cooling_schedule: self.cooling_schedule.clone(),
            hvac_heating_capacity: self.hvac_heating_capacity,
            hvac_cooling_capacity: self.hvac_cooling_capacity,
            hvac_controller: self.hvac_controller.clone(),
            predictive_controller: self.predictive_controller.clone(),
            cycling_tracker: self.cycling_tracker.clone(),
            economizer_mode: self.economizer_mode,
            previous_temperatures: self.previous_temperatures.clone(),
            hvac_equipment: self.hvac_equipment.clone(),
            zone_area: self.zone_area.clone(),
            ceiling_height: self.ceiling_height.clone(),
            air_density: self.air_density.clone(),
            heat_capacity: self.heat_capacity.clone(),
            window_ratio: self.window_ratio.clone(),
            aspect_ratio: self.aspect_ratio.clone(),
            infiltration_rate: self.infiltration_rate.clone(),
            wall_u_value: self.wall_u_value,
            roof_u_value: self.roof_u_value,
            floor_u_value: self.floor_u_value,
            case_id: self.case_id.clone(),
            building_type: self.building_type,
            thermal_model_type: self.thermal_model_type,
            timestep_mode: self.timestep_mode.clone(),
            mass_temperatures: self.mass_temperatures.clone(),
            thermal_capacitance: self.thermal_capacitance.clone(),
            envelope_mass_temperatures: self.envelope_mass_temperatures.clone(),
            internal_mass_temperatures: self.internal_mass_temperatures.clone(),
            envelope_thermal_capacitance: self.envelope_thermal_capacitance.clone(),
            internal_thermal_capacitance: self.internal_thermal_capacitance.clone(),
            h_tr_me: self.h_tr_me.clone(),
            ceiling_mass_temperatures: self.ceiling_mass_temperatures.clone(),
            floor_mass_temperatures: self.floor_mass_temperatures.clone(),
            partition_mass_temperatures: self.partition_mass_temperatures.clone(),
            ceiling_thermal_capacitance: self.ceiling_thermal_capacitance.clone(),
            floor_thermal_capacitance: self.floor_thermal_capacitance.clone(),
            partition_thermal_capacitance: self.partition_thermal_capacitance.clone(),
            h_tr_ceiling: self.h_tr_ceiling.clone(),
            h_tr_floor_mass: self.h_tr_floor_mass.clone(),
            h_tr_partition: self.h_tr_partition.clone(),
            tracer: self.tracer.clone(),
            h_tr_em: self.h_tr_em.clone(),
            h_tr_ms: self.h_tr_ms.clone(),
            h_tr_is: self.h_tr_is.clone(),
            h_tr_is_no_south: self.h_tr_is_no_south.clone(),
            h_tr_em_south: self.h_tr_em_south.clone(),
            h_tr_w: self.h_tr_w.clone(),
            h_ve: self.h_ve.clone(),
            h_tr_floor: self.h_tr_floor.clone(),
            ground_temperature: self.ground_temperature.clone_box(),
            h_tr_iz: self.h_tr_iz.clone(),
            h_tr_iz_rad: self.h_tr_iz_rad.clone(),
            surface_emissivity: self.surface_emissivity.clone(),
            zone_volume: self.zone_volume.clone(),
            common_wall_area: self.common_wall_area,
            hvac_system_mode: self.hvac_system_mode,
            night_ventilation: self.night_ventilation,
            h_vent_mass: self.h_vent_mass,
            thermal_bridge_coefficient: self.thermal_bridge_coefficient,
            ideal_air_loads_mode: self.ideal_air_loads_mode,
            ideal_loads_system: self.ideal_loads_system.clone(),
            free_float: self.free_float,
            ctf_coefficients: self.ctf_coefficients.clone(),
            ctf_solvers: self.ctf_solvers.clone(),
            ctf_enabled: self.ctf_enabled,
            ctf_timestep: self.ctf_timestep,
            ctf_zone_coupling_solver: self.ctf_zone_coupling_solver.clone(),
            ctf_primary: self.ctf_primary,
            fd_solvers: vec![],
            fd_enabled: self.fd_enabled,
            fd_timestep: self.fd_timestep,
            multi_node_solvers: vec![],
            solver_manager: None,
            convective_fraction: self.convective_fraction,
            solar_distribution_to_air: self.solar_distribution_to_air,
            solar_beam_to_mass_fraction: self.solar_beam_to_mass_fraction,
            thermal_mass_coupling_enhancement: self.thermal_mass_coupling_enhancement,
            time_constant_sensitivity_correction: self.time_constant_sensitivity_correction,
            cooling_sensitivity_correction: self.cooling_sensitivity_correction,
            time_constant_sensitivity_correction_6r2c: self
                .time_constant_sensitivity_correction_6r2c,
            cooling_sensitivity_correction_6r2c: self.cooling_sensitivity_correction_6r2c,
            previous_mass_temperatures: self.previous_mass_temperatures.clone(),
            mass_energy_change_cumulative: self.mass_energy_change_cumulative,
            envelope_mass_energy_change_cumulative: self.envelope_mass_energy_change_cumulative,
            internal_mass_energy_change_cumulative: self.internal_mass_energy_change_cumulative,
            peak_power_heating: self.peak_power_heating,
            peak_power_cooling: self.peak_power_cooling,
            annual_heating_energy: self.annual_heating_energy,
            annual_cooling_energy: self.annual_cooling_energy,
            ctf_annual_heating_joules: self.ctf_annual_heating_joules,
            ctf_annual_cooling_joules: self.ctf_annual_cooling_joules,
            fd_annual_heating_joules: self.fd_annual_heating_joules,
            fd_annual_cooling_joules: self.fd_annual_cooling_joules,
            annual_electrical_energy: self.annual_electrical_energy,
            weather: self.weather.clone(),
            latitude_deg: self.latitude_deg,
            longitude_deg: self.longitude_deg,
            window_properties: self.window_properties.clone(),
            window_orientations: self.window_orientations.clone(),
            door_geometry: self.door_geometry,
            derived_h_ext: self.derived_h_ext.clone(),
            derived_term_rest_1: self.derived_term_rest_1.clone(),
            derived_h_ms_is_prod: self.derived_h_ms_is_prod.clone(),
            derived_den: self.derived_den.clone(),
            derived_sensitivity: self.derived_sensitivity.clone(),
            derived_ground_coeff: self.derived_ground_coeff.clone(),
            diagnostics: None,
            current_hvac_output: self.current_hvac_output.clone(),
            internal_radiative_to_mass: self.internal_radiative_to_mass,
            h_tr_ms_wall: self.h_tr_ms_wall.clone(),
            h_tr_ms_roof: self.h_tr_ms_roof.clone(),
            h_tr_ms_floor: self.h_tr_ms_floor.clone(),
            h_tr_em_wall: self.h_tr_em_wall.clone(),
            h_tr_em_roof: self.h_tr_em_roof.clone(),
            h_tr_em_floor: self.h_tr_em_floor.clone(),
            cm_wall: self.cm_wall.clone(),
            cm_roof: self.cm_roof.clone(),
            cm_floor: self.cm_floor.clone(),
            cm_internal: self.cm_internal.clone(),
            multi_node_thermal_mass: self.multi_node_thermal_mass.clone(),
            #[cfg(feature = "pr821-diag")]
            last_phi_ia: self.last_phi_ia,
            #[cfg(feature = "pr821-diag")]
            last_phi_st: self.last_phi_st,
            #[cfg(feature = "pr821-diag")]
            last_phi_m: self.last_phi_m,
        }
    }
}
