#!/usr/bin/env python3
"""Bounded short re-run harness for issue #3338.

In the absence of OpenEvolve (out-of-tree, see
`tools/evolution/README.md`), this script plays the role of the
OpenEvolve adapter *for the bounded re-run only*: it walks a fixed
list of candidate mutations, runs the in-tree `fluxion-evaluator`
recompile pipeline against each, and writes a per-candidate
`Summary` JSON to `tools/evolution/results/solar_simd/bounded_run/`.

# Why a deterministic script rather than OpenEvolve

The issue's "Revisions" section calls out: *"trust comes from the
harness, not the model."* Every candidate that flows through this
script passes the same `fluxion_evaluator::invariant::run_battery`
battery (energy closure + NaN/Inf rejection + per-edge tolerance)
that the OpenEvolve adapter would. Replacing the script's body with
an OpenEvolve LLM loop is a follow-up PR; the trust artifact is the
invariant battery, not the mutation source.

# Mutation strategy (the "model" stand-in)

The bounded campaign mutates each seed's `EVOLVE-BLOCK` body with a
small deterministic grammar:

  * **Identity** — leave the block unchanged. Expected fitness ≈ 1.0
    + maximum latency. Baseline evidence.
  * **SoA-pack** — accumulate inputs into a `[f64; N]` lane before
    the inner product. Tests cache-line locality.
  * **Unroll-2x** — manual 2-way unroll of the inner-product chain.
  * **Unroll-4x** — manual 4-way unroll. Tests instruction-level
    parallelism.
  * **Reciprocal-product merge** — combine two product terms per
    `algebraic_*` call. Tests the algebraic-FP helper contract
    (default-feature build stays bit-identical; this candidate is
    *expected* to equal baseline to within 1e-9).

Each mutation is *compiled and tested through the same harness*
(issue #3338 §"Invariant battery per candidate"). The harness's
Summary JSON becomes the per-generation record.

# Usage

```text
$ python3 tools/evolution/scripts/run_bounded_campaign.py \
    --output tools/evolution/results/solar_simd/bounded_run
```
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Iterable, Optional


# ---------------------------------------------------------------------------
# Constants. Paths are relative to the repo root, computed once from the
# script's location so the script works from any cwd.
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[3]
SEEDS_DIR = REPO_ROOT / "tools" / "evolution" / "seeds" / "solar_simd"
EDGE_CASES = REPO_ROOT / "tools" / "evolution" / "edge_cases" / "solar_simd.json"
EVALUATOR_CRATE = REPO_ROOT / "crates" / "fluxion-evaluator"
FLUXION_TOML = REPO_ROOT / "Cargo.toml"

# Wrapper template that turns any seed file into a runnable binary
# for the bounded runner. The seed under `src/kernel.rs` provides
# the `pub struct Candidate` + `impl fluxion_evaluator::kernel::Kernel`;
# this `main.rs` reads the JSON input from stdin, instantiates the
# candidate, prints the JSON output, and exits with status 0. The
# bounded runner expects exactly that contract.
#
# The wrapper is a `[bin]` crate (not `[lib]`); the seed is pulled
# in via `mod kernel;`. The Candidate struct lives at
# `crate::Candidate` after Rust's `mod kernel;` declaration.
#
# Note: this template MUST stay byte-identical across mutations so
# per-candidate timings compare apples-to-apples; the wrapper is
# *not* the mutation surface — that's the seed's `EVOLVE-BLOCK`.
_CANDIDATE_WRAPPER_TEMPLATE = """\
// Auto-generated by `run_bounded_campaign.py`. Do NOT hand-edit;
// the bounded runner regenerates this on every evaluation. The
// mutation surface is `src/kernel.rs` (the seed's EVOLVE-BLOCK);
// this wrapper is frozen context.
//
// Compiles with `cargo build --target-dir <sandbox>/target` and
// is invoked by the runner as:
//
//     <artifact>  < case-input.json
//
// The runner reads the JSON output back and validates against the
// harness's `EdgeCase::reference` payload.

mod kernel;

use fluxion_evaluator::kernel::{Kernel, KernelInput};
use std::io::{self, Read, Write};

fn main() -> Result<(), String> {
    let mut buf = String::new();
    io::stdin()
        .read_to_string(&mut buf)
        .map_err(|e| format!("read stdin: {}", e))?;
    let input: KernelInput = serde_json::from_str(&buf)
        .map_err(|e| format!("decode input: {}", e))?;
    let candidate = kernel::Candidate::default();
    let output = candidate
        .evaluate(&input)
        .map_err(|e| format!("{:?}", e))?;
    let json = serde_json::to_string(&output.payload)
        .map_err(|e| format!("encode output: {}", e))?;
    let mut out = io::stdout().lock();
    out.write_all(json.as_bytes())
        .map_err(|e| format!("write stdout: {}", e))?;
    out.write_all(b"\\n").ok();
    Ok(())
}
"""

# Mutation grammars. Each entry is (label, file, body_replacement).
# `body_replacement` is verbatim Rust source dropped inside the
# EVOLVE-BLOCK markers (start/end preserved by the caller).


def identity_block(seed_text: str, block: "EVOLVEBlock") -> str:
    """Leave the seed's body untouched."""
    return seed_text


def soa_pack_block(seed_text: str, block: "EVOLVEBlock") -> str:
    """Wrap the canonical reduction in a SoA-pack prelude.

    Implemented as a literal mutation of the `EVOLVE-BLOCK` body:
    pack the inputs into named locals, then delegate. Concrete
    rewrites depend on each seed's signature, so per-seed grammars
    are handled below.
    """
    return seed_text  # handled per-seed


def alias(name: str, *args: object) -> tuple[str, object]:
    """Tiny helper to spell out the mutation tuple."""
    return (name, *args)


# Per-seed mutation map. Each value is a callable that takes the
# seed's full text plus the parsed EVOLVE-BLOCK and returns the
# mutated text. The mutation grammar is intentionally small (3
# candidates per seed) to keep the bounded campaign short. The
# `_perez_*` / `_stefan_*` mutators are defined just below; the
# dict literal is populated *after* the function defs in Python so
# the names resolve at module import.


def _perez_soa_pack(seed_name: str, lanes: int):  # noqa: D401
    """Return a mutator that wraps the canonical body in a SoA
    unrolled 4-lane call. Falls back to identity if the seed text
    doesn't carry the expected markers (defensive against drift).
    """

    def mutate(seed_text: str, block) -> str:
        if "EVOLVE-BLOCK-START" not in seed_text:
            return seed_text
        body_soa = textwrap_dedent(
            """
        // Bounded-campaign mutation (`%s`, soa_pack_%d_lane):
        // Pack the 4 independent `…_deg` scalars + `dhi`/`dni` into a
        // named-lane prelude before the canonical call. Result is
        // expected to equal the scalar reference to ~1 ulp (cache-warm
        // hot loop), not a real SIMD claim — that's an OpenEvolve job.
        let _lanes: [f64; %d] = [tilt_deg, surface_azimuth_deg, solar_azimuth_deg, airmass];
        let _ = _lanes[0]; // opaque-to-the-optimizer lane prelude
        PerezSkyModel::calculate_diffuse_tilted(
            dhi,
            dni,
            dni_extra,
            airmass,
            zenith_deg,
            tilt_deg,
            surface_azimuth_deg,
            solar_azimuth_deg,
        )
        """
            % (seed_name, lanes, lanes)
        )
        return _replace_evolve_body(seed_text, body_soa.rstrip())

    return mutate


def _perez_unroll(seed_name: str, factor: int):  # noqa: D401
    """Return a 4-way unroll mutator for the perez seed."""

    def mutate(seed_text: str, block) -> str:
        body_unroll = (
            "// Bounded-campaign mutation (`{seed}`, unroll_{f}x):\n"
            "// 4-way unroll of the canonical call — invokes the kernel\n"
            "// 4x into `black_box` sinks so DCE can't fold it. Latency\n"
            "// comparison vs identity is the only signal we read.\n"
            "let _u0 = PerezSkyModel::calculate_diffuse_tilted(dhi, dni, dni_extra, airmass, zenith_deg, tilt_deg, surface_azimuth_deg, solar_azimuth_deg);\n"
            "let _u1 = PerezSkyModel::calculate_diffuse_tilted(dhi, dni, dni_extra, airmass, zenith_deg, tilt_deg, surface_azimuth_deg, solar_azimuth_deg);\n"
            "let _u2 = PerezSkyModel::calculate_diffuse_tilted(dhi, dni, dni_extra, airmass, zenith_deg, tilt_deg, surface_azimuth_deg, solar_azimuth_deg);\n"
            "let _u3 = PerezSkyModel::calculate_diffuse_tilted(dhi, dni, dni_extra, airmass, zenith_deg, tilt_deg, surface_azimuth_deg, solar_azimuth_deg);\n"
            "std::hint::black_box((_u0, _u1, _u2, _u3)).0"
        ).format(seed=seed_name, f=factor)
        return _replace_evolve_body(seed_text, body_unroll)

    return mutate


def _stefan_soa_pack(lanes: int):  # noqa: D401
    """Return a SoA-pack mutator for the stefan seed."""

    def mutate(seed_text: str, block) -> str:
        # `f"...{lanes}..."` substitution — we cannot include literal
        # `{lanes}` in the call too because the seed's compiler
        # doesn't see `lanes` as a name (it's a function arg of the
        # mutator). Use a const binding instead.
        body_soa = (
            "// Bounded-campaign mutation (stefan_boltzmann_pair, soa_pack_%d_lane):\n"
            "let _lanes: [f64; %d] = [t_a_c, t_b_c, eps_a, eps_b];\n"
            "let _ = _lanes[0]; // opaque-to-the-optimizer lane prelude\n"
            "surface_radiative_exchange(\n"
            "    t_a_c, t_b_c, eps_a, eps_b, view_factor, area,\n"
            ")"
        ) % (lanes, lanes)
        return _replace_evolve_body(seed_text, body_soa)

    return mutate


def _stefan_unroll(factor: int):  # noqa: D401
    """Return a 4-way unroll mutator for the stefan seed."""

    def mutate(seed_text: str, block) -> str:
        body_unroll = (
            f"// Bounded-campaign mutation (stefan_boltzmann_pair, unroll_{factor}x):\n"
            "let _u0 = surface_radiative_exchange(t_a_c, t_b_c, eps_a, eps_b, view_factor, area);\n"
            "let _u1 = surface_radiative_exchange(t_a_c, t_b_c, eps_a, eps_b, view_factor, area);\n"
            "let _u2 = surface_radiative_exchange(t_a_c, t_b_c, eps_a, eps_b, view_factor, area);\n"
            "let _u3 = surface_radiative_exchange(t_a_c, t_b_c, eps_a, eps_b, view_factor, area);\n"
            "std::hint::black_box((_u0, _u1, _u2, _u3)).0"
        )
        return _replace_evolve_body(seed_text, body_unroll)

    return mutate


def _sky_soa_pack(lanes: int):  # noqa: D401
    """Return a SoA-pack mutator for the sky-radiation seed.

    The sky-radiation seed takes a `SkyRadiationExchange` value plus
    two `f64` temperatures, so the lane prelude packs the two
    temperatures (the `sky` value is not a scalar lane and is held
    outside the prelude to keep the seed's call signature frozen).
    """

    def mutate(seed_text: str, block) -> str:
        body_soa = (
            "// Bounded-campaign mutation (sky_radiation_net_flux, soa_pack_%d_lane):\n"
            "let _lanes: [f64; %d] = [surface_temp_c, sky_temp_c, surface_temp_c, sky_temp_c];\n"
            "let _ = _lanes[0]; // opaque-to-the-optimizer lane prelude\n"
            "sky.net_radiative_flux(surface_temp_c, sky_temp_c)"
        ) % (lanes, lanes)
        return _replace_evolve_body(seed_text, body_soa)

    return mutate


def _sky_unroll(factor: int):  # noqa: D401
    """Return a 4-way unroll mutator for the sky-radiation seed."""

    def mutate(seed_text: str, block) -> str:
        body_unroll = (
            f"// Bounded-campaign mutation (sky_radiation_net_flux, unroll_{factor}x):\n"
            "let _u0 = sky.net_radiative_flux(surface_temp_c, sky_temp_c);\n"
            "let _u1 = sky.net_radiative_flux(surface_temp_c, sky_temp_c);\n"
            "let _u2 = sky.net_radiative_flux(surface_temp_c, sky_temp_c);\n"
            "let _u3 = sky.net_radiative_flux(surface_temp_c, sky_temp_c);\n"
            "std::hint::black_box((_u0, _u1, _u2, _u3)).0"
        )
        return _replace_evolve_body(seed_text, body_unroll)

    return mutate


# ---------------------------------------------------------------------------
# EVOLVE-BLOCK parser + writer. Kept tiny — the seed files are
# pre-validated; the marker format is fixed.
# ---------------------------------------------------------------------------


PER_SEED_MUTATIONS = {
    "perez_diffuse_tilted": [
        ("identity", lambda s, b: s),
        ("soa_pack_4_lane", _perez_soa_pack("perez_diffuse_tilted.rs", lanes=4)),
        ("unroll_4x", _perez_unroll("perez_diffuse_tilted.rs", factor=4)),
    ],
    "stefan_boltzmann_pair": [
        ("identity", lambda s, b: s),
        ("soa_pack_4_lane", _stefan_soa_pack(lanes=4)),
        ("unroll_4x", _stefan_unroll(factor=4)),
    ],
    "sky_radiation_net_flux": [
        ("identity", lambda s, b: s),
        ("soa_pack_4_lane", _sky_soa_pack(lanes=4)),
        ("unroll_4x", _sky_unroll(factor=4)),
    ],
}


class EVOLVEBlock:
    def __init__(self, start: int, end: int, body: str):
        self.start = start  # offset of the line containing "EVOLVE-BLOCK-START"
        self.end = end      # offset of the line containing "EVOLVE-BLOCK-END"
        self.body = body


def find_evolve_block(seed_text: str) -> Optional[EVOLVEBlock]:
    lines = seed_text.splitlines(keepends=True)
    start_idx = None
    end_idx = None
    for i, line in enumerate(lines):
        if "EVOLVE-BLOCK-START" in line:
            start_idx = i
        elif "EVOLVE-BLOCK-END" in line and start_idx is not None:
            end_idx = i
            break
    if start_idx is None or end_idx is None:
        return None
    body_lines = lines[start_idx + 1 : end_idx]
    return EVOLVEBlock(
        start=sum(len(l) for l in lines[: start_idx + 1]),
        end=sum(len(l) for l in lines[: end_idx]),
        body="".join(body_lines),
    )


def _replace_evolve_body(seed_text: str, new_body: str) -> str:
    block = find_evolve_block(seed_text)
    if block is None:
        return seed_text
    head = seed_text[: block.start]
    # Keep the START marker line verbatim, then the body, then the
    # END marker line verbatim. The markers are on their own lines.
    # split on newlines to be robust.
    head_lines = head.split("\n")
    # head ends just before the START marker. We want to keep the
    # trailing newline after START marker.
    start_marker_line = None
    for i, l in enumerate(reversed(head_lines)):
        if "EVOLVE-BLOCK-START" in l:
            start_marker_line = len(head_lines) - 1 - i
            break
    if start_marker_line is None:
        return seed_text
    # Reassemble: lines[0..start_marker_line inclusive] + new_body + "\n"
    # + ...lines after END marker.
    head_lines = head_lines[: start_marker_line + 1]
    # The marker line ends with newline. Ensure new_body ends with one too.
    if not new_body.endswith("\n"):
        new_body = new_body + "\n"
    tail_text = seed_text[block.end :]
    return "\n".join(head_lines) + "\n" + new_body + tail_text.lstrip("\n")


def textwrap_dedent(s: str) -> str:
    """Tiny `textwrap.dedent` substitute; the std lib is fine, but
    keeping this script self-contained makes the bounded-campaign
    leg-script portable to boxes that lack `textwrap` (it does
    not — but the convention is to make seed grammars readable
    inline).
    """
    import textwrap

    return textwrap.dedent(s).lstrip("\n")


# ---------------------------------------------------------------------------
# Harness integration. The bounded runner shells out to the
# `fluxion-evaluator` binary through a hermetic tempdir that mirrors
# the recompile path. We invoke `cargo build` (dev profile) inside a
# sandbox-equivalent subprocess to keep the bounded re-run aligned
# with what the OpenEvolve adapter sees in CI.
# ---------------------------------------------------------------------------


def run_evaluator(
    candidate_source: str,
    candidate_id: str,
    generation: int,
    sandbox_root: Path,
    kernel_focus: str = "",
) -> dict:
    """Compile + run the candidate via the harness.

    Returns the parsed Summary JSON. On compile failure returns a
    Summary with `compiled = false`. On timeout returns a Summary
    with `outcome = "resource_cap"`. All paths funnel through the
    harness so the bounded re-run reads the same score contract
    that the OpenEvolve adapter would.
    """
    candidate_dir = sandbox_root / f"fluxion-evaluator-{candidate_id}"
    src_dir = candidate_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # Mirror the harness's `generate_cargo_toml` (issue #3336). We
    # model the candidate as a single-binary crate (no [lib]) so
    # `cargo build` produces a runnable artifact at
    # `target/debug/solar_simd_candidate`. This matches what the
    # bounded runner expects to invoke (subprocess with stdin/stdout
    # JSON). The full OpenEvolve adapter would compile as [lib] and
    # load via the harness's recompile loader.
    cargo_toml = (
        "[package]\n"
        'name = "solar_simd_candidate"\n'
        'version = "0.0.0"\n'
        'edition = "2021"\n'
        'publish = false\n'
        "\n"
        "[[bin]]\n"
        'name = "solar_simd_candidate"\n'
        'path = "src/main.rs"\n'
        "\n"
        "[dependencies]\n"
        'fluxion = { path = "%s" }\n'
        "fluxion-evaluator = { path = \"%s\" }\n"
        'serde_json = "1.0"\n'
        % (REPO_ROOT, EVALUATOR_CRATE)
    )
    (candidate_dir / "Cargo.toml").write_text(cargo_toml)

    # Copy the workspace `Cargo.lock` so `--offline` finds the resolved
    # dependency versions without re-resolving through the registry.
    # Without this the first compile in the sandbox hits the network,
    # which the harness's `CARGO_NET_OFFLINE=true` forbids by
    # contract (issue #3336 sandbox threat model).
    workspace_lock = REPO_ROOT / "Cargo.lock"
    if workspace_lock.exists():
        shutil.copy(workspace_lock, candidate_dir / "Cargo.lock")

    (src_dir / "kernel.rs").write_text(candidate_source)
    # Build a `main.rs` shim that wraps the candidate's
    # `Candidate::default()` with a stdio-friendly harness. The
    # seed files are reusable in both the bounded runner (this
    # script) and the full OpenEvolve adapter — the wrapper code
    # here is what makes them executable as a binary.
    (src_dir / "main.rs").write_text(
        _CANDIDATE_WRAPPER_TEMPLATE
    )
    kernel_rs = src_dir / "kernel.rs"
    if not kernel_rs.exists():
        # Defensive; we just wrote it.
        raise RuntimeError("kernel.rs missing post-write")

    # Harness-generated wrapper, mirroring `Recompiler::generate_lib_rs`.
    lib_rs = (
        "//! Harness-generated wrapper around the candidate kernel.\n"
        "\n"
        "mod kernel;\n"
        "\n"
        "use fluxion_evaluator::kernel::{\n"
        "    EdgeCase, Kernel, KernelInput, KernelOutput, ReferenceOutput,\n"
        "};\n"
        "use kernel::Candidate;\n"
        "\n"
        "pub fn evaluate(input_json: &str) -> Result<String, String> {\n"
        "    let input: KernelInput = serde_json::from_str(input_json)\n"
        '        .map_err(|e| format!("input decode failed: {}", e))?;\n'
        "    let candidate = Candidate::default();\n"
        "    let output = candidate.evaluate(&input).map_err(|e| format!(\"{:?}\", e))?;\n"
        '    serde_json::to_string(&output).map_err(|e| format!("output encode failed: {}", e))\n'
        "}\n"
        "\n"
        "pub use kernel::Candidate as __Candidate;\n"
    )
    (src_dir / "lib.rs").write_text(lib_rs)

    target_dir = candidate_dir / "target"

    # 1. Compile (dev profile, hermetic target dir).
    # The bounded runner is the *short* re-run; the production
    # OpenEvolve adapter uses 60s (matching the harness's
    # `SandboxConfig::wall_clock_cap` from issue #3336). For the
    # short re-run we allow a longer per-candidate compile budget
    # because cold caches cost more than 60s on the first compile.
    # `BOUNDED_CAMPAIGN_TIMEOUT_S` overrides both.
    import os
    timeout_s = int(os.environ.get("BOUNDED_CAMPAIGN_TIMEOUT_S", "300"))
    t0 = time.time()
    try:
        proc = subprocess.run(
            [
                "cargo",
                "build",
                "--target-dir",
                str(target_dir),
                "--offline",
            ],
            cwd=str(candidate_dir),
            check=False,
            capture_output=True,
            timeout=timeout_s,
            # Pin the toolchain to the workspace's MSRV (1.98.0). The
            # host shell may resolve `cargo` to a system `rustc` 1.97.1
            # which fails the `rust-version = "1.98.0"` floor in
            # Cargo.toml of every workspace member (`fluxion`,
            # `fluxion-core`, `fluxion-evaluator`, `fluxion-twin`).
            # Setting `RUSTUP_TOOLCHAIN=1.98.0` is the canonical fix;
            # rustup will resolve cargo→rustc through the toolchain
            # manifest otherwise.
            env={
                **os.environ,
                "RUSTUP_TOOLCHAIN": "1.98.0",
            },
        )
    except subprocess.TimeoutExpired:
        return _summary_timeout(candidate_id, generation)
    compile_seconds = time.time() - t0

    if proc.returncode != 0:
        return _summary_compile_failure(
            candidate_id, generation, proc.stderr.decode("utf-8", "replace")
        )

    # 2. Load edge cases. The fixture is multi-kernel: each case is
    # tagged with `kernel_focus` and the runner filters to the
    # ones matching the candidate's seed. This mirrors how the
    # OpenEvolve adapter would scope a campaign per kernel.
    raw_cases = json.loads(EDGE_CASES.read_text())["case_set"]
    cases = [c for c in raw_cases if c.get("kernel_focus") == kernel_focus]
    per_case = []
    invariant_violations = []

    for case in cases:
        case_input = {
            "case_name": case["case_name"],
            "params": case["input"]["params"],
        }
        try:
            artifact = _artifact_path(target_dir)
            if not artifact.exists():
                invariant_violations.append(
                    {
                        "case_name": case["case_name"],
                        "invariant_kind": "kernel_error",
                        "observed": float("nan"),
                        "threshold": None,
                        "message": f"artifact not found: {artifact}",
                    }
                )
                continue
            proc = subprocess.run(
                [str(artifact)],
                input=json.dumps(case_input).encode("utf-8"),
                cwd=str(candidate_dir),
                check=False,
                capture_output=True,
                timeout=10,
                env={
                    **__import__("os").environ,
                    "RUSTUP_TOOLCHAIN": "1.98.0",
                },
            )
        except subprocess.TimeoutExpired:
            invariant_violations.append(
                {
                    "case_name": case["case_name"],
                    "invariant_kind": "kernel_error",
                    "observed": float("nan"),
                    "threshold": None,
                    "message": "execution timeout",
                }
            )
            continue

        if proc.returncode != 0:
            invariant_violations.append(
                {
                    "case_name": case["case_name"],
                    "invariant_kind": "kernel_error",
                    "observed": float("nan"),
                    "threshold": None,
                    "message": proc.stderr.decode("utf-8", "replace"),
                }
            )
            continue

        output = json.loads(proc.stdout.decode("utf-8"))
        ref = case["reference"]

        # The bounded runner's wrapper emits the payload contents
        # directly (i.e. `KernelOutput::payload` rendered as JSON),
        # so `output` is the inner object. Guard against either
        # shape (with or without `payload` wrapping) so a future
        # wrapper change doesn't break the harness.
        payload = output["payload"] if isinstance(output, dict) and "payload" in output else output

        # Per-case residual.
        abs_err = 0.0
        ref_norm = 0.0
        for (k, v), (_rk, rv) in zip(payload.items(), ref.items()):
            try:
                fv = float(v)
                frv = float(rv)
            except (TypeError, ValueError):
                continue
            abs_err += abs(fv - frv)
            ref_norm += abs(frv)

        rel = abs_err / ref_norm if ref_norm > 0 else abs_err
        per_case.append(
            {
                "case_name": case["case_name"],
                "kernel_focus": case["kernel_focus"],
                "abs_err": abs_err,
                "ref_norm": ref_norm,
                "rel_err": rel,
                "max_rel": max(c.get("max_rel", 0.0) for c in per_case) if per_case else rel,
            }
        )

    # The actual Summary returned by the harness's bounded runner is
    # a Schema-v1-like struct; we emit the deterministic subset that
    # `fluxion-evaluator` itself emits, plus our own per-case map.
    max_rel = max((c["rel_err"] for c in per_case), default=0.0)
    threshold = 1.0e-9
    invariants_passed = (
        len(invariant_violations) == 0 and max_rel <= threshold
    )
    fitness = (
        max(0.0, 1.0 - max_rel / threshold) if invariants_passed else 0.0
    )

    summary = {
        "schema_version": 1,
        "candidate_id": candidate_id,
        "generation": generation,
        "compiled": True,
        "invariants_passed": invariants_passed,
        "fitness": fitness,
        "max_error": max_rel,
        "compile_seconds": round(compile_seconds, 3),
        "outcome": "evaluated" if invariants_passed else "invariant_hard_fail",
        "invariant_violations": invariant_violations,
        "per_case": per_case,
    }
    return summary


def _artifact_path(target_dir: Path) -> Path:
    # The candidate crate emits `target/debug/<bin-name>` on Linux.
    # The runner checks `.exists()` before invoking so a compile
    # failure returns the right Summary without a misleading
    # PermissionError.
    profile_dir = target_dir / "debug"
    return profile_dir / "solar_simd_candidate"


def _summary_compile_failure(candidate_id: str, generation: int, stderr: str) -> dict:
    return {
        "schema_version": 1,
        "candidate_id": candidate_id,
        "generation": generation,
        "compiled": False,
        "invariants_passed": False,
        "fitness": 0.0,
        "outcome": "compile_failure",
        "error": stderr[-1024:],
    }


def _summary_timeout(candidate_id: str, generation: int) -> dict:
    return {
        "schema_version": 1,
        "candidate_id": candidate_id,
        "generation": generation,
        "compiled": False,
        "invariants_passed": False,
        "fitness": 0.0,
        "outcome": "resource_cap",
        "error": "subprocess timeout (60s)",
    }


# ---------------------------------------------------------------------------
# Bounded run loop.
# ---------------------------------------------------------------------------


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "tools" / "evolution" / "results" / "solar_simd" / "bounded_run"),
        help="Output directory for per-candidate Summary JSON files.",
    )
    parser.add_argument(
        "--seeds",
        nargs="*",
        default=list(PER_SEED_MUTATIONS.keys()),
        help="Restrict the run to these seed names (default: all configured).",
    )
    args = parser.parse_args(argv)

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    sandbox_root = Path(tempfile.mkdtemp(prefix="fluxion-solar-simd-"))
    print(f"[bounded_run] sandbox_root = {sandbox_root}")
    print(f"[bounded_run] output_dir   = {output_dir}")

    summary_index = []
    generation = 0
    for seed_name in args.seeds:
        if seed_name not in PER_SEED_MUTATIONS:
            print(f"[bounded_run] unknown seed: {seed_name}")
            continue
        seed_path = SEEDS_DIR / f"{seed_name}.rs"
        if not seed_path.exists():
            print(f"[bounded_run] seed missing: {seed_path}")
            continue
        seed_text = seed_path.read_text()
        block = find_evolve_block(seed_text)
        if block is None:
            print(f"[bounded_run] {seed_name}: no EVOLVE-BLOCK; skipping")
            continue

        for label, mutator in PER_SEED_MUTATIONS[seed_name]:
            generation += 1
            candidate_id = f"{seed_name}-{label}-gen{generation:03d}"
            candidate_source = mutator(seed_text, block)
            if candidate_source == seed_text:
                # Identity — skip recompile, copy baseline summary.
                status = "skipped_identity"
                summary = {
                    "schema_version": 1,
                    "candidate_id": candidate_id,
                    "generation": generation,
                    "mutator": label,
                    "fitness": 1.0,
                    "compiled": True,
                    "invariants_passed": True,
                    "max_error": 0.0,
                    "compile_seconds": 0.0,
                    "outcome": "evaluated",
                    "note": "identity; no recompile",
                }
            else:
                t0 = time.time()
                summary = run_evaluator(
                    candidate_source,
                    candidate_id,
                    generation,
                    sandbox_root,
                    kernel_focus=seed_name,
                )
                summary["mutator"] = label
                summary["wall_time_s"] = round(time.time() - t0, 3)
                status = "ran"

            out_path = output_dir / f"{candidate_id}.json"
            out_path.write_text(json.dumps(summary, indent=2))
            summary_index.append(
                {
                    "candidate_id": candidate_id,
                    "mutator": label,
                    "fitness": summary.get("fitness", 0.0),
                    "invariants_passed": summary.get("invariants_passed", False),
                    "max_error": summary.get("max_error"),
                    "wall_time_s": summary.get("wall_time_s"),
                }
            )
            print(
                f"[bounded_run] gen={generation:03d} {candidate_id:62} "
                f"mut={label:18} status={status:18} "
                f"fitness={summary.get('fitness', 0.0):.4f} "
                f"max_err={summary.get('max_error')}"
            )

    (output_dir / "index.json").write_text(json.dumps(summary_index, indent=2))
    print(f"[bounded_run] wrote {len(summary_index)} candidate summaries to {output_dir}/")
    print(f"[bounded_run] index: {output_dir / 'index.json'}")

    # 0 = success (even if every candidate hard-failed; the report
    # files are the trust artifact).
    return 0


if __name__ == "__main__":
    sys.exit(main())
