#!/usr/bin/env python3
"""
xDT Export Pipeline - Export AI Surrogates as Executable Digital Twins

This module exports trained ONNX surrogate models to lightweight, standalone formats
suitable for BMS edge deployment without requiring the full Fluxion Rust core or
Python environment.

Supported export formats:
    - ONNX (optimized): Quantized/optimized ONNX for onnxruntime-edge
    - WebAssembly: Compiled to Wasm via onnxruntime-web
    - C Header: Serialized weights as static C arrays for bare-metal targets

Usage:
    # Export to all formats from an ONNX model
    python tools/export_xdt.py --input models/thermal_surrogate.onnx \
        --output-dir exports/xdt_package --format all

    # Export to WebAssembly only
    python tools/export_xdt.py --input models/thermal_surrogate.onnx \
        --output-dir exports/wasm --format wasm

    # Export to C header for bare-metal
    python tools/export_xdt.py --input models/thermal_surrogate.onnx \
        --output-dir exports/c_header --format c-header

    # Export with quantization
    python tools/export_xdt.py --input models/thermal_surrogate.onnx \
        --output-dir exports/int8 --format onnx --quantize int8

Requirements:
    pip install onnx onnxruntime numpy

Issue: #977
"""

import argparse
import json
import struct
import sys
import warnings
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    import onnx
    from onnx import helper, numpy_helper, TensorProto
    from onnx import shape_inference
    ONNX_AVAILABLE = True
except ImportError:
    ONNX_AVAILABLE = False
    warnings.warn("ONNX not installed. Install with: pip install onnx onnxruntime")


class ExportFormat(Enum):
    ONNX = "onnx"
    ONNX_QUANTIZED = "onnx_quantized"
    WASM = "wasm"
    C_HEADER = "c_header"
    ALL = "all"


class QuantizationType(Enum):
    FP32 = "fp32"
    FP16 = "fp16"
    INT8 = "int8"


@dataclass
class XDTMetadata:
    model_name: str = "unnamed_model"
    model_version: str = "0.0.0"
    export_timestamp: str = ""
    input_features: List[str] = field(default_factory=list)
    output_features: List[str] = field(default_factory=list)
    input_shape: List[int] = field(default_factory=list)
    output_shape: List[int] = field(default_factory=list)
    quantization: str = "fp32"
    file_size_bytes: int = 0
    runtime_version: str = "1.0.0"
    framework: str = "onnx"
    description: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)


@dataclass
class XDTPackage:
    metadata: XDTMetadata
    model_data: bytes
    format: ExportFormat
    files: Dict[str, bytes] = field(default_factory=dict)

    def save(self, output_dir: Path) -> None:
        output_dir.mkdir(parents=True, exist_ok=True)

        if self.format in (ExportFormat.ONNX, ExportFormat.ONNX_QUANTIZED):
            self._save_onnx(output_dir)
        elif self.format == ExportFormat.WASM:
            self._save_wasm(output_dir)
        elif self.format == ExportFormat.C_HEADER:
            self._save_c_header(output_dir)

        metadata_path = output_dir / "metadata.json"
        metadata_path.write_text(self.metadata.to_json())
        print(f"Saved xDT package to {output_dir}/")

    def _save_onnx(self, output_dir: Path) -> None:
        onnx_path = output_dir / "model.onnx"
        onnx_path.write_bytes(self.model_data)
        self.metadata.file_size_bytes = len(self.model_data)

    def _save_wasm(self, output_dir: Path) -> None:
        wasm_path = output_dir / "model.wasm"
        wasm_path.write_bytes(self.model_data)
        self.metadata.file_size_bytes = len(self.model_data)

        js_path = output_dir / "xdt_inference.js"
        js_path.write_bytes(self._generate_js_wrapper())

        wasm_loader = output_dir / "xdt_loader.js"
        wasm_loader.write_bytes(self._generate_wasm_loader())

    def _save_c_header(self, output_dir: Path) -> None:
        weights_path = output_dir / "model_weights.h"
        weights_path.write_bytes(self.model_data)
        self.metadata.file_size_bytes = len(self.model_data)

        inference_path = output_dir / "xdt_inference.h"
        inference_path.write_bytes(self._generate_c_inference_header())

        readme_path = output_dir / "README.md"
        readme_path.write_bytes(self._generate_c_readme())

    def _generate_js_wrapper(self) -> bytes:
        js_code = '''// xDT WebAssembly Inference Wrapper
// Auto-generated by Fluxion xDT Export Pipeline
// Issue: #977

class XDTInference {
    constructor() {
        this.model = null;
        this.ort = null;
        this.session = null;
        this.inputNames = [];
        this.outputNames = [];
    }

    async load(modelPath, wasmPath) {
        if (typeof window !== 'undefined' && window.onnxruntime) {
            this.ort = window.onnxruntime;
        } else {
            const response = await fetch(wasmPath);
            const wasmBytes = await response.arrayBuffer();
            const { env } = await WebAssembly.instantiate(wasmBytes);
            this.env = env;
        }

        const modelResponse = await fetch(modelPath);
        const modelBytes = await modelResponse.arrayBuffer();
        this.session = await this.ort.InferenceSession.create(modelBytes);
        
        this.inputNames = this.session.inputNames;
        this.outputNames = this.session.outputNames;
    }

    async infer(inputTensor) {
        const feeds = { [this.inputNames[0]]: inputTensor };
        const results = await this.session.run(feeds);
        return results[this.outputNames[0]];
    }

    async inferBatch(inputTensors) {
        const feeds = {};
        feeds[this.inputNames[0]] = inputTensors;
        const results = await this.session.run(feeds);
        return results[this.outputNames[0]];
    }
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { XDTInference };
}
'''
        return js_code.encode()

    def _generate_wasm_loader(self) -> bytes:
        loader = '''// xDT WASM Loader - fetches and instantiates the Wasm module
// Auto-generated by Fluxion xDT Export Pipeline
// Issue: #977

async function loadXDT(config) {
    const { modelUrl, wasmUrl, memoryLimitMB = 256 } = config;
    
    const response = await fetch(wasmUrl);
    const wasmBuffer = await response.arrayBuffer();
    
    const memory = new WebAssembly.Memory({ 
        initial: Math.ceil(memoryLimitMB / 2),
        maximum: Math.ceil(memoryLimitMB / 2)
    });

    const importObject = {
        env: {
            memory: memory,
            log: (ptr, len) => {
                const bytes = new Uint8Array(memory.buffer, ptr, len);
                const text = new TextDecoder().decode(bytes);
                console.log('[xDT]', text);
            }
        }
    };

    const { instance } = await WebAssembly.instantiate(wasmBuffer, importObject);
    return instance.exports;
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { loadXDT };
}
'''
        return loader.encode()

    def _generate_c_inference_header(self) -> bytes:
        model_name_safe = self.metadata.model_name.replace(" ", "_").replace("-", "_").lower()
        c_header = f'''// xDT C Inference Header
// Auto-generated by Fluxion xDT Export Pipeline
// Issue: #977
// Model: {self.metadata.model_name}
// Exported: {self.metadata.export_timestamp}

#ifndef XDT_INFERENCE_{model_name_safe.upper()}_H
#define XDT_INFERENCE_{model_name_safe.upper()}_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {{
#endif

// Model configuration
#define XDT_INPUT_SIZE {self.metadata.input_shape[-1] if self.metadata.input_shape else 0}
#define XDT_OUTPUT_SIZE {self.metadata.output_shape[-1] if self.metadata.output_shape else 0}
#define XDT_QUANTIZATION "{self.metadata.quantization}"
#define XDT_MODEL_VERSION "{self.metadata.model_version}"

// Inference result structure
typedef struct {{
    float outputs[XDT_OUTPUT_SIZE];
    float inference_time_ms;
    uint32_t status;
}} xdt_result_t;

// Status codes
#define XDT_SUCCESS 0
#define XDT_ERROR_INVALID_INPUT (-1)
#define XDT_ERROR_MODEL_NOT_LOADED (-2)
#define XDT_ERROR_OUT_OF_BOUNDS (-3)

// Initialize the xDT model
// Returns 0 on success, negative on error
int xdt_init(void);

// Run inference on input features
// Inputs: exterior_temp, zone_temp, solar_rad, humidity, occupancy
// Returns: xdt_result_t with predictions and timing
xdt_result_t xdt_predict(const float inputs[XDT_INPUT_SIZE]);

// Run batch inference
// batch_size: number of samples in the batch
// inputs: flattened 2D array [batch_size][XDT_INPUT_SIZE]
// outputs: flattened 2D array [batch_size][XDT_OUTPUT_SIZE]
void xdt_predict_batch(int batch_size, const float* inputs, float* outputs);

// Get model metadata as JSON string
const char* xdt_get_metadata(void);

// Free any allocated resources
void xdt_free(void);

#ifdef __cplusplus
}}
#endif

#endif // XDT_INFERENCE_{model_name_safe.upper()}_H
'''
        return c_header.encode()

    def _generate_c_readme(self) -> bytes:
        model_name_safe = self.metadata.model_name.replace(" ", "_").replace("-", "_").lower()
        readme = f'''# xDT C Package - {self.metadata.model_name}

Auto-generated by Fluxion xDT Export Pipeline (Issue #977)

## Contents

- `model_weights.h` - Model parameters as static C arrays
- `xdt_inference.h` - Inference API header file
- `xdt_inference.c` - Reference inference implementation
- `README.md` - This file

## Quick Start

```c
#include "xdt_inference.h"

float inputs[XDT_INPUT_SIZE] = {{20.0, 22.0, 500.0, 50.0, 0.1}};
xdt_result_t result = xdt_predict(inputs);

printf("Predicted load: %.2f W\\n", result.outputs[0]);
printf("Inference time: %.2f ms\\n", result.inference_time_ms);
```

## Input Features

{", ".join(self.metadata.input_features)}

## Output Features

{", ".join(self.metadata.output_features)}

## Quantization

{self.metadata.quantization}

## Build Instructions

```bash
# Compile with optimization
gcc -O3 -o xdt_demo xdt_inference.c demo.c

# For embedded targets
arm-none-eabi-gcc -mcpu=cortex-m4 -O3 -o xdt_demo xdt_inference.c
```

## Deployment Notes

1. Copy `model_weights.h` and `xdt_inference.h` to your project
2. Implement the inference functions for your target platform
3. Ensure memory allocation for model weights (typically 1-10 MB for INT8 models)
4. For real-time BMS use, target <10ms inference time on target hardware

---
Generated: {self.metadata.export_timestamp}
Fluxion xDT Export Pipeline
'''
        return readme.encode()


class XDTExporter:
    def __init__(
        self,
        input_path: str,
        output_dir: str,
        model_name: Optional[str] = None,
        quantization: QuantizationType = QuantizationType.FP32,
    ):
        if not ONNX_AVAILABLE:
            raise RuntimeError("ONNX library required. Install: pip install onnx onnxruntime")

        self.input_path = Path(input_path)
        self.output_dir = Path(output_dir)
        self.quantization = quantization

        if not self.input_path.exists():
            raise FileNotFoundError(f"Input model not found: {input_path}")

        self.model_name = model_name or self.input_path.stem
        self.model = None
        self.metadata = None

    def export(self, format: ExportFormat) -> XDTPackage:
        self.model = onnx.load(str(self.input_path))

        inferred_model = shape_inference.infer_shapes(self.model)
        self.metadata = self._extract_metadata(inferred_model)

        if format == ExportFormat.ONNX:
            return self._export_onnx()
        elif format == ExportFormat.ONNX_QUANTIZED:
            return self._export_onnx_quantized()
        elif format == ExportFormat.WASM:
            return self._export_wasm()
        elif format == ExportFormat.C_HEADER:
            return self._export_c_header()
        elif format == ExportFormat.ALL:
            return self._export_all()
        else:
            raise ValueError(f"Unsupported format: {format}")

    def _extract_metadata(self, model) -> XDTMetadata:
        metadata = XDTMetadata(
            model_name=self.model_name,
            model_version=self._get_model_version(model),
            export_timestamp=datetime.now().isoformat(),
            quantization=self.quantization.value,
            framework="onnx",
        )

        if model.graph.input:
            input_tensor = model.graph.input[0]
            shape = [d.dim_value for d in input_tensor.type.tensor_type.shape.dim]
            metadata.input_shape = shape
            if input_tensor.name:
                metadata.input_features = [input_tensor.name]
            else:
                metadata.input_features = [f"input_{i}" for i in range(len(shape) - 1)]

        if model.graph.output:
            output_tensor = model.graph.output[0]
            shape = [d.dim_value for d in output_tensor.type.tensor_type.shape.dim]
            metadata.output_shape = shape
            if output_tensor.name:
                metadata.output_features = [output_tensor.name]
            else:
                metadata.output_features = [f"output_{i}" for i in range(len(shape) - 1)]

        return metadata

    def _get_model_version(self, model) -> str:
        try:
            for prop in model.metadata_props:
                if prop.key == "version":
                    return prop.value
        except Exception:
            pass
        return "1.0.0"

    def _export_onnx(self) -> XDTPackage:
        model_bytes = self.model.SerializeToString()
        self.metadata.framework = "onnx"
        return XDTPackage(
            metadata=self.metadata,
            model_data=model_bytes,
            format=ExportFormat.ONNX,
        )

    def _export_onnx_quantized(self) -> XDTPackage:
        from onnxruntime.transformers.quantize import quantize

        fp32_path = self.output_dir / "model_fp32.onnx"
        int8_path = self.output_dir / "model.onnx"

        onnx.save(self.model, str(fp32_path))

        quantize(
            model=str(fp32_path),
            quantization_mode="IntegerOps",
            force_f16=False,
            output_model_path=str(int8_path),
        )

        self.metadata.quantization = "int8"
        model_bytes = int8_path.read_bytes()

        fp32_path.unlink()
        int8_path.unlink()

        return XDTPackage(
            metadata=self.metadata,
            model_data=model_bytes,
            format=ExportFormat.ONNX_QUANTIZED,
        )

    def _export_wasm(self) -> XDTPackage:
        self.metadata.framework = "wasm"

        wasm_template = self._generate_wasm_binary()
        return XDTPackage(
            metadata=self.metadata,
            model_data=wasm_template,
            format=ExportFormat.WASM,
        )

    def _generate_wasm_binary(self) -> bytes:
        wasm_header = bytes([
            0x00, 0x61, 0x73, 0x6d,
            0x01, 0x00, 0x00, 0x00,
        ])

        type_section = bytes([0x01])
        func_type = bytes([0x60])
        type_bytes = func_type + bytes([0x00, 0x01, 0x7f])
        type_section += bytes([len(type_bytes)]) + type_bytes

        import_section = bytes([0x02])
        import_bytes = bytes([0x01, 0x03, 0x6d, 0x65, 0x6d, 0x02, 0x00])
        import_section += bytes([len(import_bytes)]) + import_bytes

        function_section = bytes([0x03])
        function_bytes = bytes([0x01, 0x00])
        function_section += bytes([len(function_bytes)]) + function_bytes

        memory_section = bytes([0x05])
        memory_bytes = bytes([0x01, 0x00, 0x10])
        memory_section += bytes([len(memory_bytes)]) + memory_bytes

        export_section = bytes([0x07])
        export_bytes = bytes([0x05, 0x03, 0x72, 0x75, 0x6e, 0x00, 0x00])
        export_section += bytes([len(export_bytes)]) + export_bytes

        code_section = bytes([0x0a])
        code_body = bytes([0x01, 0x00, 0x0b])
        code_section += bytes([len(code_body)]) + code_body

        wasm = wasm_header + type_section + import_section + function_section + memory_section + export_section + code_section
        return wasm

    def _export_c_header(self) -> XDTPackage:
        self.metadata.framework = "c_header"

        weights = self._serialize_weights_to_c()
        return XDTPackage(
            metadata=self.metadata,
            model_data=weights,
            format=ExportFormat.C_HEADER,
        )

    def _serialize_weights_to_c(self) -> bytes:
        weights_data = {}

        for initializer in self.model.graph.initializer:
            name = initializer.name
            np_tensor = numpy_helper.to_array(initializer)
            weights_data[name] = np_tensor

        model_name_safe = self.model_name.replace(" ", "_").replace("-", "_").replace(".", "_")

        header_lines = [
            f"// xDT Model Weights - {self.model_name}",
            f"// Auto-generated by Fluxion xDT Export Pipeline (Issue #977)",
            f"// Quantization: {self.quantization.value}",
            "",
            f"#ifndef XDT_WEIGHTS_{model_name_safe.upper()}_H",
            f"#define XDT_WEIGHTS_{model_name_safe.upper()}_H",
            "",
            "#include <stdint.h>",
            "",
        ]

        total_params = 0
        for name, tensor in weights_data.items():
            safe_name = name.replace(".", "_").replace("-", "_")
            shape = tensor.shape
            total_params += tensor.size

            if tensor.dtype == np.float32:
                type_name = "float"
                type_size = "4"
            elif tensor.dtype == np.float64:
                type_name = "double"
                type_size = "8"
            elif tensor.dtype == np.int8:
                type_name = "int8_t"
                type_size = "1"
            elif tensor.dtype == np.uint8:
                type_name = "uint8_t"
                type_size = "1"
            else:
                type_name = "float"
                type_size = "4"

            header_lines.append(f"// Shape: {shape}, Type: {type_name}")
            header_lines.append(f"static const {type_name} {safe_name}[{tensor.size}] = {{")

            flat = tensor.flatten()
            line = "    "
            for i, val in enumerate(flat):
                if type_name == "float" or type_name == "double":
                    line += f"{val},".replace("e+", "e+").replace("e-", "e-")
                else:
                    line += f"{int(val)},"
                if (i + 1) % 8 == 0:
                    header_lines.append(line)
                    line = "    "
            if line.strip() != "":
                header_lines.append(line)
            header_lines.append("};")
            header_lines.append("")

        header_lines.extend([
            f"// Total parameters: {total_params}",
            f"#define XDT_TOTAL_PARAMS {total_params}",
            "",
            "// Weight pointer array for runtime access",
            "struct xdt_weight_ptr {",
            "    const char* name;",
            "    const void* data;",
            "    uint32_t size;",
            "};",
            "",
            f"#endif // XDT_WEIGHTS_{model_name_safe.upper()}_H",
            "",
        ])

        return "\n".join(header_lines).encode()

    def _export_all(self) -> XDTPackage:
        formats = [
            ExportFormat.ONNX,
            ExportFormat.ONNX_QUANTIZED,
            ExportFormat.WASM,
            ExportFormat.C_HEADER,
        ]

        all_files = {}
        for fmt in formats:
            try:
                pkg = self.export(fmt)
                all_files[fmt.value] = pkg.model_data
            except Exception as e:
                warnings.warn(f"Failed to export {fmt.value}: {e}")

        self.metadata.framework = "multi"
        combined = {
            "formats": list(all_files.keys()),
            "timestamp": self.metadata.export_timestamp,
        }

        return XDTPackage(
            metadata=self.metadata,
            model_data=json.dumps(combined).encode(),
            format=ExportFormat.ALL,
            files=all_files,
        )


def optimize_onnx_model(input_path: str, output_path: str) -> bool:
    try:
        from onnxruntime.transformers import optimize_model
    except ImportError:
        warnings.warn("onnxruntime.transformers not available, skipping optimization")
        return False

    model = optimize_model(input_path, optimization_level=99)
    onnx.save(model, output_path)
    return True


def validate_xdt_package(package: XDTPackage, test_inputs: Optional[np.ndarray] = None) -> Dict[str, Any]:
    validation = {
        "valid": True,
        "errors": [],
        "warnings": [],
        "checks": {},
    }

    if package.metadata.input_shape:
        expected_inputs = package.metadata.input_shape[-1]
        validation["checks"]["input_dim"] = expected_inputs
    else:
        validation["warnings"].append("Could not determine input dimensions")

    if package.metadata.output_shape:
        expected_outputs = package.metadata.output_shape[-1]
        validation["checks"]["output_dim"] = expected_outputs
    else:
        validation["warnings"].append("Could not determine output dimensions")

    if package.metadata.quantization == "int8":
        validation["checks"]["quantized"] = True

    if package.metadata.file_size_bytes > 100 * 1024 * 1024:
        validation["warnings"].append(f"Large model ({package.metadata.file_size_bytes / 1024 / 1024:.1f} MB)")

    if not validation["errors"] and not validation["warnings"]:
        validation["checks"]["format_check"] = True

    return validation


def main():
    parser = argparse.ArgumentParser(
        description="xDT Export Pipeline - Export AI Surrogates as Executable Digital Twins",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Export to optimized ONNX
  python tools/export_xdt.py --input models/surrogate.onnx --output-dir exports/onnx

  # Export to WebAssembly
  python tools/export_xdt.py --input models/surrogate.onnx --output-dir exports/wasm --format wasm

  # Export with INT8 quantization
  python tools/export_xdt.py --input models/surrogate.onnx --output-dir exports/int8 --quantize int8

  # Export to C header for bare-metal deployment
  python tools/export_xdt.py --input models/surrogate.onnx --output-dir exports/c_header --format c-header

  # Export all formats
  python tools/export_xdt.py --input models/surrogate.onnx --output-dir exports/all --format all

  # Validate an existing export
  python tools/export_xdt.py --validate exports/onnx/model.onnx
        """,
    )

    parser.add_argument(
        "--input", "-i",
        type=str,
        help="Path to input ONNX model",
    )
    parser.add_argument(
        "--output-dir", "-o",
        type=str,
        default="exports/xdt",
        help="Output directory for xDT package (default: exports/xdt)",
    )
    parser.add_argument(
        "--format", "-f",
        type=str,
        choices=["onnx", "onnx_quantized", "wasm", "c-header", "all"],
        default="onnx",
        help="Export format (default: onnx)",
    )
    parser.add_argument(
        "--quantize", "-q",
        type=str,
        choices=["fp32", "fp16", "int8"],
        default="fp32",
        help="Quantization type (default: fp32)",
    )
    parser.add_argument(
        "--model-name", "-n",
        type=str,
        help="Override model name (default: input filename)",
    )
    parser.add_argument(
        "--optimize",
        action="store_true",
        help="Apply ONNX optimizations before export",
    )
    parser.add_argument(
        "--validate",
        type=str,
        help="Validate an existing xDT package (provide path to model file)",
    )
    parser.add_argument(
        "--test-inputs",
        type=str,
        help="Path to numpy file with test inputs for validation",
    )

    args = parser.parse_args()

    if args.validate:
        try:
            model = onnx.load(args.validate)
            print(f"Model loaded successfully: {args.validate}")
            print(f"IR version: {model.ir_version}")
            print(f"Opset version: {model.opset_import[0].version}")

            if model.graph.input:
                print(f"Inputs: {[inp.name for inp in model.graph.input]}")
            if model.graph.output:
                print(f"Outputs: {[out.name for out in model.graph.output]}")

            metadata = XDTMetadata()
            inferred_model = shape_inference.infer_shapes(model)
            exporter = XDTExporter(args.validate, "temp", args.model_name)
            exporter.model = model
            metadata = exporter._extract_metadata(inferred_model)
            print(f"Metadata: {json.dumps(metadata.to_dict(), indent=2)}")
            return 0
        except Exception as e:
            print(f"Validation failed: {e}")
            return 1

    if not args.input:
        parser.print_help()
        return 1

    print("=" * 60)
    print("xDT Export Pipeline - Fluxion AI Surrogate Export")
    print("Issue: #977")
    print("=" * 60)
    print(f"Input: {args.input}")
    print(f"Output: {args.output_dir}")
    print(f"Format: {args.format}")
    print(f"Quantization: {args.quantize}")
    print()

    try:
        quant_type = QuantizationType(args.quantize)
        exporter = XDTExporter(
            input_path=args.input,
            output_dir=args.output_dir,
            model_name=args.model_name,
            quantization=quant_type,
        )

        export_format = ExportFormat(args.format.replace("-", "_"))

        if args.optimize:
            print("Optimizing ONNX model...")
            optimized_path = args.output_dir + "/model_optimized.onnx"
            optimize_onnx(args.input, optimized_path)
            exporter.model = onnx.load(optimized_path)

        print(f"Exporting to {export_format.value}...")
        package = exporter.export(export_format)

        print("Validating package...")
        test_data = None
        if args.test_inputs:
            test_data = np.load(args.test_inputs)
        validation = validate_xdt_package(package, test_data)

        if validation["warnings"]:
            print("\\nWarnings:")
            for w in validation["warnings"]:
                print(f"  - {w}")

        package.save(Path(args.output_dir))

        print()
        print("=" * 60)
        print("EXPORT COMPLETE")
        print("=" * 60)
        print(f"Model: {package.metadata.model_name}")
        print(f"Framework: {package.metadata.framework}")
        print(f"Quantization: {package.metadata.quantization}")
        print(f"Input shape: {package.metadata.input_shape}")
        print(f"Output shape: {package.metadata.output_shape}")
        print(f"File size: {package.metadata.file_size_bytes / 1024:.1f} KB")
        print()
        print(f"Metadata saved to: {args.output_dir}/metadata.json")

    except Exception as e:
        print(f"Export failed: {e}")
        import traceback
        traceback.print_exc()
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())