#!/usr/bin/env python3
"""
Generate Regression Tests from EnergyPlus Reference Data

This tool generates Rust test code comparing Fluxion and EnergyPlus outputs
for regression testing. It creates comprehensive test cases with proper assertions
using the EPValidation framework.

Usage:
    python tools/generate_regression_tests.py \\
        --case-id 600 \\
        --fluxion-output fluxion_600.json \\
        --ep-output ep_600.json \\
        --test-name case_600_regression

    python tools/generate_regression_tests.py --all-cases

    python tools/generate_regression_tests.py --case-id 900 --auto-detect
"""

import argparse
import sys
from pathlib import Path
from typing import List, Optional, Tuple

# Default validation thresholds
DEFAULT_MAX_ABS_ERROR = 1.0  # 1K for temps, 1W for fluxes
DEFAULT_MAX_REL_ERROR = 0.05  # 5%
DEFAULT_MIN_CORRELATION = 0.95  # R²
DEFAULT_MAX_RMSE = 0.5  # K


def generate_rust_test(
    case_id: str,
    fluxion_file: str,
    ep_file: str,
    test_name: str,
    max_abs_error: float = DEFAULT_MAX_ABS_ERROR,
    max_rel_error: float = DEFAULT_MAX_REL_ERROR,
    min_correlation: float = DEFAULT_MIN_CORRELATION,
    max_rmse: float = DEFAULT_MAX_RMSE,
) -> str:
    """
    Generate Rust test code comparing Fluxion and EP outputs.

    Args:
        case_id: ASHRAE 140 case identifier (e.g., "600", "900")
        fluxion_file: Path to Fluxion output JSON file
        ep_file: Path to EnergyPlus output JSON file
        test_name: Name for the generated test function
        max_abs_error: Maximum allowed absolute error
        max_rel_error: Maximum allowed relative error
        min_correlation: Minimum required correlation coefficient
        max_rmse: Maximum allowed RMSE

    Returns:
        Formatted Rust test code as string
    """
    template = f"""/// Regression test for ASHRAE 140 Case {case_id}
///
/// Validates Fluxion simulation results against EnergyPlus reference data.
/// This test was auto-generated by tools/generate_regression_tests.py.
#[test]
fn {test_name}() {{
    use fluxion::validation::ep_oracle::{{EPOracle, FluxionResults, ValidationCriteria}};
    use std::fs;
    use std::path::Path;

    // Load Fluxion results
    let fluxion_data = fs::read_to_string("{fluxion_file}")
        .expect("Failed to read Fluxion output file");
    let fluxion_output: serde_json::Value = serde_json::from_str(&fluxion_data)
        .expect("Failed to parse Fluxion JSON");

    // Load EnergyPlus reference data
    let ep_data = fs::read_to_string("{ep_file}")
        .expect("Failed to read EnergyPlus output file");
    let ep_output: serde_json::Value = serde_json::from_str(&ep_data)
        .expect("Failed to parse EP JSON");

    // Extract temperatures
    let fluxion_temps: Vec<f64> = fluxion_output["temperatures"]
        .as_array()
        .expect("Fluxion temperatures not found")
        .iter()
        .map(|v| v.as_f64().expect("Invalid temperature value"))
        .collect();

    let ep_temps: Vec<f64> = ep_output["temperatures"]
        .as_array()
        .expect("EP temperatures not found")
        .iter()
        .map(|v| v.as_f64().expect("Invalid temperature value"))
        .collect();

    // Extract fluxes (optional)
    let fluxion_fluxes: Option<Vec<f64>> = fluxion_output["fluxes"]
        .as_array()
        .map(|arr| arr.iter().map(|v| v.as_f64().expect("Invalid flux value")).collect());

    let ep_fluxes: Option<Vec<f64>> = ep_output["fluxes"]
        .as_array()
        .map(|arr| arr.iter().map(|v| v.as_f64().expect("Invalid flux value")).collect());

    // Extract energy values
    let fluxion_energy: f64 = fluxion_output["energy"]
        .as_f64()
        .expect("Fluxion energy not found");

    let ep_energy: f64 = ep_output["energy"]
        .as_f64()
        .expect("EP energy not found");

    // Create FluxionResults structure
    let fluxion_results = FluxionResults {{
        temperatures: fluxion_temps,
        fluxes: fluxion_fluxes,
        energy: fluxion_energy,
    }};

    // Create validation criteria
    let criteria = ValidationCriteria {{
        max_abs_error: {max_abs_error},
        max_rel_error: {max_rel_error},
        min_correlation: {min_correlation},
        max_rmse: {max_rmse},
    }};

    // Create and run oracle
    let oracle = EPOracle::new_with_criteria(criteria)
        .expect("Failed to create EPOracle");

    let report = oracle.validate_results(&fluxion_results, &ep_temps, &ep_fluxes, &ep_energy);

    // Assert validation passed with detailed error message
    assert!(
        report.passed,
        "Case {case_id} regression failed:\\n{{}}",
        report
    );

    // Optionally verify specific metrics with stricter tolerances
    if let Some(temp_metrics) = report.temperature {{
        println!("Temperature metrics:");
        println!("  Max abs error: {{:.4}} K", temp_metrics.max_abs_error);
        println!("  Max rel error: {{:.2}}%", temp_metrics.max_rel_error * 100.0);
        println!("  RMSE: {{:.4}} K", temp_metrics.rmse);
        println!("  Correlation: {{.4}}", temp_metrics.correlation);

        // Assert individual metrics meet stricter criteria
        assert!(
            temp_metrics.rmse < {max_rmse * 0.5},
            "Temperature RMSE too high: {{:.4}} K (max: {{:.4}} K)",
            temp_metrics.rmse,
            max_rmse * 0.5
        );
    }}

    if let Some(energy_metrics) = report.energy {{
        println!("Energy metrics:");
        println!("  Abs error: {{:.2}} kWh", energy_metrics.abs_error);
        println!("  Rel error: {{:.2}}%", energy_metrics.rel_error * 100.0);

        // Energy should be within tighter tolerance
        let energy_rel_error = (fluxion_energy - ep_energy).abs() / ep_energy;
        assert!(
            energy_rel_error < {max_rel_error * 0.5},
            "Energy error too high: {{:.2}}% (max: {{:.2}}%)",
            energy_rel_error * 100.0,
            max_rel_error * 50.0
        );
    }}
}}
"""
    return template


def generate_test_file_header() -> str:
    """Generate the header for the test file."""
    return """//! ASHRAE 140 Regression Tests
//!
//! This module contains auto-generated regression tests comparing Fluxion
//! simulation results against EnergyPlus reference data.
//!
//! Generated by: tools/generate_regression_tests.py

#![allow(unused_imports)]

use serde_json::Value;

// Helper function to calculate statistics
fn calculate_stats(values: &[f64]) -> (f64, f64, f64) {
    let n = values.len() as f64;
    if n == 0.0 {
        return (0.0, 0.0, 0.0);
    }

    let mean: f64 = values.iter().sum::<f64>() / n;
    let variance: f64 = values.iter()
        .map(|&x| (x - mean).powi(2))
        .sum::<f64>() / n;

    let std_dev = variance.sqrt();
    (mean, std_dev, variance)
}

// Helper function to calculate RMSE
fn calculate_rmse(actual: &[f64], expected: &[f64]) -> f64 {
    if actual.len() != expected.len() {
        panic!("Length mismatch: actual={{}}, expected={{}}", actual.len(), expected.len());
    }

    let sum_squared: f64 = actual.iter()
        .zip(expected.iter())
        .map(|(&a, &e)| (a - e).powi(2))
        .sum();

    (sum_squared / actual.len() as f64).sqrt()
}

// Helper function to calculate correlation
fn calculate_correlation(actual: &[f64], expected: &[f64]) -> f64 {
    if actual.len() != expected.len() || actual.len() < 2 {
        return 1.0;
    }

    let n = actual.len() as f64;

    let mean_actual = actual.iter().sum::<f64>() / n;
    let mean_expected = expected.iter().sum::<f64>() / n;

    let numerator: f64 = actual.iter()
        .zip(expected.iter())
        .map(|(&a, &e)| (a - mean_actual) * (e - mean_expected))
        .sum::<f64>();

    let variance_actual: f64 = actual.iter()
        .map(|&x| (x - mean_actual).powi(2))
        .sum::<f64>();
    let variance_expected: f64 = expected.iter()
        .map(|&x| (x - mean_expected).powi(2))
        .sum::<f64>();

    if variance_actual == 0.0 || variance_expected == 0.0 {
        return 1.0;
    }

    let denominator = (variance_actual * variance_expected).sqrt();
    numerator / denominator
}

// Helper function to calculate NMBE (Normalized Mean Bias Error)
fn calculate_nmbe(actual: &[f64], expected: &[f64]) -> f64 {
    if actual.len() != expected.len() || actual.is_empty() {
        return 0.0;
    }

    let mean_expected = expected.iter().sum::<f64>() / actual.len() as f64;

    let numerator: f64 = actual.iter()
        .zip(expected.iter())
        .map(|(&a, &e)| (a - e))
        .sum::<f64>();

    let denominator: f64 = expected.iter().sum::<f64>();

    if denominator == 0.0 {
        return 0.0;
    }

    (numerator / denominator) * 100.0
}

// Helper function to calculate CV_RMSE (Coefficient of Variation of RMSE)
fn calculate_cv_rmse(actual: &[f64], expected: &[f64]) -> f64 {
    if actual.len() != expected.len() || actual.is_empty() {
        return 0.0;
    }

    let rmse = calculate_rmse(actual, expected);
    let mean_expected = expected.iter().sum::<f64>() / actual.len() as f64;

    if mean_expected == 0.0 {
        return 0.0;
    }

    (rmse / mean_expected) * 100.0
}
"""


def generate_module_docstring() -> str:
    """Generate module documentation."""
    return """
/// This module contains regression tests generated from EnergyPlus reference data.
///
/// Each test validates that Fluxion simulation results remain consistent
/// with EnergyPlus after code changes, catching regressions early.
///
/// Test Organization:
/// - `test_case_600_*`: Tests for Case 600 (heavyweight baseline)
/// - `test_case_900_*`: Tests for Case 900 (lightweight baseline)
/// - `test_case_*_ff`: Tests for free-floating cases
/// - `test_case_*_960`: Tests for multi-zone case 960
///
/// Regeneration:
/// To regenerate these tests after updating reference data:
/// ```bash
/// python tools/generate_regression_tests.py --all-cases
/// ```
"""


def auto_detect_case_files(
    case_id: str, base_dir: str = "refdata/ep"
) -> Tuple[Optional[str], Optional[str]]:
    """
    Auto-detect Fluxion and EnergyPlus output files for a case.

    Args:
        case_id: Case identifier (e.g., "600", "900")
        base_dir: Base directory to search in

    Returns:
        Tuple of (fluxion_file, ep_file) or (None, None) if not found
    """
    base_path = Path(base_dir)

    # Look for Fluxion output
    fluxion_patterns = [
        f"fluxion_{case_id}.json",
        f"Case_{case_id}_fluxion.json",
        f"fluxion_output_{case_id}.json",
    ]

    fluxion_file = None
    for pattern in fluxion_patterns:
        candidate = base_path / pattern
        if candidate.exists():
            fluxion_file = str(candidate)
            break

    # Look for EP output
    ep_patterns = [
        f"Case_{case_id}_results.json",
        f"ep_{case_id}.json",
        f"Case_{case_id}_ep.json",
    ]

    ep_file = None
    for pattern in ep_patterns:
        candidate = base_path / pattern
        if candidate.exists():
            ep_file = str(candidate)
            break

    return (fluxion_file, ep_file)


def generate_all_cases_test_file(
    cases: List[str],
    base_dir: str = "refdata/ep",
    output_file: str = "tests/physics/ashrae_140_regression.rs",
) -> None:
    """
    Generate a test file with multiple case regression tests.

    Args:
        cases: List of case IDs to generate tests for
        base_dir: Base directory containing reference data
        output_file: Output test file path
    """
    tests = []
    missing_data = []

    for case_id in cases:
        fluxion_file, ep_file = auto_detect_case_files(case_id, base_dir)

        if fluxion_file is None or ep_file is None:
            missing_data.append(case_id)
            continue

        test_name = f"test_case_{case_id}_regression"
        test_code = generate_rust_test(case_id, fluxion_file, ep_file, test_name)
        tests.append(test_code)

    # Generate the test file
    output = [
        generate_module_docstring(),
        generate_test_file_header(),
    ] + tests

    # Add a summary comment for missing data
    if missing_data:
        missing_comment = f"// NOTE: The following cases were skipped due to missing reference data: {', '.join(sorted(missing_data))}\n"
        output.append(missing_comment)

    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(output))

    print(f"Generated regression test file: {output_file}")
    print(f"  Tests generated: {len(tests)}")
    if missing_data:
        print(f"  Skipped cases (missing data): {len(missing_data)}")
        print(f"    {', '.join(sorted(missing_data))}")


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="Generate ASHRAE 140 regression tests from EnergyPlus reference data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate test for a single case
  python tools/generate_regression_tests.py --case-id 600 \\
      --fluxion-output refdata/ep/fluxion_600.json \\
      --ep-output refdata/ep/Case_600_results.json

  # Auto-detect files for a case
  python tools/generate_regression_tests.py --case-id 900 --auto-detect

  # Generate tests for multiple cases
  python tools/generate_regression_tests.py --case-ids 600,900,960

  # Generate tests for all defined cases
  python tools/generate_regression_tests.py --all-cases

  # Custom validation thresholds
  python tools/generate_regression_tests.py --case-id 600 \\
      --max-abs-error 0.5 --max-rel-error 0.03
        """,
    )

    parser.add_argument(
        "--case-id", type=str, help="Single case ID (e.g., '600', '900')"
    )

    parser.add_argument(
        "--case-ids", type=str, nargs="+", help="Multiple case IDs (space-separated)"
    )

    parser.add_argument(
        "--all-cases",
        action="store_true",
        help="Generate tests for all standard ASHRAE 140 cases",
    )

    parser.add_argument(
        "--fluxion-output", type=str, help="Path to Fluxion output JSON file"
    )

    parser.add_argument(
        "--ep-output", type=str, help="Path to EnergyPlus reference JSON file"
    )

    parser.add_argument(
        "--test-name",
        type=str,
        default="test_regression",
        help="Name for the generated test function",
    )

    parser.add_argument(
        "--auto-detect",
        action="store_true",
        help="Auto-detect Fluxion and EP output files",
    )

    parser.add_argument(
        "--base-dir",
        type=str,
        default="refdata/ep",
        help="Base directory containing reference data (default: refdata/ep)",
    )

    parser.add_argument(
        "--output-file",
        type=str,
        default="tests/physics/ashrae_140_regression.rs",
        help="Output test file path",
    )

    parser.add_argument(
        "--max-abs-error",
        type=float,
        default=DEFAULT_MAX_ABS_ERROR,
        help=f"Maximum absolute error (default: {DEFAULT_MAX_ABS_ERROR})",
    )

    parser.add_argument(
        "--max-rel-error",
        type=float,
        default=DEFAULT_MAX_REL_ERROR,
        help=f"Maximum relative error (default: {DEFAULT_MAX_REL_ERROR})",
    )

    parser.add_argument(
        "--min-correlation",
        type=float,
        default=DEFAULT_MIN_CORRELATION,
        help=f"Minimum correlation coefficient (default: {DEFAULT_MIN_CORRELATION})",
    )

    parser.add_argument(
        "--max-rmse",
        type=float,
        default=DEFAULT_MAX_RMSE,
        help=f"Maximum RMSE (default: {DEFAULT_MAX_RMSE})",
    )

    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Output generated test to stdout instead of file",
    )

    args = parser.parse_args()

    # Handle single case with explicit files
    if args.case_id and args.fluxion_output and args.ep_output:
        test_code = generate_rust_test(
            args.case_id,
            args.fluxion_output,
            args.ep_output,
            args.test_name,
            args.max_abs_error,
            args.max_rel_error,
            args.min_correlation,
            args.max_rmse,
        )

        if args.stdout:
            print(
                "\n".join(
                    [
                        generate_module_docstring(),
                        generate_test_file_header(),
                        test_code,
                    ]
                )
            )
        else:
            output = [
                generate_module_docstring(),
                generate_test_file_header(),
                test_code,
            ]
            Path(args.output_file).parent.mkdir(parents=True, exist_ok=True)
            with open(args.output_file, "w") as f:
                f.write("\n".join(output))

            print(f"Generated regression test: {args.test_name}")
            print(f"  Case ID: {args.case_id}")
            print(f"  Fluxion output: {args.fluxion_output}")
            print(f"  EP output: {args.ep_output}")
            print(f"  Output file: {args.output_file}")

        return

    # Handle single case with auto-detect
    if args.case_id and args.auto_detect:
        fluxion_file, ep_file = auto_detect_case_files(args.case_id, args.base_dir)

        if fluxion_file is None or ep_file is None:
            print(
                f"Error: Could not find output files for case {args.case_id}",
                file=sys.stderr,
            )
            if fluxion_file is None:
                print("  Fluxion output not found", file=sys.stderr)
                print("  Searched patterns:", file=sys.stderr)
                print("    fluxion_{args.case_id}.json", file=sys.stderr)
                print("    Case_{args.case_id}_fluxion.json", file=sys.stderr)
                print("    fluxion_output_{args.case_id}.json", file=sys.stderr)
            if ep_file is None:
                print("  EP output not found", file=sys.stderr)
                print("  Searched patterns:", file=sys.stderr)
                print("    Case_{args.case_id}_results.json", file=sys.stderr)
                print("    ep_{args.case_id}.json", file=sys.stderr)
                print("    Case_{args.case_id}_ep.json", file=sys.stderr)
            sys.exit(1)

        test_name = f"test_case_{args.case_id}_regression"
        test_code = generate_rust_test(
            args.case_id,
            fluxion_file,
            ep_file,
            test_name,
            args.max_abs_error,
            args.max_rel_error,
            args.min_correlation,
            args.max_rmse,
        )

        if args.stdout:
            print(
                "\n".join(
                    [
                        generate_module_docstring(),
                        generate_test_file_header(),
                        test_code,
                    ]
                )
            )
        else:
            output = [
                generate_module_docstring(),
                generate_test_file_header(),
                test_code,
            ]
            Path(args.output_file).parent.mkdir(parents=True, exist_ok=True)
            with open(args.output_file, "w") as f:
                f.write("\n".join(output))

            print(f"Generated regression test: {test_name}")
            print(f"  Case ID: {args.case_id}")
            print(f"  Fluxion output: {fluxion_file}")
            print(f"  EP output: {ep_file}")
            print(f"  Output file: {args.output_file}")

        return

    # Handle multiple cases
    if args.case_ids:
        generate_all_cases_test_file(args.case_ids, args.base_dir, args.output_file)
        return

    # Handle all standard cases
    if args.all_cases:
        standard_cases = [
            "600",
            "610",
            "620",
            "630",
            "640",
            "650",
            "600FF",
            "650FF",
            "900",
            "910",
            "920",
            "930",
            "940",
            "950",
            "900FF",
            "950FF",
            "960",
            "195",
        ]
        generate_all_cases_test_file(standard_cases, args.base_dir, args.output_file)
        return

    # No arguments - show help
    parser.print_help()
    sys.exit(1)


if __name__ == "__main__":
    main()
