"""
TOPSIS Multi-Criteria Decision Making Module

This module implements TOPSIS (Technique for Order of Preference by Similarity to Ideal Solution)
for selecting optimal designs from Pareto frontiers generated by multi-objective optimization.

TOPSIS is particularly suited for building energy optimization where competing objectives include:
- Energy Consumption (EC)
- Thermal Discomfort Hours Percentage (TDHP)
- Life-Cycle Cost (LCC)
- Life-Cycle Carbon Emissions (LCCO2)

Usage:
    from tools.topsis import TOPSISSolver, ObjectiveWeights

    # Define weights for each objective (must sum to 1.0)
    weights = ObjectiveWeights(
        ec=0.35,      # Energy Consumption
        tdhp=0.25,    # Thermal Discomfort Hours Percentage
        lcc=0.25,     # Life-Cycle Cost
        lcco2=0.15    # Life-Cycle Carbon Emissions
    )

    # Create solver
    solver = TOPSISSolver(weights)

    # Solve from Pareto frontier
    # Each row: [EC, TDHP, LCC, LCCO2]
    pareto_frontier = [
        [100.0, 5.2, 50000, 72.3],
        [120.0, 3.1, 45000, 85.0],
        [95.0, 6.8, 55000, 65.0],
    ]

    best_solution = solver.solve(pareto_frontier)
    print(f"Optimal solution: {best_solution}")

    # Get ranking of all alternatives
    rankings = solver.get_rankings(pareto_frontier)
"""

import logging
from dataclasses import dataclass
from typing import List, Optional, Tuple

import numpy as np

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class ObjectiveWeights:
    """Weight coefficients for TOPSIS objectives.

    Weights should be positive and sum to 1.0 for proper normalization.
    Higher weight indicates more importance for that objective.
    """

    ec: float = 0.25
    tdhp: float = 0.25
    lcc: float = 0.25
    lcco2: float = 0.25

    def __post_init__(self):
        """Validate that weights sum to 1.0."""
        total = self.ec + self.tdhp + self.lcc + self.lcco2
        if not np.isclose(total, 1.0, atol=1e-6):
            raise ValueError(f"Objective weights must sum to 1.0, got {total:.4f}")
        if any(w < 0 for w in [self.ec, self.tdhp, self.lcc, self.lcco2]):
            raise ValueError("All weights must be non-negative")

    def to_list(self) -> List[float]:
        """Return weights as list [EC, TDHP, LCC, LCCO2]."""
        return [self.ec, self.tdhp, self.lcc, self.lcco2]


@dataclass
class TOPSISResult:
    """Result from TOPSIS analysis."""

    best_index: int
    best_alternative: np.ndarray
    closeness_scores: np.ndarray
    rankings: List[int]
    ideal_positive: np.ndarray
    ideal_negative: np.ndarray
    normalized_matrix: np.ndarray
    weights: ObjectiveWeights


class TOPSISSolver:
    """
    TOPSIS (Technique for Order of Preference by Similarity to Ideal Solution) solver.

    TOPSIS selects the alternative closest to the ideal positive solution and farthest
    from the ideal negative solution. The ideal positive solution is the best achievable
    value for each criterion, and the ideal negative is the worst.

    For building optimization:
    - EC (Energy Consumption): minimization objective (lower is better)
    - TDHP (Thermal Discomfort Hours Percentage): minimization objective
    - LCC (Life-Cycle Cost): minimization objective
    - LCCO2 (Life-Cycle Carbon Emissions): minimization objective
    """

    def __init__(
        self,
        weights: Optional[ObjectiveWeights] = None,
        objectives_are_benefit: Optional[List[bool]] = None,
    ):
        """
        Initialize TOPSIS solver.

        Args:
            weights: Weight coefficients for each objective.
                Defaults to equal weights if not provided.
            objectives_are_benefit: List of booleans indicating if each objective
                is a benefit (True) or cost (False). All objectives in this
                implementation are costs (minimization), so default is all False.
        """
        self.weights = weights or ObjectiveWeights()
        self.objectives_are_benefit = objectives_are_benefit or [
            False,
            False,
            False,
            False,
        ]

        if len(self.objectives_are_benefit) != 4:
            raise ValueError("Must specify benefit/cost for exactly 4 objectives")

    def _normalize_matrix(self, matrix: np.ndarray) -> np.ndarray:
        """
        Normalize the decision matrix using vector normalization.

        Args:
            matrix: Decision matrix of shape (n_alternatives, n_criteria)

        Returns:
            Normalized decision matrix
        """
        n_alternatives, n_criteria = matrix.shape
        normalized = np.zeros_like(matrix)

        for j in range(n_criteria):
            col = matrix[:, j]
            norm = np.sqrt(np.sum(col**2))
            if norm > 0:
                normalized[:, j] = col / norm
            else:
                normalized[:, j] = 0.0

        return normalized

    def _weighted_normalize(self, normalized: np.ndarray) -> np.ndarray:
        """
        Apply weights to normalized matrix.

        Args:
            normalized: Normalized decision matrix

        Returns:
            Weighted normalized matrix
        """
        weights = np.array(self.weights.to_list())
        return normalized * weights

    def _calculate_ideal_solutions(
        self, weighted_normalized: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculate ideal positive and ideal negative solutions.

        Args:
            weighted_normalized: Weighted normalized decision matrix

        Returns:
            Tuple of (ideal_positive, ideal_negative) arrays
        """
        n_alternatives, n_criteria = weighted_normalized.shape

        ideal_positive = np.zeros(n_criteria)
        ideal_negative = np.zeros(n_criteria)

        for j in range(n_criteria):
            if self.objectives_are_benefit[j]:
                ideal_positive[j] = np.max(weighted_normalized[:, j])
                ideal_negative[j] = np.min(weighted_normalized[:, j])
            else:
                ideal_positive[j] = np.min(weighted_normalized[:, j])
                ideal_negative[j] = np.max(weighted_normalized[:, j])

        return ideal_positive, ideal_negative

    def _calculate_distances(
        self,
        weighted_normalized: np.ndarray,
        ideal_positive: np.ndarray,
        ideal_negative: np.ndarray,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculate Euclidean distances from ideal solutions.

        Args:
            weighted_normalized: Weighted normalized decision matrix
            ideal_positive: Ideal positive solution
            ideal_negative: Ideal negative solution

        Returns:
            Tuple of (distances_to_positive, distances_to_negative) arrays
        """
        n_alternatives = weighted_normalized.shape[0]

        dist_positive = np.zeros(n_alternatives)
        dist_negative = np.zeros(n_alternatives)

        for i in range(n_alternatives):
            dist_positive[i] = np.sqrt(
                np.sum((weighted_normalized[i] - ideal_positive) ** 2)
            )
            dist_negative[i] = np.sqrt(
                np.sum((weighted_normalized[i] - ideal_negative) ** 2)
            )

        return dist_positive, dist_negative

    def _calculate_closeness(
        self, dist_positive: np.ndarray, dist_negative: np.ndarray
    ) -> np.ndarray:
        """
        Calculate closeness coefficients.

        Args:
            dist_positive: Distances to ideal positive solution
            dist_negative: Distances to ideal negative solution

        Returns:
            Closeness coefficients array
        """
        closeness = np.zeros(len(dist_positive))

        for i in range(len(dist_positive)):
            denominator = dist_positive[i] + dist_negative[i]
            if denominator > 0:
                closeness[i] = dist_negative[i] / denominator
            else:
                closeness[i] = 0.0

        return closeness

    def solve(self, decision_matrix: List[List[float]]) -> TOPSISResult:
        """
        Solve TOPSIS for the given decision matrix.

        Args:
            decision_matrix: List of lists representing the decision matrix.
                Each row is an alternative, each column is a criterion.
                Columns should be ordered: [EC, TDHP, LCC, LCCO2]

        Returns:
            TOPSISResult containing the optimal solution and analysis details
        """
        matrix = np.array(decision_matrix)

        if matrix.ndim != 2:
            raise ValueError("Decision matrix must be 2-dimensional")
        if matrix.shape[1] != 4:
            raise ValueError(
                "Decision matrix must have exactly 4 columns (EC, TDHP, LCC, LCCO2)"
            )
        if matrix.shape[0] < 2:
            raise ValueError("Need at least 2 alternatives for TOPSIS")

        normalized = self._normalize_matrix(matrix)
        weighted_normalized = self._weighted_normalize(normalized)
        ideal_positive, ideal_negative = self._calculate_ideal_solutions(
            weighted_normalized
        )
        dist_positive, dist_negative = self._calculate_distances(
            weighted_normalized, ideal_positive, ideal_negative
        )
        closeness = self._calculate_closeness(dist_positive, dist_negative)

        best_index = int(np.argmax(closeness))
        sorted_indices = np.argsort(-closeness)
        rankings = np.zeros(len(closeness), dtype=int)
        for rank, idx in enumerate(sorted_indices, start=1):
            rankings[idx] = rank

        result = TOPSISResult(
            best_index=best_index,
            best_alternative=matrix[best_index],
            closeness_scores=closeness,
            rankings=rankings.tolist(),
            ideal_positive=ideal_positive,
            ideal_negative=ideal_negative,
            normalized_matrix=weighted_normalized,
            weights=self.weights,
        )

        logger.info(f"TOPSIS solved: best alternative index = {best_index}")
        logger.info(f"Best alternative: {matrix[best_index]}")
        logger.info(f"Closeness score: {closeness[best_index]:.4f}")

        return result

    def get_rankings(self, decision_matrix: List[List[float]]) -> List[int]:
        """
        Get ranking of all alternatives.

        Args:
            decision_matrix: Decision matrix

        Returns:
            List of rankings (1 = best) for each alternative
        """
        result = self.solve(decision_matrix)
        return result.rankings

    def get_best_alternative(
        self, decision_matrix: List[List[float]]
    ) -> Tuple[int, List[float]]:
        """
        Get the best alternative from the decision matrix.

        Args:
            decision_matrix: Decision matrix

        Returns:
            Tuple of (best_index, best_alternative_values)
        """
        result = self.solve(decision_matrix)
        return result.best_index, result.best_alternative.tolist()


def create_pareto_visualization_data(
    pareto_frontier: List[List[float]],
    topsis_result: TOPSISResult,
    parameter_sets: Optional[List[List[float]]] = None,
) -> dict:
    """
    Create data for visualizing Pareto frontier with TOPSIS-selected optimal point.

    Args:
        pareto_frontier: The Pareto frontier solutions
        topsis_result: Result from TOPSIS analysis
        parameter_sets: Optional corresponding parameter values for each solution

    Returns:
        Dictionary with visualization data
    """
    pareto_array = np.array(pareto_frontier)
    n_solutions = pareto_array.shape[0]

    visualization = {
        "pareto_points": pareto_frontier,
        "topsis_selected_index": topsis_result.best_index,
        "topsis_selected_point": topsis_result.best_alternative.tolist(),
        "closeness_scores": topsis_result.closeness_scores.tolist(),
        "rankings": topsis_result.rankings,
        "ideal_positive": topsis_result.ideal_positive.tolist(),
        "ideal_negative": topsis_result.ideal_negative.tolist(),
        "weights": topsis_result.weights.to_list(),
    }

    if parameter_sets is not None:
        visualization["selected_parameters"] = parameter_sets[topsis_result.best_index]

    if pareto_array.shape[1] == 4:
        visualization["objective_ranges"] = {
            "EC": {
                "min": float(pareto_array[:, 0].min()),
                "max": float(pareto_array[:, 0].max()),
            },
            "TDHP": {
                "min": float(pareto_array[:, 1].min()),
                "max": float(pareto_array[:, 1].max()),
            },
            "LCC": {
                "min": float(pareto_array[:, 2].min()),
                "max": float(pareto_array[:, 2].max()),
            },
            "LCCO2": {
                "min": float(pareto_array[:, 3].min()),
                "max": float(pareto_array[:, 3].max()),
            },
        }

    return visualization


if __name__ == "__main__":
    print("TOPSIS Multi-Criteria Decision Making Demo")
    print("=" * 60)

    weights = ObjectiveWeights(ec=0.35, tdhp=0.25, lcc=0.25, lcco2=0.15)
    print(
        f"Objective weights: EC={weights.ec}, TDHP={weights.tdhp}, LCC={weights.lcc}, LCCO2={weights.lcco2}"
    )

    solver = TOPSISSolver(weights)

    pareto_frontier = [
        [100.0, 5.2, 50000, 72.3],
        [120.0, 3.1, 45000, 85.0],
        [95.0, 6.8, 55000, 65.0],
        [110.0, 4.5, 48000, 75.0],
        [105.0, 4.0, 52000, 70.0],
    ]

    print(f"\nPareto frontier ({len(pareto_frontier)} solutions):")
    print("  [EC, TDHP, LCC, LCCO2]")
    for i, solution in enumerate(pareto_frontier):
        print(f"  {i}: {solution}")

    result = solver.solve(pareto_frontier)

    print(f"\nResults:")
    print(f"  Best alternative index: {result.best_index}")
    print(f"  Best alternative: {result.best_alternative}")
    print(f"  Closeness scores: {result.closeness_scores}")
    print(f"  Rankings: {result.rankings}")
    print(f"  Ideal positive: {result.ideal_positive}")
    print(f"  Ideal negative: {result.ideal_negative}")

    viz_data = create_pareto_visualization_data(pareto_frontier, result)
    print(f"\nVisualization data keys: {list(viz_data.keys())}")

    print("\n" + "=" * 60)
    print("Demo complete")
