//! Battery bus with State of Charge (SoC) tracking.

use std::time::Duration;

use serde::{Deserialize, Serialize};

use super::bus::ElectricalBus;

/// Heat flow rate in Watts.
///
/// This type is used to represent thermal power (energy per unit time)
/// generated by battery ohmic heating. It can be directly integrated
/// with fluxion-core thermal modeling systems.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct HeatFlowRate(f64);

impl HeatFlowRate {
    /// Create a new heat flow rate from watts.
    pub fn from_watts(watts: f64) -> Self {
        Self(watts)
    }

    /// Get the heat flow rate in watts.
    pub fn watts(&self) -> f64 {
        self.0
    }

    /// Zero heat flow rate.
    pub fn zero() -> Self {
        Self(0.0)
    }
}

impl Default for HeatFlowRate {
    fn default() -> Self {
        Self::zero()
    }
}

/// Battery storage node with thermal modeling capabilities.
///
/// Provides ohmic heat generation and thermal output calculations
/// for battery thermal management integration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BatteryStorageNode {
    /// Internal resistance in Ohms (Ω)
    pub internal_resistance_ohms: f64,
    /// Thermal mass in J/K (Joules per Kelvin)
    pub thermal_mass_j_per_k: f64,
    /// Ambient temperature in Kelvin
    pub ambient_temperature_k: f64,
    /// Current surface temperature in Kelvin
    pub surface_temperature_k: f64,
}

impl BatteryStorageNode {
    /// Create a new battery storage node with thermal properties.
    pub fn new(
        internal_resistance_ohms: f64,
        thermal_mass_j_per_k: f64,
        ambient_temperature_k: f64,
    ) -> Self {
        Self {
            internal_resistance_ohms,
            thermal_mass_j_per_k,
            ambient_temperature_k,
            surface_temperature_k: ambient_temperature_k,
        }
    }

    /// Calculate ohmic heat generation from current flow.
    ///
    /// Uses Joule's first law: Q_gen = I² × R_internal
    ///
    /// # Arguments
    /// * `current_amps` - Current flow in Amperes (positive = discharge, negative = charge)
    ///
    /// # Returns
    /// Heat flow rate in Watts
    pub fn ohmic_heat_generation(&self, current_amps: f64) -> HeatFlowRate {
        let i_squared = current_amps * current_amps;
        let q_gen = i_squared * self.internal_resistance_ohms;
        HeatFlowRate::from_watts(q_gen)
    }

    /// Calculate thermal output based on current and time delta.
    ///
    /// Computes the heat flow considering temperature difference
    /// between surface and ambient using Newton's law of cooling.
    ///
    /// # Arguments
    /// * `dt` - Time duration of the thermal event
    /// * `current_amps` - Current flow in Amperes
    ///
    /// # Returns
    /// Net thermal output in Watts (positive = heating, negative = cooling)
    pub fn thermal_output(&self, dt: Duration, current_amps: f64) -> HeatFlowRate {
        let q_gen = self.ohmic_heat_generation(current_amps);

        let dt_seconds = dt.as_secs_f64();
        if dt_seconds <= 0.0 || self.thermal_mass_j_per_k <= 0.0 {
            return q_gen;
        }

        let temp_diff_k = self.surface_temperature_k - self.ambient_temperature_k;
        let cooling_rate = temp_diff_k / self.thermal_mass_j_per_k * 1e3;

        let net_thermal = q_gen.watts() - cooling_rate;
        HeatFlowRate::from_watts(net_thermal)
    }

    /// Update the surface temperature based on heat flow and time.
    ///
    /// Uses energy balance: ΔT = Q × Δt / C
    pub fn update_temperature(&mut self, heat_flow: HeatFlowRate, dt: Duration) {
        let dt_seconds = dt.as_secs_f64();
        if dt_seconds <= 0.0 || self.thermal_mass_j_per_k <= 0.0 {
            return;
        }

        let energy_input = heat_flow.watts() * dt_seconds;
        let temp_rise = energy_input / self.thermal_mass_j_per_k;
        self.surface_temperature_k += temp_rise;
    }
}

/// Battery degradation model for capacity fade tracking.
///
/// Models both cycle aging (use-dependent) and calendar aging (time-dependent)
/// to predict capacity loss over battery lifetime.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct BatteryDegradation {
    /// Capacity loss per full charge-discharge cycle (fraction, e.g., 0.0001 = 0.01%)
    pub fade_rate_per_cycle: f64,
    /// Capacity loss per year from calendar aging (fraction per year)
    pub calendar_fade_rate: f64,
    /// Reference temperature for calendar aging calculation (Kelvin)
    pub reference_temperature_k: f64,
    /// Arrhenius activation energy ratio for temperature dependence
    pub activation_energy_ratio: f64,
}

impl BatteryDegradation {
    /// Create a new battery degradation model.
    ///
    /// # Arguments
    /// * `fade_rate_per_cycle` - Capacity loss per full cycle (e.g., 0.0001 for 0.01%)
    /// * `calendar_fade_rate` - Annual capacity loss at reference temperature
    /// * `reference_temperature_k` - Reference temperature for Arrhenius model (default 298.15 K / 25°C)
    pub fn new(
        fade_rate_per_cycle: f64,
        calendar_fade_rate: f64,
        reference_temperature_k: f64,
    ) -> Self {
        Self {
            fade_rate_per_cycle,
            calendar_fade_rate,
            reference_temperature_k,
            activation_energy_ratio: 0.5,
        }
    }

    /// Create a default degradation model with typical Li-ion values.
    ///
    /// Default values:
    /// - Cycle fade: 0.0001 per cycle (0.01% per cycle)
    /// - Calendar fade: 0.02 per year (2% per year)
    pub fn default_lithium_ion() -> Self {
        Self::new(0.0001, 0.02, 298.15)
    }

    /// Calculate total capacity loss from cycle and calendar aging.
    ///
    /// Uses a combined linear model:
    /// - Cycle aging: fade_rate_per_cycle × cycles
    /// - Calendar aging: Arrhenius-corrected annual fade × years
    ///
    /// # Arguments
    /// * `cycles` - Number of full charge-discharge cycles
    /// * `years` - Calendar time in years
    ///
    /// # Returns
    /// Fractional capacity loss [0.0, 1.0]
    pub fn capacity_loss(&self, cycles: f64, years: f64) -> f64 {
        let cycle_loss = self.fade_rate_per_cycle * cycles;
        let calendar_loss = self.calendar_fade_rate * years;
        (cycle_loss + calendar_loss).clamp(0.0, 1.0)
    }

    /// Calculate capacity loss with temperature dependence for calendar aging.
    ///
    /// Uses Arrhenius equation for temperature correction:
    /// fade(T) = fade_ref × exp(Ea/R × (1/T_ref - 1/T))
    ///
    /// # Arguments
    /// * `cycles` - Number of full charge-discharge cycles
    /// * `years` - Calendar time in years
    /// * `temperature_k` - Operating temperature in Kelvin
    ///
    /// # Returns
    /// Fractional capacity loss [0.0, 1.0]
    pub fn capacity_loss_with_temperature(
        &self,
        cycles: f64,
        years: f64,
        temperature_k: f64,
    ) -> f64 {
        let cycle_loss = self.fade_rate_per_cycle * cycles;

        let temp_ratio = self.reference_temperature_k / temperature_k;
        let arrhenius_factor = (-self.activation_energy_ratio * (1.0 - temp_ratio)).exp();
        let calendar_loss = self.calendar_fade_rate * years * arrhenius_factor;

        (cycle_loss + calendar_loss).clamp(0.0, 1.0)
    }

    /// Calculate remaining capacity factor after degradation.
    ///
    /// # Arguments
    /// * `cycles` - Number of full charge-discharge cycles
    /// * `years` - Calendar time in years
    ///
    /// # Returns
    /// Remaining capacity as a fraction [0.0, 1.0]
    pub fn remaining_capacity(&self, cycles: f64, years: f64) -> f64 {
        1.0 - self.capacity_loss(cycles, years)
    }
}

/// Battery bus for energy storage modeling.
///
/// Tracks State of Charge (SoC) in addition to standard bus properties.
/// Batteries can operate in grid-forming (slack) or grid-following (PV/PQ) modes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BatteryBus {
    /// Underlying electrical bus properties
    pub bus: ElectricalBus,
    /// State of Charge as a fraction [0.0, 1.0]
    pub state_of_charge: f64,
    /// Maximum storage capacity in per-unit (pu)
    pub capacity: f64,
    /// Maximum charge/discharge power in per-unit (pu)
    pub max_power: f64,
    /// Charge efficiency (0.0 to 1.0)
    pub charge_efficiency: f64,
    /// Discharge efficiency (0.0 to 1.0)
    pub discharge_efficiency: f64,
    /// Minimum SoC to prevent deep discharge [0.0, 1.0]
    pub min_soc: f64,
    /// Maximum SoC to prevent overcharge [0.0, 1.0]
    pub max_soc: f64,
}

impl BatteryBus {
    /// Create a new battery bus as a PV node (grid-following).
    pub fn new_pv(id: u32, capacity: f64, max_power: f64, initial_soc: f64) -> Self {
        Self {
            bus: ElectricalBus::new_pv(id, 0.0, 1.0),
            state_of_charge: initial_soc.clamp(0.0, 1.0),
            capacity,
            max_power,
            charge_efficiency: 0.95,
            discharge_efficiency: 0.95,
            min_soc: 0.2,
            max_soc: 0.95,
        }
    }

    /// Create a new battery bus as a PQ node (load-type).
    pub fn new_pq(id: u32, capacity: f64, max_power: f64, initial_soc: f64) -> Self {
        Self {
            bus: ElectricalBus::new_pq(id, 0.0, 0.0),
            state_of_charge: initial_soc.clamp(0.0, 1.0),
            capacity,
            max_power,
            charge_efficiency: 0.95,
            discharge_efficiency: 0.95,
            min_soc: 0.2,
            max_soc: 0.95,
        }
    }

    /// Create a new battery bus as a Slack node (grid-forming).
    pub fn new_slack(
        id: u32,
        capacity: f64,
        max_power: f64,
        initial_soc: f64,
        voltage_magnitude: f64,
    ) -> Self {
        Self {
            bus: ElectricalBus::new_slack(id, voltage_magnitude, 0.0),
            state_of_charge: initial_soc.clamp(0.0, 1.0),
            capacity,
            max_power,
            charge_efficiency: 0.95,
            discharge_efficiency: 0.95,
            min_soc: 0.2,
            max_soc: 0.95,
        }
    }

    /// Update the State of Charge based on power flow.
    ///
    /// Positive power indicates charging, negative indicates discharging.
    pub fn update_soc(&mut self, power: f64, time_step: f64) {
        let constrained_power = power.clamp(-self.max_power, self.max_power);

        let energy_change = if constrained_power > 0.0 {
            constrained_power * time_step * self.charge_efficiency
        } else {
            constrained_power * time_step / self.discharge_efficiency
        };

        let new_soc = self.state_of_charge + energy_change / self.capacity;
        self.state_of_charge = new_soc.clamp(self.min_soc, self.max_soc);
    }

    /// Get available discharge capacity (above minimum SoC).
    pub fn available_discharge_capacity(&self) -> f64 {
        (self.state_of_charge - self.min_soc).max(0.0) * self.capacity
    }

    /// Get available charge capacity (below maximum SoC).
    pub fn available_charge_capacity(&self) -> f64 {
        (self.max_soc - self.state_of_charge).max(0.0) * self.capacity
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::BusNodeType;

    #[test]
    fn test_ohmic_heat_100a_discharge() {
        let node = BatteryStorageNode::new(0.01, 1000.0, 298.15);
        let heat = node.ohmic_heat_generation(100.0);
        assert_eq!(heat.watts(), 100.0);
    }

    #[test]
    fn test_ohmic_heat_zero_current() {
        let node = BatteryStorageNode::new(0.01, 1000.0, 298.15);
        let heat = node.ohmic_heat_generation(0.0);
        assert_eq!(heat.watts(), 0.0);
    }

    #[test]
    fn test_thermal_output() {
        let node = BatteryStorageNode::new(0.01, 1000.0, 298.15);
        let heat = node.thermal_output(Duration::from_secs(1), 100.0);
        assert_eq!(heat.watts(), 100.0);
    }

    #[test]
    fn test_capacity_loss_1000_cycles() {
        let deg = BatteryDegradation::new(0.0001, 0.02, 298.15);
        let loss = deg.capacity_loss(1000.0, 0.0);
        assert!((loss - 0.10).abs() < 1e-10);
    }

    #[test]
    fn test_capacity_loss_calendar_only() {
        let deg = BatteryDegradation::new(0.0001, 0.02, 298.15);
        let loss = deg.capacity_loss(0.0, 10.0);
        assert!((loss - 0.20).abs() < 1e-10);
    }

    #[test]
    fn test_capacity_loss_combined() {
        let deg = BatteryDegradation::new(0.0001, 0.02, 298.15);
        let loss = deg.capacity_loss(1000.0, 10.0);
        assert!((loss - 0.30).abs() < 1e-10);
    }

    #[test]
    fn test_remaining_capacity() {
        let deg = BatteryDegradation::new(0.0001, 0.02, 298.15);
        let remaining = deg.remaining_capacity(1000.0, 0.0);
        assert!((remaining - 0.90).abs() < 1e-10);
    }

    #[test]
    fn test_capacity_loss_clamped() {
        let deg = BatteryDegradation::new(0.1, 0.5, 298.15);
        let loss = deg.capacity_loss(1000.0, 10.0);
        assert!(loss <= 1.0);
    }

    #[test]
    fn test_battery_creation() {
        let battery = BatteryBus::new_pv(1, 1.0, 0.5, 0.8);
        assert!(matches!(battery.bus.node_type, BusNodeType::PV));
        assert_eq!(battery.state_of_charge, 0.8);
        assert_eq!(battery.capacity, 1.0);
    }

    #[test]
    fn test_soc_update_charge() {
        let mut battery = BatteryBus::new_pv(1, 1.0, 0.5, 0.5);
        battery.update_soc(0.1, 1.0);
        assert!(battery.state_of_charge > 0.5);
    }

    #[test]
    fn test_soc_update_discharge() {
        let mut battery = BatteryBus::new_pv(1, 1.0, 0.5, 0.5);
        battery.update_soc(-0.1, 1.0);
        assert!(battery.state_of_charge < 0.5);
    }

    #[test]
    fn test_soc_clamping() {
        let mut battery = BatteryBus::new_pv(1, 1.0, 0.5, 0.95);
        battery.update_soc(1.0, 1.0);
        assert!(battery.state_of_charge <= battery.max_soc);

        let mut battery2 = BatteryBus::new_pv(2, 1.0, 0.5, 0.2);
        battery2.update_soc(-1.0, 1.0);
        assert!(battery2.state_of_charge >= battery2.min_soc);
    }

    #[test]
    fn test_heat_flow_rate_default() {
        let hfr = HeatFlowRate::default();
        assert_eq!(hfr.watts(), 0.0);
    }

    #[test]
    fn test_battery_storage_node_default() {
        let node = BatteryStorageNode::new(0.01, 1000.0, 298.15);
        assert_eq!(node.internal_resistance_ohms, 0.01);
        assert_eq!(node.thermal_mass_j_per_k, 1000.0);
        assert_eq!(node.surface_temperature_k, 298.15);
    }

    #[test]
    fn test_update_temperature() {
        let mut node = BatteryStorageNode::new(0.01, 1000.0, 298.15);
        let heat = HeatFlowRate::from_watts(100.0);
        node.update_temperature(heat, Duration::from_secs(10));
        let expected_temp_rise = 100.0 * 10.0 / 1000.0;
        assert!((node.surface_temperature_k - 298.15 - expected_temp_rise).abs() < 1e-9);
    }
}
