/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * JavaScript-accessible BatchOracle wrapper for high-throughput building energy evaluation.
 *
 * This class provides a JavaScript interface to Fluxion's BatchOracle, enabling
 * optimization workflows in BIM tools (Autodesk, Speckle, Trimble) and parametric
 * analysis platforms.
 *
 * # TypeScript Example
 * ```typescript
 * import { BatchOracle } from '@fluxion/native';
 *
 * // Create oracle instance
 * const oracle = new BatchOracle();
 *
 * // Evaluate multiple configurations in parallel
 * const population = [
 *   [1.5, 20.0, 24.0], // [window_u_value, heating_setpoint, cooling_setpoint]
 *   [2.0, 20.0, 24.0],
 *   [2.5, 20.0, 24.0]
 * ];
 *
 * // Evaluate without surrogates (physics-based)
 * const physicsResults = oracle.evaluatePopulation(population, false);
 *
 * // Evaluate with surrogates (AI-accelerated, ~10x faster)
 * const aiResults = oracle.evaluatePopulation(population, true);
 *
 * console.log(`EUI values (physics): ${physicsResults}`);
 * console.log(`EUI values (AI): ${aiResults}`);
 * ```
 *
 * # Performance Characteristics
 * - **Physics-based**: ~1,000 configs/sec on 8-core CPU
 * - **AI-accelerated**: ~10,000+ configs/sec with GPU surrogates
 * - **Latency**: <100ms for single configuration (8760 timesteps)
 * - **Memory**: Minimal allocations via CTA buffer reuse
 *
 * # Parameter Constraints
 * - Window U-value: 0.1–5.0 W/m²K
 * - Heating setpoint: 15.0–25.0 °C
 * - Cooling setpoint: 22.0–32.0 °C
 * - Heating setpoint must be less than cooling setpoint
 */
export declare class BatchOracle {
  /**
   * Create a new BatchOracle instance with default ASHRAE 600 configuration.
   *
   * This initializes the oracle with a base thermal model suitable for
   * parametric studies and optimization workflows.
   *
   * # TypeScript Example
   * ```typescript
   * import { BatchOracle } from '@fluxion/native';
   * const oracle = new BatchOracle();
   * ```
   *
   * # Returns
   * A new `BatchOracle` instance ready for evaluation
   *
   * # Throws
   * - `FluxionError` if initialization fails (e.g., model loading, surrogate initialization)
   */
  constructor()
  /**
   * Evaluate a population of building design configurations in parallel.
   *
   * This is the critical "hot loop" for optimization. The function uses Rayon for
   * multi-threaded evaluation and can process 10,000+ configurations per second.
   *
   * # Arguments
   * * `population` - Array of parameter arrays. Each inner array should contain at least:
   *   - `[0]`: Window U-value (W/m²K, range: 0.1-5.0)
   *   - `[1]`: Heating setpoint (°C, range: 15-25)
   *   - `[2]`: Cooling setpoint (°C, range: 22-32)
   * * `use_surrogates` - If true, use neural network surrogates for faster evaluation;
   *   if false, use analytical physics calculations.
   *
   * # Returns
   * Array of EUI values (kWh/m²/yr) for each candidate configuration.
   * Invalid configurations return `NaN`.
   */
  evaluatePopulation(population: Array<Array<number>>, useSurrogates: boolean): Array<number>
  /**
   * Validate building parameters against physical constraints.
   *
   * # Arguments
   * * `params` - Parameter array containing at least:
   *   - `[0]`: Window U-value (W/m²K, range: 0.1-5.0)
   *   - `[1]`: Heating setpoint (°C, range: 15-25)
   *   - `[2]`: Cooling setpoint (°C, range: 22-32)
   *
   * # Throws
   * - `ValidationError` if parameters are out of valid ranges
   */
  validateParameters(params: Array<number>): void
}

/**
 * JavaScript-accessible BuildingParameters with validation.
 *
 * This class provides named properties for building design parameters, improving
 * type safety and reducing misuse compared to raw number arrays.
 *
 * # TypeScript Example
 * ```typescript
 * import { BuildingParameters } from '@fluxion/native';
 *
 * // Create parameters with validation
 * const params = new BuildingParameters(1.5, 20.0, 24.0);
 *
 * // Access properties
 * console.log(`Window U-value: ${params.windowUValue} W/m²K`);
 * console.log(`Heating setpoint: ${params.heatingSetpoint}°C`);
 * console.log(`Cooling setpoint: ${params.coolingSetpoint}°C`);
 *
 * // Convert to array for backward compatibility
 * const array = params.toVec();
 * console.log(`As array: ${array}`); // [1.5, 20.0, 24.0]
 * ```
 *
 * # Field Constraints
 * - `windowUValue`: 0.1–5.0 W/m²K
 * - `heatingSetpoint`: 15.0–25.0 °C
 * - `coolingSetpoint`: 22.0–32.0 °C
 * - Heating setpoint must be less than cooling setpoint
 *
 * # Typical Values
 * - Window U-value: 1.5 (double-glazed low-E) to 5.0 (single glass) W/m²K
 * - Heating setpoint: 20.0 °C for office buildings
 * - Cooling setpoint: 24.0 °C for office buildings
 */
export declare class BuildingParameters {
  /**
   * Create new BuildingParameters with validation.
   *
   * # TypeScript Example
   * ```typescript
   * import { BuildingParameters } from '@fluxion/native';
   *
   * // Valid parameters
   * const params = new BuildingParameters(1.5, 20.0, 24.0);
   *
   * // Invalid parameters - will throw ValidationError
   * const invalid = new BuildingParameters(6.0, 20.0, 24.0); // U-value too high
   * ```
   *
   * # Arguments
   * * `windowUValue` - Window U-value (thermal transmittance) in W/m²K (range: 0.1-5.0)
   * * `heatingSetpoint` - Heating setpoint temperature in °C (range: 15.0-25.0)
   * * `coolingSetpoint` - Cooling setpoint temperature in °C (range: 22.0-32.0)
   *
   * # Throws
   * - `ValidationError` if parameters are out of valid ranges
   */
  constructor(windowUValue: number, heatingSetpoint: number, coolingSetpoint: number)
  /**
   * Get window U-value (thermal transmittance) in W/m²K.
   *
   * Range: 0.1–5.0 W/m²K
   * Typical values: Single glass (5.0) to triple-pane low-E (0.1)
   */
  get windowUValue(): number
  /**
   * Get heating setpoint temperature in °C.
   *
   * Range: 15.0–25.0 °C
   * Typical value: 20.0 °C for office buildings
   */
  get heatingSetpoint(): number
  /**
   * Get cooling setpoint temperature in °C.
   *
   * Range: 22.0–32.0 °C
   * Typical value: 24.0 °C for office buildings
   */
  get coolingSetpoint(): number
  /**
   * Convert parameters to array for backward compatibility.
   *
   * Returns array in format: `[window_u_value, heating_setpoint, cooling_setpoint]`
   *
   * # TypeScript Example
   * ```typescript
   * const params = new BuildingParameters(1.5, 20.0, 24.0);
   * const array = params.toVec();
   *
   * // Use with BatchOracle
   * const oracle = new BatchOracle();
   * const population = [array, [2.0, 20.0, 24.0]];
   * const results = oracle.evaluatePopulation(population, false);
   * ```
   */
  toVec(): Array<number>
}

/**
 * Base error class for all Fluxion errors.
 *
 * This is the parent class for all specific Fluxion error types and can be used
 * for catch-all error handling.
 *
 * # TypeScript Example
 * ```typescript
 * try {
 *   const oracle = new BatchOracle();
 *   const results = oracle.evaluatePopulation(population, false);
 * } catch (error) {
 *   if (error instanceof FluxionError) {
 *     console.error('Fluxion error:', error.message);
 *   } else {
 *     throw error;
 *   }
 * }
 * ```
 */
export declare class FluxionError {
  /** Create a new FluxionError with a message. */
  constructor(message: string)
  /** Get the error message. */
  get message(): string
}

export declare class FmiExporter {
  constructor()
  exportFmu(path: string, zonesJson: string, stepSizeSec: number): void
}

export declare class GbXmlExporter {
  constructor()
  exportGbXml(schemaJson: string, path: string): void
}

export declare class OsmExporter {
  constructor()
  exportOsm(schemaJson: string, path: string): void
}

/** Error thrown when physics simulation fails. */
export declare class SimulationError {
  /** Create a new SimulationError with a message. */
  constructor(message: string)
  /** Get the error message. */
  get message(): string
}

/**
 * JavaScript-accessible StateExtractor for ML training data extraction.
 *
 * This class provides zero-copy access to simulation state matrices, enabling
 * high-performance ML training without JSON/CSV serialization bottlenecks.
 *
 * # TypeScript Example
 * ```typescript
 * import { StateExtractor } from '@fluxion/native';
 *
 * // Create extractor with ASHRAE 600 base configuration
 * const extractor = new StateExtractor();
 *
 * // Configure for multi-zone extraction
 * extractor.configure({ numZones: 3 });
 *
 * // Run simulation and extract state matrices
 * const result = extractor.runSimulation(1, false);
 *
 * // Access zero-copy typed arrays (no serialization!)
 * console.log(`Zone temperatures: ${result.zoneTemperatures.length} timesteps`);
 * console.log(`Timestep 0, Zone 0: ${result.zoneTemperatures[0]}`);
 * ```
 *
 * # Performance Characteristics
 * - **JSON/CSV bottleneck**: Traditional approach requires ~50-200ms for serialization
 * - **Zero-copy extraction**: Direct typed array access, ~0.1ms overhead
 * - **Speedup**: 500-2000x faster for large simulations
 */
export declare class StateExtractor {
  /**
   * Create a new StateExtractor with default ASHRAE 600 configuration.
   *
   * # TypeScript Example
   * ```typescript
   * import { StateExtractor } from '@fluxion/native';
   * const extractor = new StateExtractor();
   * ```
   */
  constructor()
  /**
   * Configure the extractor for specific simulation parameters.
   *
   * # Arguments
   * * `num_zones` - Number of thermal zones (default: 1)
   */
  configure(numZones: number): void
  /**
   * Run simulation and extract state matrices with zero-copy access.
   *
   * This is the critical method for ML training - it runs the simulation and
   * returns state matrices as typed arrays that can be passed directly to
   * ML frameworks without JSON/CSV serialization.
   *
   * # Arguments
   * * `years` - Number of years to simulate (1-5 typical)
   * * `use_surrogates` - If true, use AI surrogates for faster evaluation
   *
   * # Returns
   * StateMatrices object containing typed arrays for each state variable:
   * - `zoneTemperatures`: Zone air temperatures [timesteps x num_zones]
   * - `massTemperatures`: Thermal mass temperatures [timesteps x num_zones]
   * - `heatingLoads`: Heating energy demand [timesteps]
   * - `coolingLoads`: Cooling energy demand [timesteps]
   * - `solarGains`: Solar heat gains [timesteps x num_zones]
   */
  runSimulation(years: number, useSurrogates: boolean): StateMatrices
  /**
   * Extract only zone temperatures (lightweight extraction for simple ML models).
   *
   * This is an optimized method for cases where only zone temperatures are needed,
   * avoiding the overhead of extracting all state matrices.
   *
   * # Arguments
   * * `years` - Number of years to simulate
   * * `use_surrogates` - If true, use AI surrogates
   *
   * # Returns
   * Flat array of zone temperatures [timesteps x num_zones]
   */
  extractZoneTemperatures(years: number, useSurrogates: boolean): Array<number>
}

/**
 * Container for extracted state matrices.
 *
 * All fields are typed arrays (Float64Array in JavaScript) enabling
 * zero-copy access from ML frameworks.
 */
export declare class StateMatrices {
  /** Zone air temperatures in °C [timesteps x num_zones] */
  zoneTemperatures: Array<number>
  /** Thermal mass temperatures in °C [timesteps x num_zones] */
  massTemperatures: Array<number>
  /** Heating energy demand in W [timesteps] */
  heatingLoads: Array<number>
  /** Cooling energy demand in W [timesteps] */
  coolingLoads: Array<number>
  /** Solar heat gains in W [timesteps x num_zones] */
  solarGains: Array<number>
}

/** Error thrown when AI surrogate model evaluation fails. */
export declare class SurrogateError {
  /** Create a new SurrogateError with a message. */
  constructor(message: string)
  /** Get the error message. */
  get message(): string
}

/** Error thrown when simulation parameters are invalid. */
export declare class ValidationError {
  /** Create a new ValidationError with a message. */
  constructor(message: string)
  /** Get the error message. */
  get message(): string
}

/**
 * JavaScript-accessible 9R4C sub-hourly nodal temperature tracer.
 *
 * Steps the 9R4C multi-node solver forward at sub-hourly resolution
 * (e.g. 5- or 15-minute sub-steps) and returns per-node temperature
 * series as typed arrays. Issue #1800 (T9.6): Node parity with T9.5.
 *
 * # TypeScript Example
 * ```typescript
 * import { NineR4CNodalTracer } from '@fluxion/native';
 *
 * const tracer = new NineR4CNodalTracer();
 * const trace = tracer.runSubHourlyTrace({
 *   dtSeconds: 300.0,
 *   timesteps: 288,
 *   couplingMode: 'additive_sum',
 *   initialZoneTemperature: 20.0,
 *   surfaceExteriorTemperatures: {
 *     tExtWall: 0.0,
 *     tExtRoof: 0.0,
 *     tExtFloor: 0.0,
 *   },
 *   hTrIs: 10.0,
 * });
 *
 * console.log(`Wall[0]   = ${trace.wall[0].toFixed(2)} °C`);
 * console.log(`Zone[287] = ${trace.zone[287].toFixed(2)} °C`);
 * ```
 */
export declare class NineR4CNodalTracer {
  /** Create a tracer with documented 9R4C defaults. */
  constructor()
  /**
   * Replace the per-node thermal mass parameters and conductances.
   * Mirrors the layout of the T9.2 `NineR4CConfig::from_surface_parameters`.
   */
  configureNodes(
    wallCm: number,
    wallHTrMs: number,
    wallHTrEm: number,
    wallHTrMe: number,
    roofCm: number,
    roofHTrMs: number,
    roofHTrEm: number,
    roofHTrMe: number,
    floorCm: number,
    floorHTrMs: number,
    floorHTrEm: number,
    floorHTrMe: number,
    internalCm: number,
    internalHTrMs: number,
    internalHTrEm: number,
    internalHTrMe: number,
  ): void
  /**
   * Run the sub-hourly nodal temperature trace and return the
   * per-node temperature series.
   *
   * @throws Error if `dtSeconds` is non-positive, `timesteps` is zero,
   * or `gains.length !== timesteps`.
   */
  runSubHourlyTrace(params: NineR4CTraceParams): NineR4CNodalTrace
}

/** Per-surface exterior boundary temperatures used by the 9R4C solver. */
export interface ExteriorTemperatureSet {
  /** Wall sol-air / exterior temperature [°C]. */
  tExtWall: number
  /** Roof sol-air / exterior temperature [°C]. */
  tExtRoof: number
  /** Floor ground / exterior temperature [°C]. */
  tExtFloor: number
}

/** Sub-hourly trace parameters accepted by {@link NineR4CNodalTracer.runSubHourlyTrace}. */
export interface NineR4CTraceParams {
  /** Sub-step duration in seconds. Must be positive and finite. */
  dtSeconds: number
  /** Number of sub-steps to record. Must be non-zero. */
  timesteps: number
  /** Coupling mode: `"additive_sum"` (default) or `"parallel_resistance"`. */
  couplingMode?: string
  /** Initial zone air temperature [°C]. Defaults to `20.0`. */
  initialZoneTemperature?: number
  /** Optional `[wall, roof, floor, internal]` seed vector [°C]. */
  initialNodeTemperature?: Array<number>
  /** Per-surface exterior boundary temperatures [°C]. */
  surfaceExteriorTemperatures?: ExteriorTemperatureSet
  /** Zone-air-to-surface conductance [W/K]. Defaults to `10.0`. */
  hTrIs?: number
  /** Optional array of per-timestep gain vectors `[gw, gr, gf, gi]` in watts. */
  gains?: Array<Array<number>>
}

/** Sub-hourly nodal temperature trace returned by {@link NineR4CNodalTracer.runSubHourlyTrace}. */
export declare class NineR4CNodalTrace {
  /** Number of sub-steps recorded (length of each series). */
  timesteps: number
  /** Sub-step duration in seconds. */
  dtSeconds: number
  /** Coupling mode used for this trace. */
  couplingMode: string
  /** Wall mass-node temperatures after each sub-step [°C]. */
  wall: Array<number>
  /** Roof mass-node temperatures after each sub-step [°C]. */
  roof: Array<number>
  /** Floor mass-node temperatures after each sub-step [°C]. */
  floor: Array<number>
  /** Internal mass-node temperatures after each sub-step [°C]. */
  internal: Array<number>
  /** Zone air temperature after each sub-step [°C]. */
  zone: Array<number>
}

export declare function register(): void
